%toplevel script
function main()
  preamble();
  build_comp_library();
  build_circuit();
end
%
%
%circuit build script
function build_circuit()
  add_block('simulink/Ports & Subsystems/Subsystem','ckt_gentoggle_0_odeIdeal/circuit');
  set_param('ckt_gentoggle_0_odeIdeal/circuit','position',[989,333,1039,353]);
  delete_line('ckt_gentoggle_0_odeIdeal/circuit','In1/1','Out1/1');
  delete_block('ckt_gentoggle_0_odeIdeal/circuit/In1');
  delete_block('ckt_gentoggle_0_odeIdeal/circuit/Out1');
  add_block('ckt_gentoggle_0_odeIdeal/library/vgain','ckt_gentoggle_0_odeIdeal/circuit/vgain[14]');
  add_block('ckt_gentoggle_0_odeIdeal/library/vgain','ckt_gentoggle_0_odeIdeal/circuit/vgain[4]');
  add_block('ckt_gentoggle_0_odeIdeal/library/switch','ckt_gentoggle_0_odeIdeal/circuit/switch[16]');
  add_block('ckt_gentoggle_0_odeIdeal/library/switch','ckt_gentoggle_0_odeIdeal/circuit/switch[1]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.I','ckt_gentoggle_0_odeIdeal/circuit/input.I[2]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.I','ckt_gentoggle_0_odeIdeal/circuit/input.I[20]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.I','ckt_gentoggle_0_odeIdeal/circuit/input.I[8]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.I','ckt_gentoggle_0_odeIdeal/circuit/input.I[7]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.I','ckt_gentoggle_0_odeIdeal/circuit/input.I[13]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.I','ckt_gentoggle_0_odeIdeal/circuit/input.I[12]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.I','ckt_gentoggle_0_odeIdeal/circuit/input.I[31]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.I','ckt_gentoggle_0_odeIdeal/circuit/input.I[9]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.I','ckt_gentoggle_0_odeIdeal/circuit/input.I[0]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.I','ckt_gentoggle_0_odeIdeal/circuit/input.I[11]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.I','ckt_gentoggle_0_odeIdeal/circuit/input.I[10]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.I','ckt_gentoggle_0_odeIdeal/circuit/input.I[15]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.I','ckt_gentoggle_0_odeIdeal/circuit/input.I[6]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.I','ckt_gentoggle_0_odeIdeal/circuit/input.I[14]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.I','ckt_gentoggle_0_odeIdeal/circuit/input.I[21]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.I','ckt_gentoggle_0_odeIdeal/circuit/input.I[16]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.I','ckt_gentoggle_0_odeIdeal/circuit/input.I[30]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.I','ckt_gentoggle_0_odeIdeal/circuit/input.I[3]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.I','ckt_gentoggle_0_odeIdeal/circuit/input.I[4]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.I','ckt_gentoggle_0_odeIdeal/circuit/input.I[5]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.I','ckt_gentoggle_0_odeIdeal/circuit/input.I[1]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.I','ckt_gentoggle_0_odeIdeal/circuit/input.I[17]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.I','ckt_gentoggle_0_odeIdeal/circuit/input.I[32]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.I','ckt_gentoggle_0_odeIdeal/circuit/input.I[18]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.I','ckt_gentoggle_0_odeIdeal/circuit/input.I[19]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.I','ckt_gentoggle_0_odeIdeal/circuit/input.I[22]');
  add_block('ckt_gentoggle_0_odeIdeal/library/output.V','ckt_gentoggle_0_odeIdeal/circuit/output.V[0]');
  add_block('ckt_gentoggle_0_odeIdeal/library/output.V','ckt_gentoggle_0_odeIdeal/circuit/output.V[1]');
  add_block('ckt_gentoggle_0_odeIdeal/library/vadd','ckt_gentoggle_0_odeIdeal/circuit/vadd[7]');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_468');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_468','Value','1.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_468','position',[620,788,670,808]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_468/1','vadd[7]/6');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_470');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_470','Value','1.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_470','position',[943,989,993,1009]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_470/1','vadd[7]/7');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_472');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_472','Value','1.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_472','position',[396,96,446,116]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_472/1','vadd[7]/8');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/vadd[7]/int_375','InitialCondition','0.');
  add_block('ckt_gentoggle_0_odeIdeal/library/vadd','ckt_gentoggle_0_odeIdeal/circuit/vadd[5]');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_474');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_474','Value','1.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_474','position',[72,141,122,161]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_474/1','vadd[5]/6');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_476');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_476','Value','1.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_476','position',[644,776,694,796]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_476/1','vadd[5]/7');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_478');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_478','Value','1.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_478','position',[112,837,162,857]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_478/1','vadd[5]/8');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/vadd[5]/int_375','InitialCondition','0.');
  add_block('ckt_gentoggle_0_odeIdeal/library/vtoi','ckt_gentoggle_0_odeIdeal/circuit/vtoi[13]');
  add_block('ckt_gentoggle_0_odeIdeal/library/vtoi','ckt_gentoggle_0_odeIdeal/circuit/vtoi[9]');
  add_block('ckt_gentoggle_0_odeIdeal/library/vtoi','ckt_gentoggle_0_odeIdeal/circuit/vtoi[0]');
  add_block('ckt_gentoggle_0_odeIdeal/library/igenebind','ckt_gentoggle_0_odeIdeal/circuit/igenebind[8]');
  add_block('ckt_gentoggle_0_odeIdeal/library/igenebind','ckt_gentoggle_0_odeIdeal/circuit/igenebind[10]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.V','ckt_gentoggle_0_odeIdeal/circuit/input.V[20]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.V','ckt_gentoggle_0_odeIdeal/circuit/input.V[2]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.V','ckt_gentoggle_0_odeIdeal/circuit/input.V[8]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.V','ckt_gentoggle_0_odeIdeal/circuit/input.V[7]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.V','ckt_gentoggle_0_odeIdeal/circuit/input.V[13]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.V','ckt_gentoggle_0_odeIdeal/circuit/input.V[12]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.V','ckt_gentoggle_0_odeIdeal/circuit/input.V[9]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.V','ckt_gentoggle_0_odeIdeal/circuit/input.V[0]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.V','ckt_gentoggle_0_odeIdeal/circuit/input.V[11]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.V','ckt_gentoggle_0_odeIdeal/circuit/input.V[10]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.V','ckt_gentoggle_0_odeIdeal/circuit/input.V[15]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.V','ckt_gentoggle_0_odeIdeal/circuit/input.V[6]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.V','ckt_gentoggle_0_odeIdeal/circuit/input.V[14]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.V','ckt_gentoggle_0_odeIdeal/circuit/input.V[16]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.V','ckt_gentoggle_0_odeIdeal/circuit/input.V[3]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.V','ckt_gentoggle_0_odeIdeal/circuit/input.V[4]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.V','ckt_gentoggle_0_odeIdeal/circuit/input.V[5]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.V','ckt_gentoggle_0_odeIdeal/circuit/input.V[1]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.V','ckt_gentoggle_0_odeIdeal/circuit/input.V[17]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.V','ckt_gentoggle_0_odeIdeal/circuit/input.V[18]');
  add_block('ckt_gentoggle_0_odeIdeal/library/itov','ckt_gentoggle_0_odeIdeal/circuit/itov[15]');
  add_block('ckt_gentoggle_0_odeIdeal/library/itov','ckt_gentoggle_0_odeIdeal/circuit/itov[6]');
  add_block('ckt_gentoggle_0_odeIdeal/library/itov','ckt_gentoggle_0_odeIdeal/circuit/itov[16]');
  add_block('ckt_gentoggle_0_odeIdeal/library/iadd','ckt_gentoggle_0_odeIdeal/circuit/iadd[2]');
  add_block('ckt_gentoggle_0_odeIdeal/library/iadd','ckt_gentoggle_0_odeIdeal/circuit/iadd[12]');
  add_block('ckt_gentoggle_0_odeIdeal/library/iadd','ckt_gentoggle_0_odeIdeal/circuit/iadd[11]');
  add_block('ckt_gentoggle_0_odeIdeal/library/iadd','ckt_gentoggle_0_odeIdeal/circuit/iadd[3]');
  add_block('ckt_gentoggle_0_odeIdeal/library/iadd','ckt_gentoggle_0_odeIdeal/circuit/iadd[17]');
  add_block('ckt_gentoggle_0_odeIdeal/library/iadd','ckt_gentoggle_0_odeIdeal/circuit/iadd[18]');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','switch[1]/1','iadd[18]/4');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.I[0]/1','igenebind[10]/3');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.V[15]/1','vgain[4]/1');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.I[22]/1','switch[16]/4');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.I[32]/1','iadd[18]/3');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.V[13]/1','switch[1]/1');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','vgain[14]/1','vtoi[13]/2');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.V[14]/1','vtoi[0]/1');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','vtoi[0]/1','iadd[3]/4');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','iadd[12]/1','iadd[11]/4');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.I[30]/1','iadd[18]/2');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.I[14]/1','iadd[17]/4');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.V[11]/1','vadd[5]/2');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','itov[15]/1','vgain[14]/3');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','switch[16]/1','itov[15]/1');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','vadd[5]/2','output.V[0]/1');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','vadd[5]/2','vtoi[9]/1');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.I[12]/1','iadd[12]/3');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.I[10]/1','iadd[11]/2');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','iadd[11]/1','igenebind[10]/1');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.V[20]/1','itov[16]/2');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.I[7]/1','iadd[3]/2');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','iadd[3]/1','iadd[2]/4');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','iadd[17]/1','switch[16]/2');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','iadd[18]/1','igenebind[8]/2');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','iadd[2]/1','switch[1]/3');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.I[8]/1','iadd[11]/1');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','itov[6]/1','vadd[7]/5');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.I[21]/1','iadd[17]/2');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','itov[16]/1','vgain[4]/3');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.V[16]/1','vtoi[13]/1');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.V[5]/1','vadd[5]/3');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','vtoi[9]/1','iadd[17]/1');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.V[6]/1','vadd[7]/4');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.I[11]/1','iadd[12]/1');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','vadd[7]/2','output.V[1]/1');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','vadd[7]/2','switch[1]/4');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.I[6]/1','iadd[3]/3');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.V[17]/1','vgain[14]/2');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.I[31]/1','iadd[18]/1');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.V[9]/1','vadd[5]/1');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','vtoi[13]/1','iadd[12]/4');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','igenebind[8]/1','itov[16]/1');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.I[18]/1','igenebind[8]/1');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.I[9]/1','iadd[11]/3');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.I[16]/1','switch[1]/2');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.I[3]/1','iadd[2]/3');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.I[4]/1','iadd[2]/2');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','igenebind[10]/1','itov[6]/2');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.I[5]/1','iadd[3]/1');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.V[8]/1','vadd[7]/1');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.I[2]/1','iadd[2]/1');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.V[12]/1','vadd[7]/2');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.V[2]/1','switch[16]/1');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.I[20]/1','switch[16]/3');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.V[3]/1','vgain[4]/2');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.I[15]/1','iadd[17]/3');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.I[1]/1','igenebind[8]/3');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.V[1]/1','vgain[14]/1');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.I[13]/1','iadd[12]/2');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.I[17]/1','itov[6]/1');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.V[7]/1','vadd[7]/3');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','vgain[4]/1','vadd[5]/5');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.V[10]/1','vtoi[9]/2');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.V[0]/1','vtoi[0]/2');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.V[18]/1','itov[15]/2');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.V[4]/1','vadd[5]/4');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.I[19]/1','igenebind[10]/2');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/circuit/input.V[0]_in');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/circuit/_input.V[0]_in');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/input.V[0]_in','position',[914,707,964,727]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.V[0]_in/1','_input.V[0]_in/1');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','_input.V[0]_in/1','input.V[0]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_485');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_485','Value','2.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_485','position',[427,439,477,459]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_485/1','input.V[1]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_487');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_487','Value','0.15625');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_487','position',[936,838,986,858]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_487/1','input.I[0]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_489');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_489','Value','1250.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_489','position',[508,939,558,959]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_489/1','input.V[2]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_491');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_491','Value','0.0156');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_491','position',[963,589,1013,609]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_491/1','input.I[1]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_493');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_493','Value','0.125');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_493','position',[141,427,191,447]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_493/1','input.V[3]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_495');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_495','Value','0.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_495','position',[558,469,608,489]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_495/1','input.I[30]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_497');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_497','Value','0.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_497','position',[391,718,441,738]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_497/1','input.I[31]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_499');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_499','Value','0.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_499','position',[695,43,745,63]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_499/1','input.I[32]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_501');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_501','Value','0.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_501','position',[42,591,92,611]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_501/1','input.I[2]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_503');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_503','Value','0.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_503','position',[272,99,322,119]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_503/1','input.I[3]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_505');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_505','Value','0.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_505','position',[274,698,324,718]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_505/1','input.I[4]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_507');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_507','Value','0.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_507','position',[644,312,694,332]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_507/1','input.I[5]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_509');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_509','Value','0.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_509','position',[635,325,685,345]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_509/1','input.I[6]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_511');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_511','Value','0.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_511','position',[572,808,622,828]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_511/1','input.I[7]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_513');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_513','Value','0.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_513','position',[796,486,846,506]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_513/1','input.V[4]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_515');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_515','Value','0.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_515','position',[975,543,1025,563]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_515/1','input.V[5]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_517');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_517','Value','0.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_517','position',[155,900,205,920]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_517/1','input.V[6]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_519');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_519','Value','0.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_519','position',[110,950,160,970]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_519/1','input.V[7]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_521');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_521','Value','0.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_521','position',[162,269,212,289]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_521/1','input.I[8]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_523');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_523','Value','0.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_523','position',[758,415,808,435]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_523/1','input.I[9]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_525');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_525','Value','0.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_525','position',[259,300,309,320]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_525/1','input.I[10]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_527');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_527','Value','0.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_527','position',[880,352,930,372]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_527/1','input.I[11]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_529');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_529','Value','0.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_529','position',[314,488,364,508]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_529/1','input.I[12]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_531');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_531','Value','0.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_531','position',[704,71,754,91]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_531/1','input.I[13]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_533');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_533','Value','0.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_533','position',[867,125,917,145]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_533/1','input.I[14]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_535');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_535','Value','0.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_535','position',[732,116,782,136]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_535/1','input.I[15]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_537');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_537','Value','0.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_537','position',[1,382,51,402]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_537/1','input.V[8]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_539');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_539','Value','0.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_539','position',[912,727,962,747]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_539/1','input.V[9]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_541');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_541','Value','337.632520764');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_541','position',[644,51,694,71]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_541/1','input.I[16]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_543');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_543','Value','-1.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_543','position',[424,512,474,532]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_543/1','input.V[10]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_545');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_545','Value','4.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_545','position',[142,308,192,328]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_545/1','input.V[11]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_547');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_547','Value','4.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_547','position',[315,131,365,151]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_547/1','input.V[12]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_549');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_549','Value','4.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_549','position',[426,476,476,496]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_549/1','input.I[17]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_551');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_551','Value','1000.75');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_551','position',[135,814,185,834]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_551/1','input.V[13]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_553');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_553','Value','1.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_553','position',[662,539,712,559]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_553/1','input.V[20]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_555');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_555','Value','1.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_555','position',[889,620,939,640]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_555/1','input.V[14]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_557');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_557','Value','1.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_557','position',[463,300,513,320]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_557/1','input.V[15]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_559');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_559','Value','1.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_559','position',[189,356,239,376]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_559/1','input.I[18]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_561');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_561','Value','1.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_561','position',[567,595,617,615]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_561/1','input.I[19]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_563');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_563','Value','1.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_563','position',[607,514,657,534]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_563/1','input.V[16]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_565');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_565','Value','1.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_565','position',[926,503,976,523]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_565/1','input.V[17]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_567');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_567','Value','1.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_567','position',[17,302,67,322]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_567/1','input.V[18]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_569');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_569','Value','1.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_569','position',[272,963,322,983]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_569/1','input.I[20]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_571');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_571','Value','1.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_571','position',[947,48,997,68]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_571/1','input.I[21]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_573');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_573','Value','1.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_573','position',[469,816,519,836]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_573/1','input.I[22]/1');
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_0_odeIdeal/circuit/output.V[0]_out');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/circuit/_output.V[0]_out');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','_output.V[0]_out/1','output.V[0]_out/1');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/output.V[0]_out','position',[760,732,810,752]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','output.V[0]/1','_output.V[0]_out/1');
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_0_odeIdeal/circuit/output.V[1]_out');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/circuit/_output.V[1]_out');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','_output.V[1]_out/1','output.V[1]_out/1');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/output.V[1]_out','position',[559,476,609,496]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','output.V[1]/1','_output.V[1]_out/1');
end
%
%
%preamble function
function preamble()
  %define model name
  model_name='ckt_gentoggle_0_odeIdeal';
  %create and open the model
  open_system(new_system(model_name));
  %set solver method
  set_param(model_name,'Solver','ode3');
end
%
%
%library assembly function
function build_comp_library()
  add_block('simulink/Ports & Subsystems/Subsystem','ckt_gentoggle_0_odeIdeal/library');
  set_param('ckt_gentoggle_0_odeIdeal/library','position',[389,613,439,633]);
  delete_line('ckt_gentoggle_0_odeIdeal/library','In1/1','Out1/1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/In1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/Out1');
  %
  %
  %
  add_block('simulink/Ports & Subsystems/Subsystem','ckt_gentoggle_0_odeIdeal/library/mm');
  set_param('ckt_gentoggle_0_odeIdeal/library/mm','position',[501,286,551,306]);
  delete_line('ckt_gentoggle_0_odeIdeal/library/mm','In1/1','Out1/1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/mm/In1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/mm/Out1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/mm/kr');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/mm/_kr');
  set_param('ckt_gentoggle_0_odeIdeal/library/mm/kr','position',[58,468,108,488]);
  add_line('ckt_gentoggle_0_odeIdeal/library/mm','kr/1','_kr/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/mm/XY0');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/mm/_XY0');
  set_param('ckt_gentoggle_0_odeIdeal/library/mm/XY0','position',[759,378,809,398]);
  add_line('ckt_gentoggle_0_odeIdeal/library/mm','XY0/1','_XY0/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/mm/Ytot');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/mm/_Ytot');
  set_param('ckt_gentoggle_0_odeIdeal/library/mm/Ytot','position',[217,793,267,813]);
  add_line('ckt_gentoggle_0_odeIdeal/library/mm','Ytot/1','_Ytot/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/mm/kf');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/mm/_kf');
  set_param('ckt_gentoggle_0_odeIdeal/library/mm/kf','position',[858,133,908,153]);
  add_line('ckt_gentoggle_0_odeIdeal/library/mm','kf/1','_kf/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/mm/Xtot');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/mm/_Xtot');
  set_param('ckt_gentoggle_0_odeIdeal/library/mm/Xtot','position',[469,194,519,214]);
  add_line('ckt_gentoggle_0_odeIdeal/library/mm','Xtot/1','_Xtot/1');
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_0_odeIdeal/library/mm/X');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/mm/_X');
  add_line('ckt_gentoggle_0_odeIdeal/library/mm','_X/1','X/1');
  set_param('ckt_gentoggle_0_odeIdeal/library/mm/X','position',[299,49,349,69]);
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_0_odeIdeal/library/mm/XY');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/mm/_XY');
  add_line('ckt_gentoggle_0_odeIdeal/library/mm','_XY/1','XY/1');
  set_param('ckt_gentoggle_0_odeIdeal/library/mm/XY','position',[371,27,421,47]);
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_0_odeIdeal/library/mm/Y');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/mm/_Y');
  add_line('ckt_gentoggle_0_odeIdeal/library/mm','_Y/1','Y/1');
  set_param('ckt_gentoggle_0_odeIdeal/library/mm/Y','position',[532,133,582,153]);
  add_block('simulink/Math Operations/Sum','ckt_gentoggle_0_odeIdeal/library/mm/sum_39');
  set_param('ckt_gentoggle_0_odeIdeal/library/mm/sum_39','Inputs','+-');
  set_param('ckt_gentoggle_0_odeIdeal/library/mm/sum_39','position',[685,10,735,30]);
  add_line('ckt_gentoggle_0_odeIdeal/library/mm','_Xtot/1','sum_39/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/mm','_XY/1','sum_39/2');
  add_line('ckt_gentoggle_0_odeIdeal/library/mm','sum_39/1','_X/1');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_0_odeIdeal/library/mm/mul_42');
  set_param('ckt_gentoggle_0_odeIdeal/library/mm/mul_42','Inputs','***');
  set_param('ckt_gentoggle_0_odeIdeal/library/mm/mul_42','position',[643,468,693,488]);
  add_line('ckt_gentoggle_0_odeIdeal/library/mm','_kf/1','mul_42/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/mm','_X/1','mul_42/2');
  add_line('ckt_gentoggle_0_odeIdeal/library/mm','_Y/1','mul_42/3');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_0_odeIdeal/library/mm/mul_46');
  set_param('ckt_gentoggle_0_odeIdeal/library/mm/mul_46','Inputs','**');
  set_param('ckt_gentoggle_0_odeIdeal/library/mm/mul_46','position',[761,498,811,518]);
  add_line('ckt_gentoggle_0_odeIdeal/library/mm','_kr/1','mul_46/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/mm','_XY/1','mul_46/2');
  add_block('simulink/Math Operations/Sum','ckt_gentoggle_0_odeIdeal/library/mm/sum_49');
  set_param('ckt_gentoggle_0_odeIdeal/library/mm/sum_49','Inputs','+-');
  set_param('ckt_gentoggle_0_odeIdeal/library/mm/sum_49','position',[583,684,633,704]);
  add_line('ckt_gentoggle_0_odeIdeal/library/mm','mul_42/1','sum_49/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/mm','mul_46/1','sum_49/2');
  add_block('simulink/Continuous/Integrator','ckt_gentoggle_0_odeIdeal/library/mm/int_52');
  set_param('ckt_gentoggle_0_odeIdeal/library/mm/int_52','position',[630,896,680,916]);
  add_line('ckt_gentoggle_0_odeIdeal/library/mm','sum_49/1','int_52/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/mm','int_52/1','_XY/1');
  add_block('simulink/Math Operations/Sum','ckt_gentoggle_0_odeIdeal/library/mm/sum_54');
  set_param('ckt_gentoggle_0_odeIdeal/library/mm/sum_54','Inputs','+-');
  set_param('ckt_gentoggle_0_odeIdeal/library/mm/sum_54','position',[91,764,141,784]);
  add_line('ckt_gentoggle_0_odeIdeal/library/mm','_Ytot/1','sum_54/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/mm','_XY/1','sum_54/2');
  add_line('ckt_gentoggle_0_odeIdeal/library/mm','sum_54/1','_Y/1');
  %
  add_block('simulink/Ports & Subsystems/Subsystem','ckt_gentoggle_0_odeIdeal/library/vgain');
  set_param('ckt_gentoggle_0_odeIdeal/library/vgain','position',[415,706,465,726]);
  delete_line('ckt_gentoggle_0_odeIdeal/library/vgain','In1/1','Out1/1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/vgain/In1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/vgain/Out1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/vgain/X');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/vgain/_X');
  set_param('ckt_gentoggle_0_odeIdeal/library/vgain/X','position',[95,6,145,26]);
  add_line('ckt_gentoggle_0_odeIdeal/library/vgain','X/1','_X/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/vgain/Y');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/vgain/_Y');
  set_param('ckt_gentoggle_0_odeIdeal/library/vgain/Y','position',[684,144,734,164]);
  add_line('ckt_gentoggle_0_odeIdeal/library/vgain','Y/1','_Y/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/vgain/Z');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/vgain/_Z');
  set_param('ckt_gentoggle_0_odeIdeal/library/vgain/Z','position',[236,250,286,270]);
  add_line('ckt_gentoggle_0_odeIdeal/library/vgain','Z/1','_Z/1');
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_0_odeIdeal/library/vgain/P');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/vgain/_P');
  add_line('ckt_gentoggle_0_odeIdeal/library/vgain','_P/1','P/1');
  set_param('ckt_gentoggle_0_odeIdeal/library/vgain/P','position',[167,105,217,125]);
  add_block('simulink/Math Operations/Product','ckt_gentoggle_0_odeIdeal/library/vgain/div_77');
  set_param('ckt_gentoggle_0_odeIdeal/library/vgain/div_77','Inputs','*/');
  set_param('ckt_gentoggle_0_odeIdeal/library/vgain/div_77','position',[546,27,596,47]);
  add_line('ckt_gentoggle_0_odeIdeal/library/vgain','_X/1','div_77/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/vgain','_Y/1','div_77/2');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/library/vgain/const_80');
  set_param('ckt_gentoggle_0_odeIdeal/library/vgain/const_80','Value','0.5');
  set_param('ckt_gentoggle_0_odeIdeal/library/vgain/const_80','position',[354,479,404,499]);
  add_block('simulink/Math Operations/Product','ckt_gentoggle_0_odeIdeal/library/vgain/mul_82');
  set_param('ckt_gentoggle_0_odeIdeal/library/vgain/mul_82','Inputs','***');
  set_param('ckt_gentoggle_0_odeIdeal/library/vgain/mul_82','position',[930,21,980,41]);
  add_line('ckt_gentoggle_0_odeIdeal/library/vgain','div_77/1','mul_82/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/vgain','_Z/1','mul_82/2');
  add_line('ckt_gentoggle_0_odeIdeal/library/vgain','const_80/1','mul_82/3');
  add_line('ckt_gentoggle_0_odeIdeal/library/vgain','mul_82/1','_P/1');
  %
  add_block('simulink/Ports & Subsystems/Subsystem','ckt_gentoggle_0_odeIdeal/library/switch');
  set_param('ckt_gentoggle_0_odeIdeal/library/switch','position',[546,581,596,601]);
  delete_line('ckt_gentoggle_0_odeIdeal/library/switch','In1/1','Out1/1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/switch/In1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/switch/Out1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/switch/n');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/switch/_n');
  set_param('ckt_gentoggle_0_odeIdeal/library/switch/n','position',[614,876,664,896]);
  add_line('ckt_gentoggle_0_odeIdeal/library/switch','n/1','_n/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/switch/SUB');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/switch/_SUB');
  set_param('ckt_gentoggle_0_odeIdeal/library/switch/SUB','position',[42,20,92,40]);
  add_line('ckt_gentoggle_0_odeIdeal/library/switch','SUB/1','_SUB/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/switch/Kmod');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/switch/_Kmod');
  set_param('ckt_gentoggle_0_odeIdeal/library/switch/Kmod','position',[106,375,156,395]);
  add_line('ckt_gentoggle_0_odeIdeal/library/switch','Kmod/1','_Kmod/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/switch/Vmax');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/switch/_Vmax');
  set_param('ckt_gentoggle_0_odeIdeal/library/switch/Vmax','position',[132,331,182,351]);
  add_line('ckt_gentoggle_0_odeIdeal/library/switch','Vmax/1','_Vmax/1');
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_0_odeIdeal/library/switch/PROD');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/switch/_PROD');
  add_line('ckt_gentoggle_0_odeIdeal/library/switch','_PROD/1','PROD/1');
  set_param('ckt_gentoggle_0_odeIdeal/library/switch/PROD','position',[364,77,414,97]);
  add_block('simulink/Math Operations/Product','ckt_gentoggle_0_odeIdeal/library/switch/div_111');
  set_param('ckt_gentoggle_0_odeIdeal/library/switch/div_111','Inputs','*/');
  set_param('ckt_gentoggle_0_odeIdeal/library/switch/div_111','position',[146,670,196,690]);
  add_line('ckt_gentoggle_0_odeIdeal/library/switch','_SUB/1','div_111/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/switch','_Kmod/1','div_111/2');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/library/switch/const_114');
  set_param('ckt_gentoggle_0_odeIdeal/library/switch/const_114','Value','1.');
  set_param('ckt_gentoggle_0_odeIdeal/library/switch/const_114','position',[694,840,744,860]);
  add_block('simulink/Math Operations/Sum','ckt_gentoggle_0_odeIdeal/library/switch/sub_116');
  set_param('ckt_gentoggle_0_odeIdeal/library/switch/sub_116','Inputs','++');
  set_param('ckt_gentoggle_0_odeIdeal/library/switch/sub_116','position',[306,836,356,856]);
  add_line('ckt_gentoggle_0_odeIdeal/library/switch','div_111/1','sub_116/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/switch','const_114/1','sub_116/2');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/library/switch/const_119');
  set_param('ckt_gentoggle_0_odeIdeal/library/switch/const_119','Value','500.');
  set_param('ckt_gentoggle_0_odeIdeal/library/switch/const_119','position',[523,128,573,148]);
  add_block('simulink/Math Operations/Product','ckt_gentoggle_0_odeIdeal/library/switch/div_121');
  set_param('ckt_gentoggle_0_odeIdeal/library/switch/div_121','Inputs','*/');
  set_param('ckt_gentoggle_0_odeIdeal/library/switch/div_121','position',[292,311,342,331]);
  add_line('ckt_gentoggle_0_odeIdeal/library/switch','_n/1','div_121/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/switch','const_119/1','div_121/2');
  add_block('simulink/Math Operations/Math Function','ckt_gentoggle_0_odeIdeal/library/switch/pow_124');
  set_param('ckt_gentoggle_0_odeIdeal/library/switch/pow_124','Function','pow');
  set_param('ckt_gentoggle_0_odeIdeal/library/switch/pow_124','position',[328,696,378,716]);
  add_line('ckt_gentoggle_0_odeIdeal/library/switch','div_121/1','pow_124/2');
  add_line('ckt_gentoggle_0_odeIdeal/library/switch','sub_116/1','pow_124/1');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_0_odeIdeal/library/switch/div_127');
  set_param('ckt_gentoggle_0_odeIdeal/library/switch/div_127','Inputs','*/');
  set_param('ckt_gentoggle_0_odeIdeal/library/switch/div_127','position',[150,720,200,740]);
  add_line('ckt_gentoggle_0_odeIdeal/library/switch','_Vmax/1','div_127/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/switch','pow_124/1','div_127/2');
  add_line('ckt_gentoggle_0_odeIdeal/library/switch','div_127/1','_PROD/1');
  %
  add_block('simulink/Ports & Subsystems/Subsystem','ckt_gentoggle_0_odeIdeal/library/ihill');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill','position',[645,261,695,281]);
  delete_line('ckt_gentoggle_0_odeIdeal/library/ihill','In1/1','Out1/1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/ihill/In1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/ihill/Out1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/ihill/n');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/ihill/_n');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/n','position',[686,38,736,58]);
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','n/1','_n/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/ihill/S');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/ihill/_S');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/S','position',[82,578,132,598]);
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','S/1','_S/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/ihill/Km');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/ihill/_Km');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/Km','position',[732,479,782,499]);
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','Km/1','_Km/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/ihill/Vmax');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/ihill/_Vmax');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/Vmax','position',[78,388,128,408]);
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','Vmax/1','_Vmax/1');
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_0_odeIdeal/library/ihill/STIM');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/ihill/_STIM');
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','_STIM/1','STIM/1');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/STIM','position',[297,673,347,693]);
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_0_odeIdeal/library/ihill/REP');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/ihill/_REP');
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','_REP/1','REP/1');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/REP','position',[204,197,254,217]);
  add_block('simulink/Math Operations/Product','ckt_gentoggle_0_odeIdeal/library/ihill/div_159');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/div_159','Inputs','*/');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/div_159','position',[242,535,292,555]);
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','_S/1','div_159/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','_Km/1','div_159/2');
  add_block('simulink/Math Operations/Math Function','ckt_gentoggle_0_odeIdeal/library/ihill/pow_162');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/pow_162','Function','pow');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/pow_162','position',[980,606,1030,626]);
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','_n/1','pow_162/2');
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','div_159/1','pow_162/1');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_0_odeIdeal/library/ihill/div_165');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/div_165','Inputs','*/');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/div_165','position',[103,999,153,1019]);
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','_S/1','div_165/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','_Km/1','div_165/2');
  add_block('simulink/Math Operations/Math Function','ckt_gentoggle_0_odeIdeal/library/ihill/pow_168');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/pow_168','Function','pow');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/pow_168','position',[132,86,182,106]);
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','_n/1','pow_168/2');
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','div_165/1','pow_168/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/library/ihill/const_171');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/const_171','Value','1.');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/const_171','position',[158,658,208,678]);
  add_block('simulink/Math Operations/Sum','ckt_gentoggle_0_odeIdeal/library/ihill/sub_173');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/sub_173','Inputs','++');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/sub_173','position',[946,55,996,75]);
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','pow_168/1','sub_173/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','const_171/1','sub_173/2');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_0_odeIdeal/library/ihill/div_176');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/div_176','Inputs','*/');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/div_176','position',[880,850,930,870]);
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','pow_162/1','div_176/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','sub_173/1','div_176/2');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_0_odeIdeal/library/ihill/mul_179');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/mul_179','Inputs','**');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/mul_179','position',[293,257,343,277]);
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','_Vmax/1','mul_179/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','div_176/1','mul_179/2');
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','mul_179/1','_STIM/1');
  add_block('simulink/Math Operations/Math Function','ckt_gentoggle_0_odeIdeal/library/ihill/pow_182');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/pow_182','Function','pow');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/pow_182','position',[287,865,337,885]);
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','_n/1','pow_182/2');
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','_Km/1','pow_182/1');
  add_block('simulink/Math Operations/Math Function','ckt_gentoggle_0_odeIdeal/library/ihill/pow_185');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/pow_185','Function','pow');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/pow_185','position',[215,405,265,425]);
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','_n/1','pow_185/2');
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','_S/1','pow_185/1');
  add_block('simulink/Math Operations/Math Function','ckt_gentoggle_0_odeIdeal/library/ihill/pow_188');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/pow_188','Function','pow');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/pow_188','position',[943,727,993,747]);
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','_n/1','pow_188/2');
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','_Km/1','pow_188/1');
  add_block('simulink/Math Operations/Sum','ckt_gentoggle_0_odeIdeal/library/ihill/sub_191');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/sub_191','Inputs','++');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/sub_191','position',[975,185,1025,205]);
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','pow_185/1','sub_191/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','pow_188/1','sub_191/2');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_0_odeIdeal/library/ihill/div_194');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/div_194','Inputs','*/');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/div_194','position',[628,866,678,886]);
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','pow_182/1','div_194/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','sub_191/1','div_194/2');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_0_odeIdeal/library/ihill/mul_197');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/mul_197','Inputs','**');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/mul_197','position',[326,429,376,449]);
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','_Vmax/1','mul_197/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','div_194/1','mul_197/2');
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','mul_197/1','_REP/1');
  %
  add_block('simulink/Ports & Subsystems/Subsystem','ckt_gentoggle_0_odeIdeal/library/itov');
  set_param('ckt_gentoggle_0_odeIdeal/library/itov','position',[48,417,98,437]);
  delete_line('ckt_gentoggle_0_odeIdeal/library/itov','In1/1','Out1/1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/itov/In1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/itov/Out1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/itov/X');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/itov/_X');
  set_param('ckt_gentoggle_0_odeIdeal/library/itov/X','position',[539,915,589,935]);
  add_line('ckt_gentoggle_0_odeIdeal/library/itov','X/1','_X/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/itov/K');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/itov/_K');
  set_param('ckt_gentoggle_0_odeIdeal/library/itov/K','position',[734,560,784,580]);
  add_line('ckt_gentoggle_0_odeIdeal/library/itov','K/1','_K/1');
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_0_odeIdeal/library/itov/Y');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/itov/_Y');
  add_line('ckt_gentoggle_0_odeIdeal/library/itov','_Y/1','Y/1');
  set_param('ckt_gentoggle_0_odeIdeal/library/itov/Y','position',[471,503,521,523]);
  add_block('simulink/Math Operations/Product','ckt_gentoggle_0_odeIdeal/library/itov/mul_215');
  set_param('ckt_gentoggle_0_odeIdeal/library/itov/mul_215','Inputs','**');
  set_param('ckt_gentoggle_0_odeIdeal/library/itov/mul_215','position',[793,563,843,583]);
  add_line('ckt_gentoggle_0_odeIdeal/library/itov','_K/1','mul_215/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/itov','_X/1','mul_215/2');
  add_line('ckt_gentoggle_0_odeIdeal/library/itov','mul_215/1','_Y/1');
  %
  add_block('simulink/Ports & Subsystems/Subsystem','ckt_gentoggle_0_odeIdeal/library/output.I');
  set_param('ckt_gentoggle_0_odeIdeal/library/output.I','position',[380,466,430,486]);
  delete_line('ckt_gentoggle_0_odeIdeal/library/output.I','In1/1','Out1/1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/output.I/In1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/output.I/Out1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/output.I/X');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/output.I/_X');
  set_param('ckt_gentoggle_0_odeIdeal/library/output.I/X','position',[503,323,553,343]);
  add_line('ckt_gentoggle_0_odeIdeal/library/output.I','X/1','_X/1');
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_0_odeIdeal/library/output.I/O');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/output.I/_O');
  add_line('ckt_gentoggle_0_odeIdeal/library/output.I','_O/1','O/1');
  set_param('ckt_gentoggle_0_odeIdeal/library/output.I/O','position',[82,575,132,595]);
  add_line('ckt_gentoggle_0_odeIdeal/library/output.I','_X/1','_O/1');
  %
  add_block('simulink/Ports & Subsystems/Subsystem','ckt_gentoggle_0_odeIdeal/library/output.V');
  set_param('ckt_gentoggle_0_odeIdeal/library/output.V','position',[846,749,896,769]);
  delete_line('ckt_gentoggle_0_odeIdeal/library/output.V','In1/1','Out1/1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/output.V/In1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/output.V/Out1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/output.V/X');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/output.V/_X');
  set_param('ckt_gentoggle_0_odeIdeal/library/output.V/X','position',[499,359,549,379]);
  add_line('ckt_gentoggle_0_odeIdeal/library/output.V','X/1','_X/1');
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_0_odeIdeal/library/output.V/O');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/output.V/_O');
  add_line('ckt_gentoggle_0_odeIdeal/library/output.V','_O/1','O/1');
  set_param('ckt_gentoggle_0_odeIdeal/library/output.V/O','position',[953,21,1003,41]);
  add_line('ckt_gentoggle_0_odeIdeal/library/output.V','_X/1','_O/1');
  %
  add_block('simulink/Ports & Subsystems/Subsystem','ckt_gentoggle_0_odeIdeal/library/input.V');
  set_param('ckt_gentoggle_0_odeIdeal/library/input.V','position',[580,285,630,305]);
  delete_line('ckt_gentoggle_0_odeIdeal/library/input.V','In1/1','Out1/1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/input.V/In1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/input.V/Out1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/input.V/X');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/input.V/_X');
  set_param('ckt_gentoggle_0_odeIdeal/library/input.V/X','position',[564,240,614,260]);
  add_block('simulink/Discontinuities/Quantizer','ckt_gentoggle_0_odeIdeal/library/input.V/smp_244');
  set_param('ckt_gentoggle_0_odeIdeal/library/input.V/smp_244','QuantizationInterval','1e-05');
  set_param('ckt_gentoggle_0_odeIdeal/library/input.V/smp_244','position',[594,178,644,198]);
  add_line('ckt_gentoggle_0_odeIdeal/library/input.V','X/1','smp_244/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/input.V','smp_244/1','_X/1');
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_0_odeIdeal/library/input.V/O');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/input.V/_O');
  add_line('ckt_gentoggle_0_odeIdeal/library/input.V','_O/1','O/1');
  set_param('ckt_gentoggle_0_odeIdeal/library/input.V/O','position',[195,854,245,874]);
  add_line('ckt_gentoggle_0_odeIdeal/library/input.V','_X/1','_O/1');
  %
  add_block('simulink/Ports & Subsystems/Subsystem','ckt_gentoggle_0_odeIdeal/library/copy.V');
  set_param('ckt_gentoggle_0_odeIdeal/library/copy.V','position',[604,476,654,496]);
  delete_line('ckt_gentoggle_0_odeIdeal/library/copy.V','In1/1','Out1/1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/copy.V/In1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/copy.V/Out1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/copy.V/X');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/copy.V/_X');
  set_param('ckt_gentoggle_0_odeIdeal/library/copy.V/X','position',[998,335,1048,355]);
  add_line('ckt_gentoggle_0_odeIdeal/library/copy.V','X/1','_X/1');
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_0_odeIdeal/library/copy.V/Y');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/copy.V/_Y');
  add_line('ckt_gentoggle_0_odeIdeal/library/copy.V','_Y/1','Y/1');
  set_param('ckt_gentoggle_0_odeIdeal/library/copy.V/Y','position',[398,841,448,861]);
  add_line('ckt_gentoggle_0_odeIdeal/library/copy.V','_X/1','_Y/1');
  %
  add_block('simulink/Ports & Subsystems/Subsystem','ckt_gentoggle_0_odeIdeal/library/vtoi');
  set_param('ckt_gentoggle_0_odeIdeal/library/vtoi','position',[744,889,794,909]);
  delete_line('ckt_gentoggle_0_odeIdeal/library/vtoi','In1/1','Out1/1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/vtoi/In1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/vtoi/Out1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/vtoi/X');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/vtoi/_X');
  set_param('ckt_gentoggle_0_odeIdeal/library/vtoi/X','position',[577,421,627,441]);
  add_line('ckt_gentoggle_0_odeIdeal/library/vtoi','X/1','_X/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/vtoi/K');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/vtoi/_K');
  set_param('ckt_gentoggle_0_odeIdeal/library/vtoi/K','position',[717,665,767,685]);
  add_line('ckt_gentoggle_0_odeIdeal/library/vtoi','K/1','_K/1');
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_0_odeIdeal/library/vtoi/Y');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/vtoi/_Y');
  add_line('ckt_gentoggle_0_odeIdeal/library/vtoi','_Y/1','Y/1');
  set_param('ckt_gentoggle_0_odeIdeal/library/vtoi/Y','position',[359,682,409,702]);
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/library/vtoi/const_275');
  set_param('ckt_gentoggle_0_odeIdeal/library/vtoi/const_275','Value','1.');
  set_param('ckt_gentoggle_0_odeIdeal/library/vtoi/const_275','position',[145,803,195,823]);
  add_block('simulink/Math Operations/Product','ckt_gentoggle_0_odeIdeal/library/vtoi/div_277');
  set_param('ckt_gentoggle_0_odeIdeal/library/vtoi/div_277','Inputs','*/');
  set_param('ckt_gentoggle_0_odeIdeal/library/vtoi/div_277','position',[654,486,704,506]);
  add_line('ckt_gentoggle_0_odeIdeal/library/vtoi','const_275/1','div_277/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/vtoi','_K/1','div_277/2');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_0_odeIdeal/library/vtoi/mul_280');
  set_param('ckt_gentoggle_0_odeIdeal/library/vtoi/mul_280','Inputs','**');
  set_param('ckt_gentoggle_0_odeIdeal/library/vtoi/mul_280','position',[734,956,784,976]);
  add_line('ckt_gentoggle_0_odeIdeal/library/vtoi','div_277/1','mul_280/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/vtoi','_X/1','mul_280/2');
  add_line('ckt_gentoggle_0_odeIdeal/library/vtoi','mul_280/1','_Y/1');
  %
  add_block('simulink/Ports & Subsystems/Subsystem','ckt_gentoggle_0_odeIdeal/library/vadd');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd','position',[892,473,942,493]);
  delete_line('ckt_gentoggle_0_odeIdeal/library/vadd','In1/1','Out1/1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/vadd/In1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/vadd/Out1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/vadd/OUT2_0');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/vadd/_OUT2_0');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/OUT2_0','position',[899,587,949,607]);
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','OUT2_0/1','_OUT2_0/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/vadd/D');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/vadd/_D');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/D','position',[826,898,876,918]);
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','D/1','_D/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/vadd/C');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/vadd/_C');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/C','position',[276,782,326,802]);
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','C/1','_C/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/vadd/A');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/vadd/_A');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/A','position',[602,118,652,138]);
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','A/1','_A/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/vadd/B');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/vadd/_B');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/B','position',[985,946,1035,966]);
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','B/1','_B/1');
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_0_odeIdeal/library/vadd/OUT');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/vadd/_OUT');
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','_OUT/1','OUT/1');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/OUT','position',[57,72,107,92]);
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_0_odeIdeal/library/vadd/OUT2');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/vadd/_OUT2');
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','_OUT2/1','OUT2/1');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/OUT2','position',[291,951,341,971]);
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/vadd/BSW');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/vadd/_BSW');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/BSW','position',[363,777,413,797]);
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','BSW/1','_BSW/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/vadd/CSW');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/vadd/_CSW');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/CSW','position',[7,236,57,256]);
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','CSW/1','_CSW/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/vadd/DSW');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/vadd/_DSW');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/DSW','position',[410,673,460,693]);
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','DSW/1','_DSW/1');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_0_odeIdeal/library/vadd/mul_332');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/mul_332','Inputs','**');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/mul_332','position',[205,732,255,752]);
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','_BSW/1','mul_332/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','_B/1','mul_332/2');
  add_block('simulink/Math Operations/Sum','ckt_gentoggle_0_odeIdeal/library/vadd/sub_335');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/sub_335','Inputs','++');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/sub_335','position',[982,856,1032,876]);
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','_A/1','sub_335/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','mul_332/1','sub_335/2');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_0_odeIdeal/library/vadd/mul_338');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/mul_338','Inputs','**');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/mul_338','position',[924,98,974,118]);
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','_CSW/1','mul_338/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','_C/1','mul_338/2');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_0_odeIdeal/library/vadd/mul_341');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/mul_341','Inputs','**');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/mul_341','position',[382,237,432,257]);
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','_DSW/1','mul_341/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','_D/1','mul_341/2');
  add_block('simulink/Math Operations/Sum','ckt_gentoggle_0_odeIdeal/library/vadd/sum_344');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/sum_344','Inputs','+--');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/sum_344','position',[660,478,710,498]);
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','sub_335/1','sum_344/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','mul_338/1','sum_344/2');
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','mul_341/1','sum_344/3');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/library/vadd/const_348');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/const_348','Value','0.25');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/const_348','position',[619,667,669,687]);
  add_block('simulink/Math Operations/Product','ckt_gentoggle_0_odeIdeal/library/vadd/mul_350');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/mul_350','Inputs','**');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/mul_350','position',[376,259,426,279]);
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','sum_344/1','mul_350/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','const_348/1','mul_350/2');
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','mul_350/1','_OUT/1');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_0_odeIdeal/library/vadd/mul_353');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/mul_353','Inputs','**');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/mul_353','position',[131,613,181,633]);
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','_BSW/1','mul_353/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','_B/1','mul_353/2');
  add_block('simulink/Math Operations/Sum','ckt_gentoggle_0_odeIdeal/library/vadd/sub_356');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/sub_356','Inputs','++');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/sub_356','position',[958,452,1008,472]);
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','_A/1','sub_356/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','mul_353/1','sub_356/2');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_0_odeIdeal/library/vadd/mul_359');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/mul_359','Inputs','**');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/mul_359','position',[33,1,83,21]);
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','_CSW/1','mul_359/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','_C/1','mul_359/2');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_0_odeIdeal/library/vadd/mul_362');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/mul_362','Inputs','***');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/mul_362','position',[490,729,540,749]);
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','_DSW/1','mul_362/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','_D/1','mul_362/2');
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','_OUT2/1','mul_362/3');
  add_block('simulink/Math Operations/Sum','ckt_gentoggle_0_odeIdeal/library/vadd/sum_366');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/sum_366','Inputs','+--');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/sum_366','position',[783,637,833,657]);
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','sub_356/1','sum_366/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','mul_359/1','sum_366/2');
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','mul_362/1','sum_366/3');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/library/vadd/const_370');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/const_370','Value','0.25');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/const_370','position',[442,210,492,230]);
  add_block('simulink/Math Operations/Product','ckt_gentoggle_0_odeIdeal/library/vadd/mul_372');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/mul_372','Inputs','**');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/mul_372','position',[192,716,242,736]);
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','sum_366/1','mul_372/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','const_370/1','mul_372/2');
  add_block('simulink/Continuous/Integrator','ckt_gentoggle_0_odeIdeal/library/vadd/int_375');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/int_375','position',[153,331,203,351]);
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','mul_372/1','int_375/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','int_375/1','_OUT2/1');
  %
  add_block('simulink/Ports & Subsystems/Subsystem','ckt_gentoggle_0_odeIdeal/library/copy.I');
  set_param('ckt_gentoggle_0_odeIdeal/library/copy.I','position',[883,238,933,258]);
  delete_line('ckt_gentoggle_0_odeIdeal/library/copy.I','In1/1','Out1/1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/copy.I/In1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/copy.I/Out1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/copy.I/X');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/copy.I/_X');
  set_param('ckt_gentoggle_0_odeIdeal/library/copy.I/X','position',[333,121,383,141]);
  add_line('ckt_gentoggle_0_odeIdeal/library/copy.I','X/1','_X/1');
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_0_odeIdeal/library/copy.I/Y');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/copy.I/_Y');
  add_line('ckt_gentoggle_0_odeIdeal/library/copy.I','_Y/1','Y/1');
  set_param('ckt_gentoggle_0_odeIdeal/library/copy.I/Y','position',[695,54,745,74]);
  add_line('ckt_gentoggle_0_odeIdeal/library/copy.I','_X/1','_Y/1');
  %
  add_block('simulink/Ports & Subsystems/Subsystem','ckt_gentoggle_0_odeIdeal/library/iadd');
  set_param('ckt_gentoggle_0_odeIdeal/library/iadd','position',[302,808,352,828]);
  delete_line('ckt_gentoggle_0_odeIdeal/library/iadd','In1/1','Out1/1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/iadd/In1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/iadd/Out1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/iadd/D');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/iadd/_D');
  set_param('ckt_gentoggle_0_odeIdeal/library/iadd/D','position',[254,373,304,393]);
  add_line('ckt_gentoggle_0_odeIdeal/library/iadd','D/1','_D/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/iadd/C');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/iadd/_C');
  set_param('ckt_gentoggle_0_odeIdeal/library/iadd/C','position',[805,938,855,958]);
  add_line('ckt_gentoggle_0_odeIdeal/library/iadd','C/1','_C/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/iadd/A');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/iadd/_A');
  set_param('ckt_gentoggle_0_odeIdeal/library/iadd/A','position',[185,420,235,440]);
  add_line('ckt_gentoggle_0_odeIdeal/library/iadd','A/1','_A/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/iadd/B');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/iadd/_B');
  set_param('ckt_gentoggle_0_odeIdeal/library/iadd/B','position',[672,532,722,552]);
  add_line('ckt_gentoggle_0_odeIdeal/library/iadd','B/1','_B/1');
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_0_odeIdeal/library/iadd/OUT');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/iadd/_OUT');
  add_line('ckt_gentoggle_0_odeIdeal/library/iadd','_OUT/1','OUT/1');
  set_param('ckt_gentoggle_0_odeIdeal/library/iadd/OUT','position',[388,189,438,209]);
  add_block('simulink/Math Operations/Sum','ckt_gentoggle_0_odeIdeal/library/iadd/sub_412');
  set_param('ckt_gentoggle_0_odeIdeal/library/iadd/sub_412','Inputs','++');
  set_param('ckt_gentoggle_0_odeIdeal/library/iadd/sub_412','position',[961,407,1011,427]);
  add_line('ckt_gentoggle_0_odeIdeal/library/iadd','_A/1','sub_412/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/iadd','_B/1','sub_412/2');
  add_block('simulink/Math Operations/Sum','ckt_gentoggle_0_odeIdeal/library/iadd/sum_415');
  set_param('ckt_gentoggle_0_odeIdeal/library/iadd/sum_415','Inputs','+--');
  set_param('ckt_gentoggle_0_odeIdeal/library/iadd/sum_415','position',[953,588,1003,608]);
  add_line('ckt_gentoggle_0_odeIdeal/library/iadd','sub_412/1','sum_415/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/iadd','_C/1','sum_415/2');
  add_line('ckt_gentoggle_0_odeIdeal/library/iadd','_D/1','sum_415/3');
  add_line('ckt_gentoggle_0_odeIdeal/library/iadd','sum_415/1','_OUT/1');
  %
  add_block('simulink/Ports & Subsystems/Subsystem','ckt_gentoggle_0_odeIdeal/library/input.I');
  set_param('ckt_gentoggle_0_odeIdeal/library/input.I','position',[462,660,512,680]);
  delete_line('ckt_gentoggle_0_odeIdeal/library/input.I','In1/1','Out1/1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/input.I/In1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/input.I/Out1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/input.I/X');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/input.I/_X');
  set_param('ckt_gentoggle_0_odeIdeal/library/input.I/X','position',[105,382,155,402]);
  add_block('simulink/Discontinuities/Quantizer','ckt_gentoggle_0_odeIdeal/library/input.I/smp_425');
  set_param('ckt_gentoggle_0_odeIdeal/library/input.I/smp_425','QuantizationInterval','1e-05');
  set_param('ckt_gentoggle_0_odeIdeal/library/input.I/smp_425','position',[757,812,807,832]);
  add_line('ckt_gentoggle_0_odeIdeal/library/input.I','X/1','smp_425/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/input.I','smp_425/1','_X/1');
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_0_odeIdeal/library/input.I/O');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/input.I/_O');
  add_line('ckt_gentoggle_0_odeIdeal/library/input.I','_O/1','O/1');
  set_param('ckt_gentoggle_0_odeIdeal/library/input.I/O','position',[434,360,484,380]);
  add_line('ckt_gentoggle_0_odeIdeal/library/input.I','_X/1','_O/1');
  %
  add_block('simulink/Ports & Subsystems/Subsystem','ckt_gentoggle_0_odeIdeal/library/igenebind');
  set_param('ckt_gentoggle_0_odeIdeal/library/igenebind','position',[473,255,523,275]);
  delete_line('ckt_gentoggle_0_odeIdeal/library/igenebind','In1/1','Out1/1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/igenebind/In1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/igenebind/Out1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/igenebind/TF');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/igenebind/_TF');
  set_param('ckt_gentoggle_0_odeIdeal/library/igenebind/TF','position',[594,270,644,290]);
  add_line('ckt_gentoggle_0_odeIdeal/library/igenebind','TF/1','_TF/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/igenebind/K');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/igenebind/_K');
  set_param('ckt_gentoggle_0_odeIdeal/library/igenebind/K','position',[720,982,770,1002]);
  add_line('ckt_gentoggle_0_odeIdeal/library/igenebind','K/1','_K/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/igenebind/Vmax');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/igenebind/_Vmax');
  set_param('ckt_gentoggle_0_odeIdeal/library/igenebind/Vmax','position',[65,502,115,522]);
  add_line('ckt_gentoggle_0_odeIdeal/library/igenebind','Vmax/1','_Vmax/1');
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_0_odeIdeal/library/igenebind/GE');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/igenebind/_GE');
  add_line('ckt_gentoggle_0_odeIdeal/library/igenebind','_GE/1','GE/1');
  set_param('ckt_gentoggle_0_odeIdeal/library/igenebind/GE','position',[981,708,1031,728]);
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/library/igenebind/const_451');
  set_param('ckt_gentoggle_0_odeIdeal/library/igenebind/const_451','Value','1.');
  set_param('ckt_gentoggle_0_odeIdeal/library/igenebind/const_451','position',[391,552,441,572]);
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/library/igenebind/const_453');
  set_param('ckt_gentoggle_0_odeIdeal/library/igenebind/const_453','Value','1.');
  set_param('ckt_gentoggle_0_odeIdeal/library/igenebind/const_453','position',[625,909,675,929]);
  add_block('simulink/Math Operations/Product','ckt_gentoggle_0_odeIdeal/library/igenebind/mul_455');
  set_param('ckt_gentoggle_0_odeIdeal/library/igenebind/mul_455','Inputs','**');
  set_param('ckt_gentoggle_0_odeIdeal/library/igenebind/mul_455','position',[272,379,322,399]);
  add_line('ckt_gentoggle_0_odeIdeal/library/igenebind','_K/1','mul_455/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/igenebind','_TF/1','mul_455/2');
  add_block('simulink/Math Operations/Sum','ckt_gentoggle_0_odeIdeal/library/igenebind/sub_458');
  set_param('ckt_gentoggle_0_odeIdeal/library/igenebind/sub_458','Inputs','++');
  set_param('ckt_gentoggle_0_odeIdeal/library/igenebind/sub_458','position',[9,329,59,349]);
  add_line('ckt_gentoggle_0_odeIdeal/library/igenebind','const_453/1','sub_458/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/igenebind','mul_455/1','sub_458/2');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_0_odeIdeal/library/igenebind/div_461');
  set_param('ckt_gentoggle_0_odeIdeal/library/igenebind/div_461','Inputs','*/');
  set_param('ckt_gentoggle_0_odeIdeal/library/igenebind/div_461','position',[613,179,663,199]);
  add_line('ckt_gentoggle_0_odeIdeal/library/igenebind','const_451/1','div_461/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/igenebind','sub_458/1','div_461/2');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_0_odeIdeal/library/igenebind/mul_464');
  set_param('ckt_gentoggle_0_odeIdeal/library/igenebind/mul_464','Inputs','**');
  set_param('ckt_gentoggle_0_odeIdeal/library/igenebind/mul_464','position',[287,575,337,595]);
  add_line('ckt_gentoggle_0_odeIdeal/library/igenebind','_Vmax/1','mul_464/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/igenebind','div_461/1','mul_464/2');
  add_line('ckt_gentoggle_0_odeIdeal/library/igenebind','mul_464/1','_GE/1');
end
%
%
%
