%toplevel script
function main()
  preamble();
  build_comp_library();
  build_circuit();
end
%
%
%circuit build script
function build_circuit()
  add_block('simulink/Ports & Subsystems/Subsystem','ckt_gentoggle_0_odeIdeal/circuit');
  set_param('ckt_gentoggle_0_odeIdeal/circuit','position',[930,232,980,252]);
  delete_line('ckt_gentoggle_0_odeIdeal/circuit','In1/1','Out1/1');
  delete_block('ckt_gentoggle_0_odeIdeal/circuit/In1');
  delete_block('ckt_gentoggle_0_odeIdeal/circuit/Out1');
  add_block('ckt_gentoggle_0_odeIdeal/library/vgain','ckt_gentoggle_0_odeIdeal/circuit/vgain[12]');
  add_block('ckt_gentoggle_0_odeIdeal/library/switch','ckt_gentoggle_0_odeIdeal/circuit/switch[14]');
  add_block('ckt_gentoggle_0_odeIdeal/library/switch','ckt_gentoggle_0_odeIdeal/circuit/switch[1]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.I','ckt_gentoggle_0_odeIdeal/circuit/input.I[2]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.I','ckt_gentoggle_0_odeIdeal/circuit/input.I[20]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.I','ckt_gentoggle_0_odeIdeal/circuit/input.I[8]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.I','ckt_gentoggle_0_odeIdeal/circuit/input.I[7]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.I','ckt_gentoggle_0_odeIdeal/circuit/input.I[13]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.I','ckt_gentoggle_0_odeIdeal/circuit/input.I[12]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.I','ckt_gentoggle_0_odeIdeal/circuit/input.I[9]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.I','ckt_gentoggle_0_odeIdeal/circuit/input.I[0]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.I','ckt_gentoggle_0_odeIdeal/circuit/input.I[11]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.I','ckt_gentoggle_0_odeIdeal/circuit/input.I[26]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.I','ckt_gentoggle_0_odeIdeal/circuit/input.I[10]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.I','ckt_gentoggle_0_odeIdeal/circuit/input.I[27]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.I','ckt_gentoggle_0_odeIdeal/circuit/input.I[15]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.I','ckt_gentoggle_0_odeIdeal/circuit/input.I[6]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.I','ckt_gentoggle_0_odeIdeal/circuit/input.I[14]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.I','ckt_gentoggle_0_odeIdeal/circuit/input.I[21]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.I','ckt_gentoggle_0_odeIdeal/circuit/input.I[16]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.I','ckt_gentoggle_0_odeIdeal/circuit/input.I[3]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.I','ckt_gentoggle_0_odeIdeal/circuit/input.I[4]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.I','ckt_gentoggle_0_odeIdeal/circuit/input.I[5]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.I','ckt_gentoggle_0_odeIdeal/circuit/input.I[28]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.I','ckt_gentoggle_0_odeIdeal/circuit/input.I[1]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.I','ckt_gentoggle_0_odeIdeal/circuit/input.I[17]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.I','ckt_gentoggle_0_odeIdeal/circuit/input.I[18]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.I','ckt_gentoggle_0_odeIdeal/circuit/input.I[19]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.I','ckt_gentoggle_0_odeIdeal/circuit/input.I[22]');
  add_block('ckt_gentoggle_0_odeIdeal/library/output.V','ckt_gentoggle_0_odeIdeal/circuit/output.V[0]');
  add_block('ckt_gentoggle_0_odeIdeal/library/output.V','ckt_gentoggle_0_odeIdeal/circuit/output.V[1]');
  add_block('ckt_gentoggle_0_odeIdeal/library/vadd','ckt_gentoggle_0_odeIdeal/circuit/vadd[16]');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_468');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_468','Value','1.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_468','position',[516,90,566,110]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_468/1','vadd[16]/6');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_470');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_470','Value','1.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_470','position',[596,49,646,69]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_470/1','vadd[16]/7');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_472');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_472','Value','1.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_472','position',[580,503,630,523]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_472/1','vadd[16]/8');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/vadd[16]/int_375','InitialCondition','0.');
  add_block('ckt_gentoggle_0_odeIdeal/library/vadd','ckt_gentoggle_0_odeIdeal/circuit/vadd[5]');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_474');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_474','Value','1.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_474','position',[972,454,1022,474]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_474/1','vadd[5]/6');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_476');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_476','Value','1.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_476','position',[196,543,246,563]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_476/1','vadd[5]/7');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_478');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_478','Value','1.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_478','position',[898,437,948,457]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_478/1','vadd[5]/8');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/vadd[5]/int_375','InitialCondition','0.');
  add_block('ckt_gentoggle_0_odeIdeal/library/vtoi','ckt_gentoggle_0_odeIdeal/circuit/vtoi[12]');
  add_block('ckt_gentoggle_0_odeIdeal/library/vtoi','ckt_gentoggle_0_odeIdeal/circuit/vtoi[0]');
  add_block('ckt_gentoggle_0_odeIdeal/library/vtoi','ckt_gentoggle_0_odeIdeal/circuit/vtoi[11]');
  add_block('ckt_gentoggle_0_odeIdeal/library/igenebind','ckt_gentoggle_0_odeIdeal/circuit/igenebind[8]');
  add_block('ckt_gentoggle_0_odeIdeal/library/igenebind','ckt_gentoggle_0_odeIdeal/circuit/igenebind[6]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.V','ckt_gentoggle_0_odeIdeal/circuit/input.V[2]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.V','ckt_gentoggle_0_odeIdeal/circuit/input.V[8]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.V','ckt_gentoggle_0_odeIdeal/circuit/input.V[7]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.V','ckt_gentoggle_0_odeIdeal/circuit/input.V[13]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.V','ckt_gentoggle_0_odeIdeal/circuit/input.V[12]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.V','ckt_gentoggle_0_odeIdeal/circuit/input.V[9]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.V','ckt_gentoggle_0_odeIdeal/circuit/input.V[0]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.V','ckt_gentoggle_0_odeIdeal/circuit/input.V[11]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.V','ckt_gentoggle_0_odeIdeal/circuit/input.V[10]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.V','ckt_gentoggle_0_odeIdeal/circuit/input.V[15]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.V','ckt_gentoggle_0_odeIdeal/circuit/input.V[6]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.V','ckt_gentoggle_0_odeIdeal/circuit/input.V[14]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.V','ckt_gentoggle_0_odeIdeal/circuit/input.V[16]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.V','ckt_gentoggle_0_odeIdeal/circuit/input.V[3]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.V','ckt_gentoggle_0_odeIdeal/circuit/input.V[4]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.V','ckt_gentoggle_0_odeIdeal/circuit/input.V[5]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.V','ckt_gentoggle_0_odeIdeal/circuit/input.V[1]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.V','ckt_gentoggle_0_odeIdeal/circuit/input.V[18]');
  add_block('ckt_gentoggle_0_odeIdeal/library/itov','ckt_gentoggle_0_odeIdeal/circuit/itov[13]');
  add_block('ckt_gentoggle_0_odeIdeal/library/itov','ckt_gentoggle_0_odeIdeal/circuit/itov[15]');
  add_block('ckt_gentoggle_0_odeIdeal/library/itov','ckt_gentoggle_0_odeIdeal/circuit/itov[4]');
  add_block('ckt_gentoggle_0_odeIdeal/library/iadd','ckt_gentoggle_0_odeIdeal/circuit/iadd[2]');
  add_block('ckt_gentoggle_0_odeIdeal/library/iadd','ckt_gentoggle_0_odeIdeal/circuit/iadd[7]');
  add_block('ckt_gentoggle_0_odeIdeal/library/iadd','ckt_gentoggle_0_odeIdeal/circuit/iadd[9]');
  add_block('ckt_gentoggle_0_odeIdeal/library/iadd','ckt_gentoggle_0_odeIdeal/circuit/iadd[11]');
  add_block('ckt_gentoggle_0_odeIdeal/library/iadd','ckt_gentoggle_0_odeIdeal/circuit/iadd[10]');
  add_block('ckt_gentoggle_0_odeIdeal/library/iadd','ckt_gentoggle_0_odeIdeal/circuit/iadd[3]');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','switch[1]/1','iadd[11]/3');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.I[6]/1','iadd[7]/3');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','itov[13]/1','vgain[12]/3');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','vtoi[12]/1','iadd[7]/4');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.I[0]/1','iadd[2]/1');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.V[9]/1','vadd[5]/1');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.I[22]/1','switch[14]/3');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.V[15]/1','vgain[12]/2');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','igenebind[8]/1','itov[15]/2');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.I[26]/1','iadd[11]/2');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.I[18]/1','igenebind[6]/1');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.I[9]/1','iadd[9]/3');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.V[13]/1','vtoi[0]/1');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.I[3]/1','iadd[3]/1');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.I[16]/1','igenebind[6]/3');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.I[4]/1','iadd[3]/3');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.I[5]/1','iadd[3]/2');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.V[14]/1','vtoi[11]/1');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','vtoi[0]/1','iadd[3]/4');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.V[11]/1','vadd[5]/2');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.I[14]/1','itov[15]/1');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','itov[15]/1','vadd[16]/5');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.I[2]/1','iadd[2]/2');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.V[8]/1','vadd[16]/1');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.V[12]/1','switch[1]/1');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','vadd[5]/2','output.V[0]/1');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','vadd[5]/2','vtoi[12]/1');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.I[20]/1','igenebind[8]/2');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.V[3]/1','vadd[5]/4');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.V[2]/1','switch[14]/1');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.I[15]/1','switch[1]/2');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.I[10]/1','iadd[9]/2');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','igenebind[6]/1','itov[4]/1');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.I[12]/1','iadd[10]/3');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.I[1]/1','iadd[2]/3');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','vadd[16]/2','output.V[1]/1');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','vadd[16]/2','switch[1]/4');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','iadd[11]/1','igenebind[6]/2');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','iadd[7]/1','switch[14]/2');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','iadd[10]/1','iadd[9]/4');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.V[1]/1','vgain[12]/1');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.I[13]/1','iadd[10]/2');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.I[7]/1','iadd[7]/2');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','iadd[3]/1','iadd[2]/4');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.V[7]/1','itov[4]/2');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.I[17]/1','igenebind[8]/3');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','iadd[2]/1','switch[1]/3');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.I[8]/1','iadd[9]/1');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','iadd[9]/1','igenebind[8]/1');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','vtoi[11]/1','iadd[10]/4');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','vgain[12]/1','vtoi[11]/2');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','switch[14]/1','itov[13]/1');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.I[21]/1','switch[14]/4');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.I[27]/1','iadd[11]/4');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.V[0]/1','vtoi[0]/2');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.V[10]/1','vadd[16]/2');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.V[18]/1','vtoi[12]/2');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.V[16]/1','itov[13]/2');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','itov[4]/1','vadd[5]/5');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.V[4]/1','vadd[5]/3');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.I[19]/1','iadd[7]/1');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.V[5]/1','vadd[16]/3');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.V[6]/1','vadd[16]/4');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.I[28]/1','iadd[11]/1');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.I[11]/1','iadd[10]/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/circuit/input.V[0]_in');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/circuit/_input.V[0]_in');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/input.V[0]_in','position',[684,445,734,465]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.V[0]_in/1','_input.V[0]_in/1');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','_input.V[0]_in/1','input.V[0]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_485');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_485','Value','2.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_485','position',[304,653,354,673]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_485/1','input.V[1]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_487');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_487','Value','1250.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_487','position',[851,885,901,905]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_487/1','input.V[2]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_489');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_489','Value','0.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_489','position',[469,144,519,164]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_489/1','input.I[26]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_491');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_491','Value','0.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_491','position',[159,343,209,363]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_491/1','input.I[27]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_493');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_493','Value','0.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_493','position',[684,816,734,836]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_493/1','input.I[28]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_495');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_495','Value','0.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_495','position',[650,335,700,355]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_495/1','input.I[0]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_497');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_497','Value','0.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_497','position',[884,871,934,891]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_497/1','input.I[1]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_499');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_499','Value','0.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_499','position',[658,156,708,176]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_499/1','input.I[2]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_501');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_501','Value','0.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_501','position',[234,667,284,687]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_501/1','input.I[3]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_503');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_503','Value','0.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_503','position',[998,640,1048,660]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_503/1','input.I[4]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_505');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_505','Value','0.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_505','position',[48,482,98,502]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_505/1','input.I[5]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_507');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_507','Value','0.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_507','position',[813,36,863,56]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_507/1','input.V[3]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_509');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_509','Value','0.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_509','position',[5,677,55,697]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_509/1','input.V[4]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_511');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_511','Value','0.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_511','position',[658,449,708,469]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_511/1','input.I[6]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_513');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_513','Value','0.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_513','position',[127,507,177,527]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_513/1','input.I[7]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_515');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_515','Value','0.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_515','position',[86,139,136,159]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_515/1','input.I[8]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_517');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_517','Value','0.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_517','position',[3,611,53,631]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_517/1','input.I[9]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_519');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_519','Value','0.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_519','position',[284,838,334,858]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_519/1','input.I[10]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_521');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_521','Value','0.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_521','position',[434,392,484,412]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_521/1','input.I[11]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_523');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_523','Value','0.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_523','position',[255,568,305,588]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_523/1','input.I[12]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_525');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_525','Value','0.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_525','position',[587,793,637,813]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_525/1','input.I[13]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_527');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_527','Value','0.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_527','position',[105,146,155,166]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_527/1','input.V[5]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_529');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_529','Value','0.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_529','position',[843,638,893,658]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_529/1','input.V[6]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_531');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_531','Value','400.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_531','position',[121,234,171,254]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_531/1','input.I[14]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_533');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_533','Value','400.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_533','position',[170,400,220,420]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_533/1','input.V[7]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_535');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_535','Value','0.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_535','position',[927,187,977,207]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_535/1','input.V[8]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_537');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_537','Value','0.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_537','position',[469,143,519,163]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_537/1','input.V[9]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_539');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_539','Value','337.632520764');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_539','position',[495,493,545,513]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_539/1','input.I[15]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_541');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_541','Value','0.156');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_541','position',[317,470,367,490]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_541/1','input.I[16]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_543');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_543','Value','4.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_543','position',[644,710,694,730]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_543/1','input.V[10]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_545');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_545','Value','4.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_545','position',[477,612,527,632]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_545/1','input.V[11]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_547');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_547','Value','1000.75');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_547','position',[427,238,477,258]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_547/1','input.V[12]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_549');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_549','Value','1.5625');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_549','position',[321,858,371,878]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_549/1','input.I[17]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_551');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_551','Value','1.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_551','position',[425,939,475,959]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_551/1','input.V[18]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_553');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_553','Value','1.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_553','position',[875,478,925,498]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_553/1','input.V[13]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_555');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_555','Value','1.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_555','position',[466,932,516,952]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_555/1','input.I[18]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_557');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_557','Value','1.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_557','position',[954,14,1004,34]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_557/1','input.I[19]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_559');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_559','Value','1.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_559','position',[133,270,183,290]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_559/1','input.I[20]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_561');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_561','Value','1.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_561','position',[270,63,320,83]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_561/1','input.V[14]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_563');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_563','Value','1.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_563','position',[72,927,122,947]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_563/1','input.V[15]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_565');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_565','Value','1.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_565','position',[641,331,691,351]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_565/1','input.V[16]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_567');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_567','Value','1.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_567','position',[669,593,719,613]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_567/1','input.I[21]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_569');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_569','Value','1.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_569','position',[639,780,689,800]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_569/1','input.I[22]/1');
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_0_odeIdeal/circuit/output.V[0]_out');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/circuit/_output.V[0]_out');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','_output.V[0]_out/1','output.V[0]_out/1');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/output.V[0]_out','position',[68,567,118,587]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','output.V[0]/1','_output.V[0]_out/1');
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_0_odeIdeal/circuit/output.V[1]_out');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/circuit/_output.V[1]_out');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','_output.V[1]_out/1','output.V[1]_out/1');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/output.V[1]_out','position',[534,503,584,523]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','output.V[1]/1','_output.V[1]_out/1');
end
%
%
%preamble function
function preamble()
  %define model name
  model_name='ckt_gentoggle_0_odeIdeal';
  %create and open the model
  open_system(new_system(model_name));
  %set solver method
  set_param(model_name,'Solver','ode3');
end
%
%
%library assembly function
function build_comp_library()
  add_block('simulink/Ports & Subsystems/Subsystem','ckt_gentoggle_0_odeIdeal/library');
  set_param('ckt_gentoggle_0_odeIdeal/library','position',[454,849,504,869]);
  delete_line('ckt_gentoggle_0_odeIdeal/library','In1/1','Out1/1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/In1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/Out1');
  %
  %
  %
  add_block('simulink/Ports & Subsystems/Subsystem','ckt_gentoggle_0_odeIdeal/library/mm');
  set_param('ckt_gentoggle_0_odeIdeal/library/mm','position',[552,831,602,851]);
  delete_line('ckt_gentoggle_0_odeIdeal/library/mm','In1/1','Out1/1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/mm/In1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/mm/Out1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/mm/kr');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/mm/_kr');
  set_param('ckt_gentoggle_0_odeIdeal/library/mm/kr','position',[474,951,524,971]);
  add_line('ckt_gentoggle_0_odeIdeal/library/mm','kr/1','_kr/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/mm/XY0');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/mm/_XY0');
  set_param('ckt_gentoggle_0_odeIdeal/library/mm/XY0','position',[675,866,725,886]);
  add_line('ckt_gentoggle_0_odeIdeal/library/mm','XY0/1','_XY0/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/mm/Ytot');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/mm/_Ytot');
  set_param('ckt_gentoggle_0_odeIdeal/library/mm/Ytot','position',[703,634,753,654]);
  add_line('ckt_gentoggle_0_odeIdeal/library/mm','Ytot/1','_Ytot/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/mm/kf');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/mm/_kf');
  set_param('ckt_gentoggle_0_odeIdeal/library/mm/kf','position',[950,114,1000,134]);
  add_line('ckt_gentoggle_0_odeIdeal/library/mm','kf/1','_kf/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/mm/Xtot');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/mm/_Xtot');
  set_param('ckt_gentoggle_0_odeIdeal/library/mm/Xtot','position',[954,965,1004,985]);
  add_line('ckt_gentoggle_0_odeIdeal/library/mm','Xtot/1','_Xtot/1');
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_0_odeIdeal/library/mm/X');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/mm/_X');
  add_line('ckt_gentoggle_0_odeIdeal/library/mm','_X/1','X/1');
  set_param('ckt_gentoggle_0_odeIdeal/library/mm/X','position',[211,539,261,559]);
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_0_odeIdeal/library/mm/XY');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/mm/_XY');
  add_line('ckt_gentoggle_0_odeIdeal/library/mm','_XY/1','XY/1');
  set_param('ckt_gentoggle_0_odeIdeal/library/mm/XY','position',[341,827,391,847]);
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_0_odeIdeal/library/mm/Y');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/mm/_Y');
  add_line('ckt_gentoggle_0_odeIdeal/library/mm','_Y/1','Y/1');
  set_param('ckt_gentoggle_0_odeIdeal/library/mm/Y','position',[568,605,618,625]);
  add_block('simulink/Math Operations/Sum','ckt_gentoggle_0_odeIdeal/library/mm/sum_39');
  set_param('ckt_gentoggle_0_odeIdeal/library/mm/sum_39','Inputs','+-');
  set_param('ckt_gentoggle_0_odeIdeal/library/mm/sum_39','position',[722,591,772,611]);
  add_line('ckt_gentoggle_0_odeIdeal/library/mm','_Xtot/1','sum_39/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/mm','_XY/1','sum_39/2');
  add_line('ckt_gentoggle_0_odeIdeal/library/mm','sum_39/1','_X/1');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_0_odeIdeal/library/mm/mul_42');
  set_param('ckt_gentoggle_0_odeIdeal/library/mm/mul_42','Inputs','***');
  set_param('ckt_gentoggle_0_odeIdeal/library/mm/mul_42','position',[424,219,474,239]);
  add_line('ckt_gentoggle_0_odeIdeal/library/mm','_kf/1','mul_42/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/mm','_X/1','mul_42/2');
  add_line('ckt_gentoggle_0_odeIdeal/library/mm','_Y/1','mul_42/3');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_0_odeIdeal/library/mm/mul_46');
  set_param('ckt_gentoggle_0_odeIdeal/library/mm/mul_46','Inputs','**');
  set_param('ckt_gentoggle_0_odeIdeal/library/mm/mul_46','position',[982,561,1032,581]);
  add_line('ckt_gentoggle_0_odeIdeal/library/mm','_kr/1','mul_46/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/mm','_XY/1','mul_46/2');
  add_block('simulink/Math Operations/Sum','ckt_gentoggle_0_odeIdeal/library/mm/sum_49');
  set_param('ckt_gentoggle_0_odeIdeal/library/mm/sum_49','Inputs','+-');
  set_param('ckt_gentoggle_0_odeIdeal/library/mm/sum_49','position',[599,822,649,842]);
  add_line('ckt_gentoggle_0_odeIdeal/library/mm','mul_42/1','sum_49/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/mm','mul_46/1','sum_49/2');
  add_block('simulink/Continuous/Integrator','ckt_gentoggle_0_odeIdeal/library/mm/int_52');
  set_param('ckt_gentoggle_0_odeIdeal/library/mm/int_52','position',[795,604,845,624]);
  add_line('ckt_gentoggle_0_odeIdeal/library/mm','sum_49/1','int_52/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/mm','int_52/1','_XY/1');
  add_block('simulink/Math Operations/Sum','ckt_gentoggle_0_odeIdeal/library/mm/sum_54');
  set_param('ckt_gentoggle_0_odeIdeal/library/mm/sum_54','Inputs','+-');
  set_param('ckt_gentoggle_0_odeIdeal/library/mm/sum_54','position',[946,260,996,280]);
  add_line('ckt_gentoggle_0_odeIdeal/library/mm','_Ytot/1','sum_54/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/mm','_XY/1','sum_54/2');
  add_line('ckt_gentoggle_0_odeIdeal/library/mm','sum_54/1','_Y/1');
  %
  add_block('simulink/Ports & Subsystems/Subsystem','ckt_gentoggle_0_odeIdeal/library/vgain');
  set_param('ckt_gentoggle_0_odeIdeal/library/vgain','position',[785,888,835,908]);
  delete_line('ckt_gentoggle_0_odeIdeal/library/vgain','In1/1','Out1/1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/vgain/In1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/vgain/Out1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/vgain/X');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/vgain/_X');
  set_param('ckt_gentoggle_0_odeIdeal/library/vgain/X','position',[235,708,285,728]);
  add_line('ckt_gentoggle_0_odeIdeal/library/vgain','X/1','_X/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/vgain/Y');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/vgain/_Y');
  set_param('ckt_gentoggle_0_odeIdeal/library/vgain/Y','position',[8,602,58,622]);
  add_line('ckt_gentoggle_0_odeIdeal/library/vgain','Y/1','_Y/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/vgain/Z');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/vgain/_Z');
  set_param('ckt_gentoggle_0_odeIdeal/library/vgain/Z','position',[112,521,162,541]);
  add_line('ckt_gentoggle_0_odeIdeal/library/vgain','Z/1','_Z/1');
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_0_odeIdeal/library/vgain/P');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/vgain/_P');
  add_line('ckt_gentoggle_0_odeIdeal/library/vgain','_P/1','P/1');
  set_param('ckt_gentoggle_0_odeIdeal/library/vgain/P','position',[174,483,224,503]);
  add_block('simulink/Math Operations/Product','ckt_gentoggle_0_odeIdeal/library/vgain/div_77');
  set_param('ckt_gentoggle_0_odeIdeal/library/vgain/div_77','Inputs','*/');
  set_param('ckt_gentoggle_0_odeIdeal/library/vgain/div_77','position',[24,562,74,582]);
  add_line('ckt_gentoggle_0_odeIdeal/library/vgain','_X/1','div_77/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/vgain','_Y/1','div_77/2');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/library/vgain/const_80');
  set_param('ckt_gentoggle_0_odeIdeal/library/vgain/const_80','Value','0.5');
  set_param('ckt_gentoggle_0_odeIdeal/library/vgain/const_80','position',[929,631,979,651]);
  add_block('simulink/Math Operations/Product','ckt_gentoggle_0_odeIdeal/library/vgain/mul_82');
  set_param('ckt_gentoggle_0_odeIdeal/library/vgain/mul_82','Inputs','***');
  set_param('ckt_gentoggle_0_odeIdeal/library/vgain/mul_82','position',[682,350,732,370]);
  add_line('ckt_gentoggle_0_odeIdeal/library/vgain','div_77/1','mul_82/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/vgain','_Z/1','mul_82/2');
  add_line('ckt_gentoggle_0_odeIdeal/library/vgain','const_80/1','mul_82/3');
  add_line('ckt_gentoggle_0_odeIdeal/library/vgain','mul_82/1','_P/1');
  %
  add_block('simulink/Ports & Subsystems/Subsystem','ckt_gentoggle_0_odeIdeal/library/switch');
  set_param('ckt_gentoggle_0_odeIdeal/library/switch','position',[89,725,139,745]);
  delete_line('ckt_gentoggle_0_odeIdeal/library/switch','In1/1','Out1/1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/switch/In1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/switch/Out1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/switch/n');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/switch/_n');
  set_param('ckt_gentoggle_0_odeIdeal/library/switch/n','position',[408,378,458,398]);
  add_line('ckt_gentoggle_0_odeIdeal/library/switch','n/1','_n/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/switch/SUB');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/switch/_SUB');
  set_param('ckt_gentoggle_0_odeIdeal/library/switch/SUB','position',[815,374,865,394]);
  add_line('ckt_gentoggle_0_odeIdeal/library/switch','SUB/1','_SUB/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/switch/Kmod');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/switch/_Kmod');
  set_param('ckt_gentoggle_0_odeIdeal/library/switch/Kmod','position',[402,946,452,966]);
  add_line('ckt_gentoggle_0_odeIdeal/library/switch','Kmod/1','_Kmod/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/switch/Vmax');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/switch/_Vmax');
  set_param('ckt_gentoggle_0_odeIdeal/library/switch/Vmax','position',[646,432,696,452]);
  add_line('ckt_gentoggle_0_odeIdeal/library/switch','Vmax/1','_Vmax/1');
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_0_odeIdeal/library/switch/PROD');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/switch/_PROD');
  add_line('ckt_gentoggle_0_odeIdeal/library/switch','_PROD/1','PROD/1');
  set_param('ckt_gentoggle_0_odeIdeal/library/switch/PROD','position',[719,170,769,190]);
  add_block('simulink/Math Operations/Product','ckt_gentoggle_0_odeIdeal/library/switch/div_111');
  set_param('ckt_gentoggle_0_odeIdeal/library/switch/div_111','Inputs','*/');
  set_param('ckt_gentoggle_0_odeIdeal/library/switch/div_111','position',[291,260,341,280]);
  add_line('ckt_gentoggle_0_odeIdeal/library/switch','_SUB/1','div_111/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/switch','_Kmod/1','div_111/2');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/library/switch/const_114');
  set_param('ckt_gentoggle_0_odeIdeal/library/switch/const_114','Value','1.');
  set_param('ckt_gentoggle_0_odeIdeal/library/switch/const_114','position',[694,811,744,831]);
  add_block('simulink/Math Operations/Sum','ckt_gentoggle_0_odeIdeal/library/switch/sub_116');
  set_param('ckt_gentoggle_0_odeIdeal/library/switch/sub_116','Inputs','++');
  set_param('ckt_gentoggle_0_odeIdeal/library/switch/sub_116','position',[988,675,1038,695]);
  add_line('ckt_gentoggle_0_odeIdeal/library/switch','div_111/1','sub_116/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/switch','const_114/1','sub_116/2');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/library/switch/const_119');
  set_param('ckt_gentoggle_0_odeIdeal/library/switch/const_119','Value','500.');
  set_param('ckt_gentoggle_0_odeIdeal/library/switch/const_119','position',[565,367,615,387]);
  add_block('simulink/Math Operations/Product','ckt_gentoggle_0_odeIdeal/library/switch/div_121');
  set_param('ckt_gentoggle_0_odeIdeal/library/switch/div_121','Inputs','*/');
  set_param('ckt_gentoggle_0_odeIdeal/library/switch/div_121','position',[46,969,96,989]);
  add_line('ckt_gentoggle_0_odeIdeal/library/switch','_n/1','div_121/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/switch','const_119/1','div_121/2');
  add_block('simulink/Math Operations/Math Function','ckt_gentoggle_0_odeIdeal/library/switch/pow_124');
  set_param('ckt_gentoggle_0_odeIdeal/library/switch/pow_124','Function','pow');
  set_param('ckt_gentoggle_0_odeIdeal/library/switch/pow_124','position',[514,322,564,342]);
  add_line('ckt_gentoggle_0_odeIdeal/library/switch','div_121/1','pow_124/2');
  add_line('ckt_gentoggle_0_odeIdeal/library/switch','sub_116/1','pow_124/1');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_0_odeIdeal/library/switch/div_127');
  set_param('ckt_gentoggle_0_odeIdeal/library/switch/div_127','Inputs','*/');
  set_param('ckt_gentoggle_0_odeIdeal/library/switch/div_127','position',[321,671,371,691]);
  add_line('ckt_gentoggle_0_odeIdeal/library/switch','_Vmax/1','div_127/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/switch','pow_124/1','div_127/2');
  add_line('ckt_gentoggle_0_odeIdeal/library/switch','div_127/1','_PROD/1');
  %
  add_block('simulink/Ports & Subsystems/Subsystem','ckt_gentoggle_0_odeIdeal/library/ihill');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill','position',[208,598,258,618]);
  delete_line('ckt_gentoggle_0_odeIdeal/library/ihill','In1/1','Out1/1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/ihill/In1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/ihill/Out1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/ihill/n');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/ihill/_n');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/n','position',[741,650,791,670]);
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','n/1','_n/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/ihill/S');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/ihill/_S');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/S','position',[287,117,337,137]);
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','S/1','_S/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/ihill/Km');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/ihill/_Km');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/Km','position',[200,54,250,74]);
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','Km/1','_Km/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/ihill/Vmax');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/ihill/_Vmax');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/Vmax','position',[172,6,222,26]);
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','Vmax/1','_Vmax/1');
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_0_odeIdeal/library/ihill/STIM');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/ihill/_STIM');
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','_STIM/1','STIM/1');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/STIM','position',[374,768,424,788]);
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_0_odeIdeal/library/ihill/REP');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/ihill/_REP');
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','_REP/1','REP/1');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/REP','position',[511,545,561,565]);
  add_block('simulink/Math Operations/Product','ckt_gentoggle_0_odeIdeal/library/ihill/div_159');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/div_159','Inputs','*/');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/div_159','position',[27,427,77,447]);
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','_S/1','div_159/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','_Km/1','div_159/2');
  add_block('simulink/Math Operations/Math Function','ckt_gentoggle_0_odeIdeal/library/ihill/pow_162');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/pow_162','Function','pow');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/pow_162','position',[30,959,80,979]);
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','_n/1','pow_162/2');
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','div_159/1','pow_162/1');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_0_odeIdeal/library/ihill/div_165');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/div_165','Inputs','*/');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/div_165','position',[332,314,382,334]);
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','_S/1','div_165/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','_Km/1','div_165/2');
  add_block('simulink/Math Operations/Math Function','ckt_gentoggle_0_odeIdeal/library/ihill/pow_168');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/pow_168','Function','pow');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/pow_168','position',[311,810,361,830]);
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','_n/1','pow_168/2');
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','div_165/1','pow_168/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/library/ihill/const_171');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/const_171','Value','1.');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/const_171','position',[931,358,981,378]);
  add_block('simulink/Math Operations/Sum','ckt_gentoggle_0_odeIdeal/library/ihill/sub_173');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/sub_173','Inputs','++');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/sub_173','position',[600,773,650,793]);
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','pow_168/1','sub_173/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','const_171/1','sub_173/2');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_0_odeIdeal/library/ihill/div_176');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/div_176','Inputs','*/');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/div_176','position',[835,981,885,1001]);
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','pow_162/1','div_176/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','sub_173/1','div_176/2');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_0_odeIdeal/library/ihill/mul_179');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/mul_179','Inputs','**');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/mul_179','position',[396,383,446,403]);
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','_Vmax/1','mul_179/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','div_176/1','mul_179/2');
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','mul_179/1','_STIM/1');
  add_block('simulink/Math Operations/Math Function','ckt_gentoggle_0_odeIdeal/library/ihill/pow_182');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/pow_182','Function','pow');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/pow_182','position',[142,414,192,434]);
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','_n/1','pow_182/2');
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','_Km/1','pow_182/1');
  add_block('simulink/Math Operations/Math Function','ckt_gentoggle_0_odeIdeal/library/ihill/pow_185');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/pow_185','Function','pow');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/pow_185','position',[208,622,258,642]);
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','_n/1','pow_185/2');
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','_S/1','pow_185/1');
  add_block('simulink/Math Operations/Math Function','ckt_gentoggle_0_odeIdeal/library/ihill/pow_188');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/pow_188','Function','pow');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/pow_188','position',[256,538,306,558]);
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','_n/1','pow_188/2');
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','_Km/1','pow_188/1');
  add_block('simulink/Math Operations/Sum','ckt_gentoggle_0_odeIdeal/library/ihill/sub_191');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/sub_191','Inputs','++');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/sub_191','position',[686,680,736,700]);
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','pow_185/1','sub_191/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','pow_188/1','sub_191/2');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_0_odeIdeal/library/ihill/div_194');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/div_194','Inputs','*/');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/div_194','position',[197,30,247,50]);
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','pow_182/1','div_194/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','sub_191/1','div_194/2');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_0_odeIdeal/library/ihill/mul_197');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/mul_197','Inputs','**');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/mul_197','position',[177,893,227,913]);
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','_Vmax/1','mul_197/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','div_194/1','mul_197/2');
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','mul_197/1','_REP/1');
  %
  add_block('simulink/Ports & Subsystems/Subsystem','ckt_gentoggle_0_odeIdeal/library/itov');
  set_param('ckt_gentoggle_0_odeIdeal/library/itov','position',[348,675,398,695]);
  delete_line('ckt_gentoggle_0_odeIdeal/library/itov','In1/1','Out1/1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/itov/In1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/itov/Out1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/itov/X');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/itov/_X');
  set_param('ckt_gentoggle_0_odeIdeal/library/itov/X','position',[100,372,150,392]);
  add_line('ckt_gentoggle_0_odeIdeal/library/itov','X/1','_X/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/itov/K');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/itov/_K');
  set_param('ckt_gentoggle_0_odeIdeal/library/itov/K','position',[497,7,547,27]);
  add_line('ckt_gentoggle_0_odeIdeal/library/itov','K/1','_K/1');
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_0_odeIdeal/library/itov/Y');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/itov/_Y');
  add_line('ckt_gentoggle_0_odeIdeal/library/itov','_Y/1','Y/1');
  set_param('ckt_gentoggle_0_odeIdeal/library/itov/Y','position',[468,585,518,605]);
  add_block('simulink/Math Operations/Product','ckt_gentoggle_0_odeIdeal/library/itov/mul_215');
  set_param('ckt_gentoggle_0_odeIdeal/library/itov/mul_215','Inputs','**');
  set_param('ckt_gentoggle_0_odeIdeal/library/itov/mul_215','position',[137,388,187,408]);
  add_line('ckt_gentoggle_0_odeIdeal/library/itov','_K/1','mul_215/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/itov','_X/1','mul_215/2');
  add_line('ckt_gentoggle_0_odeIdeal/library/itov','mul_215/1','_Y/1');
  %
  add_block('simulink/Ports & Subsystems/Subsystem','ckt_gentoggle_0_odeIdeal/library/output.I');
  set_param('ckt_gentoggle_0_odeIdeal/library/output.I','position',[45,805,95,825]);
  delete_line('ckt_gentoggle_0_odeIdeal/library/output.I','In1/1','Out1/1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/output.I/In1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/output.I/Out1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/output.I/X');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/output.I/_X');
  set_param('ckt_gentoggle_0_odeIdeal/library/output.I/X','position',[518,252,568,272]);
  add_line('ckt_gentoggle_0_odeIdeal/library/output.I','X/1','_X/1');
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_0_odeIdeal/library/output.I/O');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/output.I/_O');
  add_line('ckt_gentoggle_0_odeIdeal/library/output.I','_O/1','O/1');
  set_param('ckt_gentoggle_0_odeIdeal/library/output.I/O','position',[800,983,850,1003]);
  add_line('ckt_gentoggle_0_odeIdeal/library/output.I','_X/1','_O/1');
  %
  add_block('simulink/Ports & Subsystems/Subsystem','ckt_gentoggle_0_odeIdeal/library/output.V');
  set_param('ckt_gentoggle_0_odeIdeal/library/output.V','position',[653,564,703,584]);
  delete_line('ckt_gentoggle_0_odeIdeal/library/output.V','In1/1','Out1/1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/output.V/In1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/output.V/Out1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/output.V/X');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/output.V/_X');
  set_param('ckt_gentoggle_0_odeIdeal/library/output.V/X','position',[444,679,494,699]);
  add_line('ckt_gentoggle_0_odeIdeal/library/output.V','X/1','_X/1');
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_0_odeIdeal/library/output.V/O');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/output.V/_O');
  add_line('ckt_gentoggle_0_odeIdeal/library/output.V','_O/1','O/1');
  set_param('ckt_gentoggle_0_odeIdeal/library/output.V/O','position',[636,528,686,548]);
  add_line('ckt_gentoggle_0_odeIdeal/library/output.V','_X/1','_O/1');
  %
  add_block('simulink/Ports & Subsystems/Subsystem','ckt_gentoggle_0_odeIdeal/library/input.V');
  set_param('ckt_gentoggle_0_odeIdeal/library/input.V','position',[486,374,536,394]);
  delete_line('ckt_gentoggle_0_odeIdeal/library/input.V','In1/1','Out1/1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/input.V/In1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/input.V/Out1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/input.V/X');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/input.V/_X');
  set_param('ckt_gentoggle_0_odeIdeal/library/input.V/X','position',[224,639,274,659]);
  add_block('simulink/Discontinuities/Quantizer','ckt_gentoggle_0_odeIdeal/library/input.V/smp_244');
  set_param('ckt_gentoggle_0_odeIdeal/library/input.V/smp_244','QuantizationInterval','1e-05');
  set_param('ckt_gentoggle_0_odeIdeal/library/input.V/smp_244','position',[476,350,526,370]);
  add_line('ckt_gentoggle_0_odeIdeal/library/input.V','X/1','smp_244/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/input.V','smp_244/1','_X/1');
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_0_odeIdeal/library/input.V/O');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/input.V/_O');
  add_line('ckt_gentoggle_0_odeIdeal/library/input.V','_O/1','O/1');
  set_param('ckt_gentoggle_0_odeIdeal/library/input.V/O','position',[2,413,52,433]);
  add_line('ckt_gentoggle_0_odeIdeal/library/input.V','_X/1','_O/1');
  %
  add_block('simulink/Ports & Subsystems/Subsystem','ckt_gentoggle_0_odeIdeal/library/copy.V');
  set_param('ckt_gentoggle_0_odeIdeal/library/copy.V','position',[162,201,212,221]);
  delete_line('ckt_gentoggle_0_odeIdeal/library/copy.V','In1/1','Out1/1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/copy.V/In1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/copy.V/Out1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/copy.V/X');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/copy.V/_X');
  set_param('ckt_gentoggle_0_odeIdeal/library/copy.V/X','position',[166,672,216,692]);
  add_line('ckt_gentoggle_0_odeIdeal/library/copy.V','X/1','_X/1');
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_0_odeIdeal/library/copy.V/Y');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/copy.V/_Y');
  add_line('ckt_gentoggle_0_odeIdeal/library/copy.V','_Y/1','Y/1');
  set_param('ckt_gentoggle_0_odeIdeal/library/copy.V/Y','position',[361,409,411,429]);
  add_line('ckt_gentoggle_0_odeIdeal/library/copy.V','_X/1','_Y/1');
  %
  add_block('simulink/Ports & Subsystems/Subsystem','ckt_gentoggle_0_odeIdeal/library/vtoi');
  set_param('ckt_gentoggle_0_odeIdeal/library/vtoi','position',[355,417,405,437]);
  delete_line('ckt_gentoggle_0_odeIdeal/library/vtoi','In1/1','Out1/1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/vtoi/In1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/vtoi/Out1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/vtoi/X');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/vtoi/_X');
  set_param('ckt_gentoggle_0_odeIdeal/library/vtoi/X','position',[565,272,615,292]);
  add_line('ckt_gentoggle_0_odeIdeal/library/vtoi','X/1','_X/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/vtoi/K');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/vtoi/_K');
  set_param('ckt_gentoggle_0_odeIdeal/library/vtoi/K','position',[369,975,419,995]);
  add_line('ckt_gentoggle_0_odeIdeal/library/vtoi','K/1','_K/1');
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_0_odeIdeal/library/vtoi/Y');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/vtoi/_Y');
  add_line('ckt_gentoggle_0_odeIdeal/library/vtoi','_Y/1','Y/1');
  set_param('ckt_gentoggle_0_odeIdeal/library/vtoi/Y','position',[663,602,713,622]);
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/library/vtoi/const_275');
  set_param('ckt_gentoggle_0_odeIdeal/library/vtoi/const_275','Value','1.');
  set_param('ckt_gentoggle_0_odeIdeal/library/vtoi/const_275','position',[759,861,809,881]);
  add_block('simulink/Math Operations/Product','ckt_gentoggle_0_odeIdeal/library/vtoi/div_277');
  set_param('ckt_gentoggle_0_odeIdeal/library/vtoi/div_277','Inputs','*/');
  set_param('ckt_gentoggle_0_odeIdeal/library/vtoi/div_277','position',[256,9,306,29]);
  add_line('ckt_gentoggle_0_odeIdeal/library/vtoi','const_275/1','div_277/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/vtoi','_K/1','div_277/2');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_0_odeIdeal/library/vtoi/mul_280');
  set_param('ckt_gentoggle_0_odeIdeal/library/vtoi/mul_280','Inputs','**');
  set_param('ckt_gentoggle_0_odeIdeal/library/vtoi/mul_280','position',[534,905,584,925]);
  add_line('ckt_gentoggle_0_odeIdeal/library/vtoi','div_277/1','mul_280/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/vtoi','_X/1','mul_280/2');
  add_line('ckt_gentoggle_0_odeIdeal/library/vtoi','mul_280/1','_Y/1');
  %
  add_block('simulink/Ports & Subsystems/Subsystem','ckt_gentoggle_0_odeIdeal/library/vadd');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd','position',[557,290,607,310]);
  delete_line('ckt_gentoggle_0_odeIdeal/library/vadd','In1/1','Out1/1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/vadd/In1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/vadd/Out1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/vadd/OUT2_0');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/vadd/_OUT2_0');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/OUT2_0','position',[466,996,516,1016]);
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','OUT2_0/1','_OUT2_0/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/vadd/D');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/vadd/_D');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/D','position',[514,665,564,685]);
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','D/1','_D/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/vadd/C');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/vadd/_C');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/C','position',[725,582,775,602]);
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','C/1','_C/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/vadd/A');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/vadd/_A');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/A','position',[569,776,619,796]);
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','A/1','_A/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/vadd/B');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/vadd/_B');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/B','position',[773,499,823,519]);
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','B/1','_B/1');
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_0_odeIdeal/library/vadd/OUT');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/vadd/_OUT');
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','_OUT/1','OUT/1');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/OUT','position',[227,830,277,850]);
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_0_odeIdeal/library/vadd/OUT2');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/vadd/_OUT2');
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','_OUT2/1','OUT2/1');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/OUT2','position',[412,469,462,489]);
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/vadd/BSW');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/vadd/_BSW');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/BSW','position',[673,594,723,614]);
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','BSW/1','_BSW/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/vadd/CSW');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/vadd/_CSW');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/CSW','position',[436,43,486,63]);
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','CSW/1','_CSW/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/vadd/DSW');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/vadd/_DSW');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/DSW','position',[733,546,783,566]);
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','DSW/1','_DSW/1');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_0_odeIdeal/library/vadd/mul_332');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/mul_332','Inputs','**');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/mul_332','position',[260,19,310,39]);
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','_BSW/1','mul_332/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','_B/1','mul_332/2');
  add_block('simulink/Math Operations/Sum','ckt_gentoggle_0_odeIdeal/library/vadd/sub_335');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/sub_335','Inputs','++');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/sub_335','position',[377,256,427,276]);
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','_A/1','sub_335/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','mul_332/1','sub_335/2');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_0_odeIdeal/library/vadd/mul_338');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/mul_338','Inputs','**');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/mul_338','position',[387,545,437,565]);
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','_CSW/1','mul_338/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','_C/1','mul_338/2');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_0_odeIdeal/library/vadd/mul_341');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/mul_341','Inputs','**');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/mul_341','position',[698,741,748,761]);
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','_DSW/1','mul_341/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','_D/1','mul_341/2');
  add_block('simulink/Math Operations/Sum','ckt_gentoggle_0_odeIdeal/library/vadd/sum_344');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/sum_344','Inputs','+--');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/sum_344','position',[635,775,685,795]);
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','sub_335/1','sum_344/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','mul_338/1','sum_344/2');
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','mul_341/1','sum_344/3');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/library/vadd/const_348');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/const_348','Value','0.25');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/const_348','position',[601,201,651,221]);
  add_block('simulink/Math Operations/Product','ckt_gentoggle_0_odeIdeal/library/vadd/mul_350');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/mul_350','Inputs','**');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/mul_350','position',[874,488,924,508]);
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','sum_344/1','mul_350/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','const_348/1','mul_350/2');
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','mul_350/1','_OUT/1');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_0_odeIdeal/library/vadd/mul_353');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/mul_353','Inputs','**');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/mul_353','position',[448,841,498,861]);
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','_BSW/1','mul_353/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','_B/1','mul_353/2');
  add_block('simulink/Math Operations/Sum','ckt_gentoggle_0_odeIdeal/library/vadd/sub_356');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/sub_356','Inputs','++');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/sub_356','position',[387,871,437,891]);
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','_A/1','sub_356/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','mul_353/1','sub_356/2');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_0_odeIdeal/library/vadd/mul_359');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/mul_359','Inputs','**');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/mul_359','position',[104,103,154,123]);
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','_CSW/1','mul_359/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','_C/1','mul_359/2');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_0_odeIdeal/library/vadd/mul_362');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/mul_362','Inputs','***');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/mul_362','position',[299,284,349,304]);
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','_DSW/1','mul_362/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','_D/1','mul_362/2');
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','_OUT2/1','mul_362/3');
  add_block('simulink/Math Operations/Sum','ckt_gentoggle_0_odeIdeal/library/vadd/sum_366');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/sum_366','Inputs','+--');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/sum_366','position',[592,977,642,997]);
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','sub_356/1','sum_366/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','mul_359/1','sum_366/2');
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','mul_362/1','sum_366/3');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/library/vadd/const_370');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/const_370','Value','0.25');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/const_370','position',[198,967,248,987]);
  add_block('simulink/Math Operations/Product','ckt_gentoggle_0_odeIdeal/library/vadd/mul_372');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/mul_372','Inputs','**');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/mul_372','position',[904,494,954,514]);
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','sum_366/1','mul_372/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','const_370/1','mul_372/2');
  add_block('simulink/Continuous/Integrator','ckt_gentoggle_0_odeIdeal/library/vadd/int_375');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/int_375','position',[561,193,611,213]);
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','mul_372/1','int_375/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','int_375/1','_OUT2/1');
  %
  add_block('simulink/Ports & Subsystems/Subsystem','ckt_gentoggle_0_odeIdeal/library/copy.I');
  set_param('ckt_gentoggle_0_odeIdeal/library/copy.I','position',[85,6,135,26]);
  delete_line('ckt_gentoggle_0_odeIdeal/library/copy.I','In1/1','Out1/1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/copy.I/In1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/copy.I/Out1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/copy.I/X');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/copy.I/_X');
  set_param('ckt_gentoggle_0_odeIdeal/library/copy.I/X','position',[556,967,606,987]);
  add_line('ckt_gentoggle_0_odeIdeal/library/copy.I','X/1','_X/1');
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_0_odeIdeal/library/copy.I/Y');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/copy.I/_Y');
  add_line('ckt_gentoggle_0_odeIdeal/library/copy.I','_Y/1','Y/1');
  set_param('ckt_gentoggle_0_odeIdeal/library/copy.I/Y','position',[561,123,611,143]);
  add_line('ckt_gentoggle_0_odeIdeal/library/copy.I','_X/1','_Y/1');
  %
  add_block('simulink/Ports & Subsystems/Subsystem','ckt_gentoggle_0_odeIdeal/library/iadd');
  set_param('ckt_gentoggle_0_odeIdeal/library/iadd','position',[409,858,459,878]);
  delete_line('ckt_gentoggle_0_odeIdeal/library/iadd','In1/1','Out1/1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/iadd/In1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/iadd/Out1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/iadd/D');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/iadd/_D');
  set_param('ckt_gentoggle_0_odeIdeal/library/iadd/D','position',[556,222,606,242]);
  add_line('ckt_gentoggle_0_odeIdeal/library/iadd','D/1','_D/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/iadd/C');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/iadd/_C');
  set_param('ckt_gentoggle_0_odeIdeal/library/iadd/C','position',[137,545,187,565]);
  add_line('ckt_gentoggle_0_odeIdeal/library/iadd','C/1','_C/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/iadd/A');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/iadd/_A');
  set_param('ckt_gentoggle_0_odeIdeal/library/iadd/A','position',[151,182,201,202]);
  add_line('ckt_gentoggle_0_odeIdeal/library/iadd','A/1','_A/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/iadd/B');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/iadd/_B');
  set_param('ckt_gentoggle_0_odeIdeal/library/iadd/B','position',[657,842,707,862]);
  add_line('ckt_gentoggle_0_odeIdeal/library/iadd','B/1','_B/1');
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_0_odeIdeal/library/iadd/OUT');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/iadd/_OUT');
  add_line('ckt_gentoggle_0_odeIdeal/library/iadd','_OUT/1','OUT/1');
  set_param('ckt_gentoggle_0_odeIdeal/library/iadd/OUT','position',[526,833,576,853]);
  add_block('simulink/Math Operations/Sum','ckt_gentoggle_0_odeIdeal/library/iadd/sub_412');
  set_param('ckt_gentoggle_0_odeIdeal/library/iadd/sub_412','Inputs','++');
  set_param('ckt_gentoggle_0_odeIdeal/library/iadd/sub_412','position',[893,952,943,972]);
  add_line('ckt_gentoggle_0_odeIdeal/library/iadd','_A/1','sub_412/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/iadd','_B/1','sub_412/2');
  add_block('simulink/Math Operations/Sum','ckt_gentoggle_0_odeIdeal/library/iadd/sum_415');
  set_param('ckt_gentoggle_0_odeIdeal/library/iadd/sum_415','Inputs','+--');
  set_param('ckt_gentoggle_0_odeIdeal/library/iadd/sum_415','position',[325,753,375,773]);
  add_line('ckt_gentoggle_0_odeIdeal/library/iadd','sub_412/1','sum_415/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/iadd','_C/1','sum_415/2');
  add_line('ckt_gentoggle_0_odeIdeal/library/iadd','_D/1','sum_415/3');
  add_line('ckt_gentoggle_0_odeIdeal/library/iadd','sum_415/1','_OUT/1');
  %
  add_block('simulink/Ports & Subsystems/Subsystem','ckt_gentoggle_0_odeIdeal/library/input.I');
  set_param('ckt_gentoggle_0_odeIdeal/library/input.I','position',[524,735,574,755]);
  delete_line('ckt_gentoggle_0_odeIdeal/library/input.I','In1/1','Out1/1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/input.I/In1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/input.I/Out1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/input.I/X');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/input.I/_X');
  set_param('ckt_gentoggle_0_odeIdeal/library/input.I/X','position',[969,331,1019,351]);
  add_block('simulink/Discontinuities/Quantizer','ckt_gentoggle_0_odeIdeal/library/input.I/smp_425');
  set_param('ckt_gentoggle_0_odeIdeal/library/input.I/smp_425','QuantizationInterval','1e-05');
  set_param('ckt_gentoggle_0_odeIdeal/library/input.I/smp_425','position',[749,629,799,649]);
  add_line('ckt_gentoggle_0_odeIdeal/library/input.I','X/1','smp_425/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/input.I','smp_425/1','_X/1');
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_0_odeIdeal/library/input.I/O');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/input.I/_O');
  add_line('ckt_gentoggle_0_odeIdeal/library/input.I','_O/1','O/1');
  set_param('ckt_gentoggle_0_odeIdeal/library/input.I/O','position',[738,269,788,289]);
  add_line('ckt_gentoggle_0_odeIdeal/library/input.I','_X/1','_O/1');
  %
  add_block('simulink/Ports & Subsystems/Subsystem','ckt_gentoggle_0_odeIdeal/library/igenebind');
  set_param('ckt_gentoggle_0_odeIdeal/library/igenebind','position',[935,962,985,982]);
  delete_line('ckt_gentoggle_0_odeIdeal/library/igenebind','In1/1','Out1/1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/igenebind/In1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/igenebind/Out1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/igenebind/TF');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/igenebind/_TF');
  set_param('ckt_gentoggle_0_odeIdeal/library/igenebind/TF','position',[720,789,770,809]);
  add_line('ckt_gentoggle_0_odeIdeal/library/igenebind','TF/1','_TF/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/igenebind/K');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/igenebind/_K');
  set_param('ckt_gentoggle_0_odeIdeal/library/igenebind/K','position',[308,354,358,374]);
  add_line('ckt_gentoggle_0_odeIdeal/library/igenebind','K/1','_K/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/igenebind/Vmax');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/igenebind/_Vmax');
  set_param('ckt_gentoggle_0_odeIdeal/library/igenebind/Vmax','position',[515,349,565,369]);
  add_line('ckt_gentoggle_0_odeIdeal/library/igenebind','Vmax/1','_Vmax/1');
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_0_odeIdeal/library/igenebind/GE');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/igenebind/_GE');
  add_line('ckt_gentoggle_0_odeIdeal/library/igenebind','_GE/1','GE/1');
  set_param('ckt_gentoggle_0_odeIdeal/library/igenebind/GE','position',[67,456,117,476]);
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/library/igenebind/const_451');
  set_param('ckt_gentoggle_0_odeIdeal/library/igenebind/const_451','Value','1.');
  set_param('ckt_gentoggle_0_odeIdeal/library/igenebind/const_451','position',[609,18,659,38]);
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/library/igenebind/const_453');
  set_param('ckt_gentoggle_0_odeIdeal/library/igenebind/const_453','Value','1.');
  set_param('ckt_gentoggle_0_odeIdeal/library/igenebind/const_453','position',[450,513,500,533]);
  add_block('simulink/Math Operations/Product','ckt_gentoggle_0_odeIdeal/library/igenebind/mul_455');
  set_param('ckt_gentoggle_0_odeIdeal/library/igenebind/mul_455','Inputs','**');
  set_param('ckt_gentoggle_0_odeIdeal/library/igenebind/mul_455','position',[311,255,361,275]);
  add_line('ckt_gentoggle_0_odeIdeal/library/igenebind','_K/1','mul_455/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/igenebind','_TF/1','mul_455/2');
  add_block('simulink/Math Operations/Sum','ckt_gentoggle_0_odeIdeal/library/igenebind/sub_458');
  set_param('ckt_gentoggle_0_odeIdeal/library/igenebind/sub_458','Inputs','++');
  set_param('ckt_gentoggle_0_odeIdeal/library/igenebind/sub_458','position',[805,953,855,973]);
  add_line('ckt_gentoggle_0_odeIdeal/library/igenebind','const_453/1','sub_458/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/igenebind','mul_455/1','sub_458/2');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_0_odeIdeal/library/igenebind/div_461');
  set_param('ckt_gentoggle_0_odeIdeal/library/igenebind/div_461','Inputs','*/');
  set_param('ckt_gentoggle_0_odeIdeal/library/igenebind/div_461','position',[915,124,965,144]);
  add_line('ckt_gentoggle_0_odeIdeal/library/igenebind','const_451/1','div_461/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/igenebind','sub_458/1','div_461/2');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_0_odeIdeal/library/igenebind/mul_464');
  set_param('ckt_gentoggle_0_odeIdeal/library/igenebind/mul_464','Inputs','**');
  set_param('ckt_gentoggle_0_odeIdeal/library/igenebind/mul_464','position',[413,65,463,85]);
  add_line('ckt_gentoggle_0_odeIdeal/library/igenebind','_Vmax/1','mul_464/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/igenebind','div_461/1','mul_464/2');
  add_line('ckt_gentoggle_0_odeIdeal/library/igenebind','mul_464/1','_GE/1');
end
%
%
%
