%toplevel script
function main()
  preamble();
  build_comp_library();
  build_circuit();
end
%
%
%circuit build script
function build_circuit()
  add_block('simulink/Ports & Subsystems/Subsystem','ckt_gentoggle_8_odeIdeal/circuit');
  set_param('ckt_gentoggle_8_odeIdeal/circuit','position',[410,279,460,299]);
  delete_line('ckt_gentoggle_8_odeIdeal/circuit','In1/1','Out1/1');
  delete_block('ckt_gentoggle_8_odeIdeal/circuit/In1');
  delete_block('ckt_gentoggle_8_odeIdeal/circuit/Out1');
  add_block('ckt_gentoggle_8_odeIdeal/library/vgain','ckt_gentoggle_8_odeIdeal/circuit/vgain[0]');
  add_block('ckt_gentoggle_8_odeIdeal/library/switch','ckt_gentoggle_8_odeIdeal/circuit/switch[6]');
  add_block('ckt_gentoggle_8_odeIdeal/library/input.I','ckt_gentoggle_8_odeIdeal/circuit/input.I[2]');
  add_block('ckt_gentoggle_8_odeIdeal/library/input.I','ckt_gentoggle_8_odeIdeal/circuit/input.I[0]');
  add_block('ckt_gentoggle_8_odeIdeal/library/input.I','ckt_gentoggle_8_odeIdeal/circuit/input.I[15]');
  add_block('ckt_gentoggle_8_odeIdeal/library/input.I','ckt_gentoggle_8_odeIdeal/circuit/input.I[14]');
  add_block('ckt_gentoggle_8_odeIdeal/library/input.I','ckt_gentoggle_8_odeIdeal/circuit/input.I[16]');
  add_block('ckt_gentoggle_8_odeIdeal/library/input.I','ckt_gentoggle_8_odeIdeal/circuit/input.I[3]');
  add_block('ckt_gentoggle_8_odeIdeal/library/input.I','ckt_gentoggle_8_odeIdeal/circuit/input.I[4]');
  add_block('ckt_gentoggle_8_odeIdeal/library/input.I','ckt_gentoggle_8_odeIdeal/circuit/input.I[5]');
  add_block('ckt_gentoggle_8_odeIdeal/library/input.I','ckt_gentoggle_8_odeIdeal/circuit/input.I[1]');
  add_block('ckt_gentoggle_8_odeIdeal/library/output.V','ckt_gentoggle_8_odeIdeal/circuit/output.V[0]');
  add_block('ckt_gentoggle_8_odeIdeal/library/output.V','ckt_gentoggle_8_odeIdeal/circuit/output.V[1]');
  add_block('ckt_gentoggle_8_odeIdeal/library/vadd','ckt_gentoggle_8_odeIdeal/circuit/vadd[5]');
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_odeIdeal/circuit/const_468');
  set_param('ckt_gentoggle_8_odeIdeal/circuit/const_468','Value','1.');
  set_param('ckt_gentoggle_8_odeIdeal/circuit/const_468','position',[793,56,843,76]);
  add_line('ckt_gentoggle_8_odeIdeal/circuit','const_468/1','vadd[5]/6');
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_odeIdeal/circuit/const_470');
  set_param('ckt_gentoggle_8_odeIdeal/circuit/const_470','Value','1.');
  set_param('ckt_gentoggle_8_odeIdeal/circuit/const_470','position',[206,207,256,227]);
  add_line('ckt_gentoggle_8_odeIdeal/circuit','const_470/1','vadd[5]/7');
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_odeIdeal/circuit/const_472');
  set_param('ckt_gentoggle_8_odeIdeal/circuit/const_472','Value','1.');
  set_param('ckt_gentoggle_8_odeIdeal/circuit/const_472','position',[667,626,717,646]);
  add_line('ckt_gentoggle_8_odeIdeal/circuit','const_472/1','vadd[5]/8');
  set_param('ckt_gentoggle_8_odeIdeal/circuit/vadd[5]/int_375','InitialCondition','0.');
  add_block('ckt_gentoggle_8_odeIdeal/library/vadd','ckt_gentoggle_8_odeIdeal/circuit/vadd[1]');
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_odeIdeal/circuit/const_474');
  set_param('ckt_gentoggle_8_odeIdeal/circuit/const_474','Value','1.');
  set_param('ckt_gentoggle_8_odeIdeal/circuit/const_474','position',[887,481,937,501]);
  add_line('ckt_gentoggle_8_odeIdeal/circuit','const_474/1','vadd[1]/6');
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_odeIdeal/circuit/const_476');
  set_param('ckt_gentoggle_8_odeIdeal/circuit/const_476','Value','1.');
  set_param('ckt_gentoggle_8_odeIdeal/circuit/const_476','position',[380,25,430,45]);
  add_line('ckt_gentoggle_8_odeIdeal/circuit','const_476/1','vadd[1]/7');
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_odeIdeal/circuit/const_478');
  set_param('ckt_gentoggle_8_odeIdeal/circuit/const_478','Value','1.');
  set_param('ckt_gentoggle_8_odeIdeal/circuit/const_478','position',[725,836,775,856]);
  add_line('ckt_gentoggle_8_odeIdeal/circuit','const_478/1','vadd[1]/8');
  set_param('ckt_gentoggle_8_odeIdeal/circuit/vadd[1]/int_375','InitialCondition','0.');
  add_block('ckt_gentoggle_8_odeIdeal/library/ihill','ckt_gentoggle_8_odeIdeal/circuit/ihill[2]');
  add_block('ckt_gentoggle_8_odeIdeal/library/ihill','ckt_gentoggle_8_odeIdeal/circuit/ihill[3]');
  add_block('ckt_gentoggle_8_odeIdeal/library/vtoi','ckt_gentoggle_8_odeIdeal/circuit/vtoi[0]');
  add_block('ckt_gentoggle_8_odeIdeal/library/input.V','ckt_gentoggle_8_odeIdeal/circuit/input.V[2]');
  add_block('ckt_gentoggle_8_odeIdeal/library/input.V','ckt_gentoggle_8_odeIdeal/circuit/input.V[8]');
  add_block('ckt_gentoggle_8_odeIdeal/library/input.V','ckt_gentoggle_8_odeIdeal/circuit/input.V[7]');
  add_block('ckt_gentoggle_8_odeIdeal/library/input.V','ckt_gentoggle_8_odeIdeal/circuit/input.V[13]');
  add_block('ckt_gentoggle_8_odeIdeal/library/input.V','ckt_gentoggle_8_odeIdeal/circuit/input.V[12]');
  add_block('ckt_gentoggle_8_odeIdeal/library/input.V','ckt_gentoggle_8_odeIdeal/circuit/input.V[9]');
  add_block('ckt_gentoggle_8_odeIdeal/library/input.V','ckt_gentoggle_8_odeIdeal/circuit/input.V[0]');
  add_block('ckt_gentoggle_8_odeIdeal/library/input.V','ckt_gentoggle_8_odeIdeal/circuit/input.V[11]');
  add_block('ckt_gentoggle_8_odeIdeal/library/input.V','ckt_gentoggle_8_odeIdeal/circuit/input.V[10]');
  add_block('ckt_gentoggle_8_odeIdeal/library/input.V','ckt_gentoggle_8_odeIdeal/circuit/input.V[6]');
  add_block('ckt_gentoggle_8_odeIdeal/library/input.V','ckt_gentoggle_8_odeIdeal/circuit/input.V[16]');
  add_block('ckt_gentoggle_8_odeIdeal/library/input.V','ckt_gentoggle_8_odeIdeal/circuit/input.V[3]');
  add_block('ckt_gentoggle_8_odeIdeal/library/input.V','ckt_gentoggle_8_odeIdeal/circuit/input.V[4]');
  add_block('ckt_gentoggle_8_odeIdeal/library/input.V','ckt_gentoggle_8_odeIdeal/circuit/input.V[5]');
  add_block('ckt_gentoggle_8_odeIdeal/library/input.V','ckt_gentoggle_8_odeIdeal/circuit/input.V[1]');
  add_block('ckt_gentoggle_8_odeIdeal/library/input.V','ckt_gentoggle_8_odeIdeal/circuit/input.V[17]');
  add_block('ckt_gentoggle_8_odeIdeal/library/itov','ckt_gentoggle_8_odeIdeal/circuit/itov[5]');
  add_block('ckt_gentoggle_8_odeIdeal/library/itov','ckt_gentoggle_8_odeIdeal/circuit/itov[4]');
  add_block('ckt_gentoggle_8_odeIdeal/library/iadd','ckt_gentoggle_8_odeIdeal/circuit/iadd[0]');
  add_line('ckt_gentoggle_8_odeIdeal/circuit','input.V[17]/1','vtoi[0]/2');
  add_line('ckt_gentoggle_8_odeIdeal/circuit','vadd[1]/2','output.V[0]/1');
  add_line('ckt_gentoggle_8_odeIdeal/circuit','vadd[1]/2','vtoi[0]/1');
  add_line('ckt_gentoggle_8_odeIdeal/circuit','input.I[0]/1','switch[6]/2');
  add_line('ckt_gentoggle_8_odeIdeal/circuit','input.V[9]/1','vadd[5]/2');
  add_line('ckt_gentoggle_8_odeIdeal/circuit','input.I[16]/1','iadd[0]/3');
  add_line('ckt_gentoggle_8_odeIdeal/circuit','input.I[4]/1','ihill[2]/4');
  add_line('ckt_gentoggle_8_odeIdeal/circuit','input.V[13]/1','vgain[0]/1');
  add_line('ckt_gentoggle_8_odeIdeal/circuit','input.I[3]/1','ihill[3]/4');
  add_line('ckt_gentoggle_8_odeIdeal/circuit','input.I[5]/1','switch[6]/3');
  add_line('ckt_gentoggle_8_odeIdeal/circuit','vtoi[0]/1','ihill[3]/2');
  add_line('ckt_gentoggle_8_odeIdeal/circuit','ihill[3]/2','itov[4]/1');
  add_line('ckt_gentoggle_8_odeIdeal/circuit','input.I[14]/1','iadd[0]/2');
  add_line('ckt_gentoggle_8_odeIdeal/circuit','itov[5]/1','vgain[0]/3');
  add_line('ckt_gentoggle_8_odeIdeal/circuit','input.V[11]/1','switch[6]/1');
  add_line('ckt_gentoggle_8_odeIdeal/circuit','input.V[8]/1','vadd[1]/2');
  add_line('ckt_gentoggle_8_odeIdeal/circuit','input.V[12]/1','ihill[2]/1');
  add_line('ckt_gentoggle_8_odeIdeal/circuit','input.I[2]/1','ihill[2]/3');
  add_line('ckt_gentoggle_8_odeIdeal/circuit','ihill[2]/2','itov[5]/1');
  add_line('ckt_gentoggle_8_odeIdeal/circuit','input.V[2]/1','vadd[1]/4');
  add_line('ckt_gentoggle_8_odeIdeal/circuit','input.V[3]/1','vadd[1]/3');
  add_line('ckt_gentoggle_8_odeIdeal/circuit','vadd[5]/2','output.V[1]/1');
  add_line('ckt_gentoggle_8_odeIdeal/circuit','vadd[5]/2','switch[6]/4');
  add_line('ckt_gentoggle_8_odeIdeal/circuit','switch[6]/1','iadd[0]/4');
  add_line('ckt_gentoggle_8_odeIdeal/circuit','iadd[0]/1','ihill[2]/2');
  add_line('ckt_gentoggle_8_odeIdeal/circuit','input.I[15]/1','iadd[0]/1');
  add_line('ckt_gentoggle_8_odeIdeal/circuit','input.I[1]/1','ihill[3]/3');
  add_line('ckt_gentoggle_8_odeIdeal/circuit','input.V[1]/1','vgain[0]/2');
  add_line('ckt_gentoggle_8_odeIdeal/circuit','vgain[0]/1','vadd[1]/5');
  add_line('ckt_gentoggle_8_odeIdeal/circuit','input.V[7]/1','vadd[1]/1');
  add_line('ckt_gentoggle_8_odeIdeal/circuit','input.V[0]/1','ihill[3]/1');
  add_line('ckt_gentoggle_8_odeIdeal/circuit','input.V[10]/1','itov[4]/2');
  add_line('ckt_gentoggle_8_odeIdeal/circuit','input.V[16]/1','itov[5]/2');
  add_line('ckt_gentoggle_8_odeIdeal/circuit','itov[4]/1','vadd[5]/5');
  add_line('ckt_gentoggle_8_odeIdeal/circuit','input.V[4]/1','vadd[5]/3');
  add_line('ckt_gentoggle_8_odeIdeal/circuit','input.V[5]/1','vadd[5]/4');
  add_line('ckt_gentoggle_8_odeIdeal/circuit','input.V[6]/1','vadd[5]/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_8_odeIdeal/circuit/input.I[0]_in');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_odeIdeal/circuit/_input.I[0]_in');
  set_param('ckt_gentoggle_8_odeIdeal/circuit/input.I[0]_in','position',[808,206,858,226]);
  add_line('ckt_gentoggle_8_odeIdeal/circuit','input.I[0]_in/1','_input.I[0]_in/1');
  add_line('ckt_gentoggle_8_odeIdeal/circuit','_input.I[0]_in/1','input.I[0]/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_8_odeIdeal/circuit/input.I[1]_in');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_odeIdeal/circuit/_input.I[1]_in');
  set_param('ckt_gentoggle_8_odeIdeal/circuit/input.I[1]_in','position',[216,307,266,327]);
  add_line('ckt_gentoggle_8_odeIdeal/circuit','input.I[1]_in/1','_input.I[1]_in/1');
  add_line('ckt_gentoggle_8_odeIdeal/circuit','_input.I[1]_in/1','input.I[1]/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_8_odeIdeal/circuit/input.I[2]_in');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_odeIdeal/circuit/_input.I[2]_in');
  set_param('ckt_gentoggle_8_odeIdeal/circuit/input.I[2]_in','position',[119,805,169,825]);
  add_line('ckt_gentoggle_8_odeIdeal/circuit','input.I[2]_in/1','_input.I[2]_in/1');
  add_line('ckt_gentoggle_8_odeIdeal/circuit','_input.I[2]_in/1','input.I[2]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_odeIdeal/circuit/const_495');
  set_param('ckt_gentoggle_8_odeIdeal/circuit/const_495','Value','0.15625');
  set_param('ckt_gentoggle_8_odeIdeal/circuit/const_495','position',[71,648,121,668]);
  add_line('ckt_gentoggle_8_odeIdeal/circuit','const_495/1','input.I[3]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_odeIdeal/circuit/const_497');
  set_param('ckt_gentoggle_8_odeIdeal/circuit/const_497','Value','0.0156');
  set_param('ckt_gentoggle_8_odeIdeal/circuit/const_497','position',[778,769,828,789]);
  add_line('ckt_gentoggle_8_odeIdeal/circuit','const_497/1','input.I[4]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_odeIdeal/circuit/const_499');
  set_param('ckt_gentoggle_8_odeIdeal/circuit/const_499','Value','2.5');
  set_param('ckt_gentoggle_8_odeIdeal/circuit/const_499','position',[760,624,810,644]);
  add_line('ckt_gentoggle_8_odeIdeal/circuit','const_499/1','input.V[0]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_odeIdeal/circuit/const_501');
  set_param('ckt_gentoggle_8_odeIdeal/circuit/const_501','Value','0.125');
  set_param('ckt_gentoggle_8_odeIdeal/circuit/const_501','position',[665,982,715,1002]);
  add_line('ckt_gentoggle_8_odeIdeal/circuit','const_501/1','input.V[1]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_odeIdeal/circuit/const_503');
  set_param('ckt_gentoggle_8_odeIdeal/circuit/const_503','Value','0.');
  set_param('ckt_gentoggle_8_odeIdeal/circuit/const_503','position',[534,615,584,635]);
  add_line('ckt_gentoggle_8_odeIdeal/circuit','const_503/1','input.I[14]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_odeIdeal/circuit/const_505');
  set_param('ckt_gentoggle_8_odeIdeal/circuit/const_505','Value','0.');
  set_param('ckt_gentoggle_8_odeIdeal/circuit/const_505','position',[322,140,372,160]);
  add_line('ckt_gentoggle_8_odeIdeal/circuit','const_505/1','input.I[15]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_odeIdeal/circuit/const_507');
  set_param('ckt_gentoggle_8_odeIdeal/circuit/const_507','Value','0.');
  set_param('ckt_gentoggle_8_odeIdeal/circuit/const_507','position',[555,697,605,717]);
  add_line('ckt_gentoggle_8_odeIdeal/circuit','const_507/1','input.I[16]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_odeIdeal/circuit/const_509');
  set_param('ckt_gentoggle_8_odeIdeal/circuit/const_509','Value','0.');
  set_param('ckt_gentoggle_8_odeIdeal/circuit/const_509','position',[780,872,830,892]);
  add_line('ckt_gentoggle_8_odeIdeal/circuit','const_509/1','input.V[2]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_odeIdeal/circuit/const_511');
  set_param('ckt_gentoggle_8_odeIdeal/circuit/const_511','Value','0.');
  set_param('ckt_gentoggle_8_odeIdeal/circuit/const_511','position',[996,913,1046,933]);
  add_line('ckt_gentoggle_8_odeIdeal/circuit','const_511/1','input.V[3]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_odeIdeal/circuit/const_513');
  set_param('ckt_gentoggle_8_odeIdeal/circuit/const_513','Value','0.');
  set_param('ckt_gentoggle_8_odeIdeal/circuit/const_513','position',[159,973,209,993]);
  add_line('ckt_gentoggle_8_odeIdeal/circuit','const_513/1','input.V[4]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_odeIdeal/circuit/const_515');
  set_param('ckt_gentoggle_8_odeIdeal/circuit/const_515','Value','0.');
  set_param('ckt_gentoggle_8_odeIdeal/circuit/const_515','position',[492,266,542,286]);
  add_line('ckt_gentoggle_8_odeIdeal/circuit','const_515/1','input.V[5]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_odeIdeal/circuit/const_517');
  set_param('ckt_gentoggle_8_odeIdeal/circuit/const_517','Value','0.');
  set_param('ckt_gentoggle_8_odeIdeal/circuit/const_517','position',[321,964,371,984]);
  add_line('ckt_gentoggle_8_odeIdeal/circuit','const_517/1','input.V[6]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_odeIdeal/circuit/const_519');
  set_param('ckt_gentoggle_8_odeIdeal/circuit/const_519','Value','0.');
  set_param('ckt_gentoggle_8_odeIdeal/circuit/const_519','position',[837,582,887,602]);
  add_line('ckt_gentoggle_8_odeIdeal/circuit','const_519/1','input.V[7]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_odeIdeal/circuit/const_521');
  set_param('ckt_gentoggle_8_odeIdeal/circuit/const_521','Value','4.');
  set_param('ckt_gentoggle_8_odeIdeal/circuit/const_521','position',[965,870,1015,890]);
  add_line('ckt_gentoggle_8_odeIdeal/circuit','const_521/1','input.V[8]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_odeIdeal/circuit/const_523');
  set_param('ckt_gentoggle_8_odeIdeal/circuit/const_523','Value','4.');
  set_param('ckt_gentoggle_8_odeIdeal/circuit/const_523','position',[928,170,978,190]);
  add_line('ckt_gentoggle_8_odeIdeal/circuit','const_523/1','input.V[9]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_odeIdeal/circuit/const_525');
  set_param('ckt_gentoggle_8_odeIdeal/circuit/const_525','Value','4.');
  set_param('ckt_gentoggle_8_odeIdeal/circuit/const_525','position',[231,769,281,789]);
  add_line('ckt_gentoggle_8_odeIdeal/circuit','const_525/1','input.V[10]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_odeIdeal/circuit/const_527');
  set_param('ckt_gentoggle_8_odeIdeal/circuit/const_527','Value','1000.75');
  set_param('ckt_gentoggle_8_odeIdeal/circuit/const_527','position',[894,288,944,308]);
  add_line('ckt_gentoggle_8_odeIdeal/circuit','const_527/1','input.V[11]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_odeIdeal/circuit/const_529');
  set_param('ckt_gentoggle_8_odeIdeal/circuit/const_529','Value','0.0029618');
  set_param('ckt_gentoggle_8_odeIdeal/circuit/const_529','position',[90,296,140,316]);
  add_line('ckt_gentoggle_8_odeIdeal/circuit','const_529/1','input.I[5]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_odeIdeal/circuit/const_531');
  set_param('ckt_gentoggle_8_odeIdeal/circuit/const_531','Value','1.');
  set_param('ckt_gentoggle_8_odeIdeal/circuit/const_531','position',[206,343,256,363]);
  add_line('ckt_gentoggle_8_odeIdeal/circuit','const_531/1','input.V[16]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_odeIdeal/circuit/const_533');
  set_param('ckt_gentoggle_8_odeIdeal/circuit/const_533','Value','1.');
  set_param('ckt_gentoggle_8_odeIdeal/circuit/const_533','position',[816,456,866,476]);
  add_line('ckt_gentoggle_8_odeIdeal/circuit','const_533/1','input.V[17]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_odeIdeal/circuit/const_535');
  set_param('ckt_gentoggle_8_odeIdeal/circuit/const_535','Value','1.');
  set_param('ckt_gentoggle_8_odeIdeal/circuit/const_535','position',[770,931,820,951]);
  add_line('ckt_gentoggle_8_odeIdeal/circuit','const_535/1','input.V[12]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_odeIdeal/circuit/const_537');
  set_param('ckt_gentoggle_8_odeIdeal/circuit/const_537','Value','1.');
  set_param('ckt_gentoggle_8_odeIdeal/circuit/const_537','position',[170,997,220,1017]);
  add_line('ckt_gentoggle_8_odeIdeal/circuit','const_537/1','input.V[13]/1');
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_8_odeIdeal/circuit/output.V[0]_out');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_odeIdeal/circuit/_output.V[0]_out');
  add_line('ckt_gentoggle_8_odeIdeal/circuit','_output.V[0]_out/1','output.V[0]_out/1');
  set_param('ckt_gentoggle_8_odeIdeal/circuit/output.V[0]_out','position',[896,603,946,623]);
  add_line('ckt_gentoggle_8_odeIdeal/circuit','output.V[0]/1','_output.V[0]_out/1');
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_8_odeIdeal/circuit/output.V[1]_out');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_odeIdeal/circuit/_output.V[1]_out');
  add_line('ckt_gentoggle_8_odeIdeal/circuit','_output.V[1]_out/1','output.V[1]_out/1');
  set_param('ckt_gentoggle_8_odeIdeal/circuit/output.V[1]_out','position',[905,141,955,161]);
  add_line('ckt_gentoggle_8_odeIdeal/circuit','output.V[1]/1','_output.V[1]_out/1');
end
%
%
%preamble function
function preamble()
  %define model name
  model_name='ckt_gentoggle_8_odeIdeal';
  %create and open the model
  open_system(new_system(model_name));
  %set solver method
  set_param(model_name,'Solver','ode3');
end
%
%
%library assembly function
function build_comp_library()
  add_block('simulink/Ports & Subsystems/Subsystem','ckt_gentoggle_8_odeIdeal/library');
  set_param('ckt_gentoggle_8_odeIdeal/library','position',[63,327,113,347]);
  delete_line('ckt_gentoggle_8_odeIdeal/library','In1/1','Out1/1');
  delete_block('ckt_gentoggle_8_odeIdeal/library/In1');
  delete_block('ckt_gentoggle_8_odeIdeal/library/Out1');
  %
  %
  %
  add_block('simulink/Ports & Subsystems/Subsystem','ckt_gentoggle_8_odeIdeal/library/mm');
  set_param('ckt_gentoggle_8_odeIdeal/library/mm','position',[742,495,792,515]);
  delete_line('ckt_gentoggle_8_odeIdeal/library/mm','In1/1','Out1/1');
  delete_block('ckt_gentoggle_8_odeIdeal/library/mm/In1');
  delete_block('ckt_gentoggle_8_odeIdeal/library/mm/Out1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_8_odeIdeal/library/mm/kr');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_odeIdeal/library/mm/_kr');
  set_param('ckt_gentoggle_8_odeIdeal/library/mm/kr','position',[101,884,151,904]);
  add_line('ckt_gentoggle_8_odeIdeal/library/mm','kr/1','_kr/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_8_odeIdeal/library/mm/XY0');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_odeIdeal/library/mm/_XY0');
  set_param('ckt_gentoggle_8_odeIdeal/library/mm/XY0','position',[708,450,758,470]);
  add_line('ckt_gentoggle_8_odeIdeal/library/mm','XY0/1','_XY0/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_8_odeIdeal/library/mm/Ytot');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_odeIdeal/library/mm/_Ytot');
  set_param('ckt_gentoggle_8_odeIdeal/library/mm/Ytot','position',[64,269,114,289]);
  add_line('ckt_gentoggle_8_odeIdeal/library/mm','Ytot/1','_Ytot/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_8_odeIdeal/library/mm/kf');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_odeIdeal/library/mm/_kf');
  set_param('ckt_gentoggle_8_odeIdeal/library/mm/kf','position',[830,199,880,219]);
  add_line('ckt_gentoggle_8_odeIdeal/library/mm','kf/1','_kf/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_8_odeIdeal/library/mm/Xtot');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_odeIdeal/library/mm/_Xtot');
  set_param('ckt_gentoggle_8_odeIdeal/library/mm/Xtot','position',[123,200,173,220]);
  add_line('ckt_gentoggle_8_odeIdeal/library/mm','Xtot/1','_Xtot/1');
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_8_odeIdeal/library/mm/X');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_odeIdeal/library/mm/_X');
  add_line('ckt_gentoggle_8_odeIdeal/library/mm','_X/1','X/1');
  set_param('ckt_gentoggle_8_odeIdeal/library/mm/X','position',[429,105,479,125]);
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_8_odeIdeal/library/mm/XY');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_odeIdeal/library/mm/_XY');
  add_line('ckt_gentoggle_8_odeIdeal/library/mm','_XY/1','XY/1');
  set_param('ckt_gentoggle_8_odeIdeal/library/mm/XY','position',[459,451,509,471]);
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_8_odeIdeal/library/mm/Y');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_odeIdeal/library/mm/_Y');
  add_line('ckt_gentoggle_8_odeIdeal/library/mm','_Y/1','Y/1');
  set_param('ckt_gentoggle_8_odeIdeal/library/mm/Y','position',[840,216,890,236]);
  add_block('simulink/Math Operations/Sum','ckt_gentoggle_8_odeIdeal/library/mm/sum_39');
  set_param('ckt_gentoggle_8_odeIdeal/library/mm/sum_39','Inputs','+-');
  set_param('ckt_gentoggle_8_odeIdeal/library/mm/sum_39','position',[6,121,56,141]);
  add_line('ckt_gentoggle_8_odeIdeal/library/mm','_Xtot/1','sum_39/1');
  add_line('ckt_gentoggle_8_odeIdeal/library/mm','_XY/1','sum_39/2');
  add_line('ckt_gentoggle_8_odeIdeal/library/mm','sum_39/1','_X/1');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_8_odeIdeal/library/mm/mul_42');
  set_param('ckt_gentoggle_8_odeIdeal/library/mm/mul_42','Inputs','***');
  set_param('ckt_gentoggle_8_odeIdeal/library/mm/mul_42','position',[38,256,88,276]);
  add_line('ckt_gentoggle_8_odeIdeal/library/mm','_kf/1','mul_42/1');
  add_line('ckt_gentoggle_8_odeIdeal/library/mm','_X/1','mul_42/2');
  add_line('ckt_gentoggle_8_odeIdeal/library/mm','_Y/1','mul_42/3');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_8_odeIdeal/library/mm/mul_46');
  set_param('ckt_gentoggle_8_odeIdeal/library/mm/mul_46','Inputs','**');
  set_param('ckt_gentoggle_8_odeIdeal/library/mm/mul_46','position',[752,652,802,672]);
  add_line('ckt_gentoggle_8_odeIdeal/library/mm','_kr/1','mul_46/1');
  add_line('ckt_gentoggle_8_odeIdeal/library/mm','_XY/1','mul_46/2');
  add_block('simulink/Math Operations/Sum','ckt_gentoggle_8_odeIdeal/library/mm/sum_49');
  set_param('ckt_gentoggle_8_odeIdeal/library/mm/sum_49','Inputs','+-');
  set_param('ckt_gentoggle_8_odeIdeal/library/mm/sum_49','position',[774,573,824,593]);
  add_line('ckt_gentoggle_8_odeIdeal/library/mm','mul_42/1','sum_49/1');
  add_line('ckt_gentoggle_8_odeIdeal/library/mm','mul_46/1','sum_49/2');
  add_block('simulink/Continuous/Integrator','ckt_gentoggle_8_odeIdeal/library/mm/int_52');
  set_param('ckt_gentoggle_8_odeIdeal/library/mm/int_52','position',[274,968,324,988]);
  add_line('ckt_gentoggle_8_odeIdeal/library/mm','sum_49/1','int_52/1');
  add_line('ckt_gentoggle_8_odeIdeal/library/mm','int_52/1','_XY/1');
  add_block('simulink/Math Operations/Sum','ckt_gentoggle_8_odeIdeal/library/mm/sum_54');
  set_param('ckt_gentoggle_8_odeIdeal/library/mm/sum_54','Inputs','+-');
  set_param('ckt_gentoggle_8_odeIdeal/library/mm/sum_54','position',[895,414,945,434]);
  add_line('ckt_gentoggle_8_odeIdeal/library/mm','_Ytot/1','sum_54/1');
  add_line('ckt_gentoggle_8_odeIdeal/library/mm','_XY/1','sum_54/2');
  add_line('ckt_gentoggle_8_odeIdeal/library/mm','sum_54/1','_Y/1');
  %
  add_block('simulink/Ports & Subsystems/Subsystem','ckt_gentoggle_8_odeIdeal/library/vgain');
  set_param('ckt_gentoggle_8_odeIdeal/library/vgain','position',[720,701,770,721]);
  delete_line('ckt_gentoggle_8_odeIdeal/library/vgain','In1/1','Out1/1');
  delete_block('ckt_gentoggle_8_odeIdeal/library/vgain/In1');
  delete_block('ckt_gentoggle_8_odeIdeal/library/vgain/Out1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_8_odeIdeal/library/vgain/X');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_odeIdeal/library/vgain/_X');
  set_param('ckt_gentoggle_8_odeIdeal/library/vgain/X','position',[215,890,265,910]);
  add_line('ckt_gentoggle_8_odeIdeal/library/vgain','X/1','_X/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_8_odeIdeal/library/vgain/Y');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_odeIdeal/library/vgain/_Y');
  set_param('ckt_gentoggle_8_odeIdeal/library/vgain/Y','position',[945,985,995,1005]);
  add_line('ckt_gentoggle_8_odeIdeal/library/vgain','Y/1','_Y/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_8_odeIdeal/library/vgain/Z');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_odeIdeal/library/vgain/_Z');
  set_param('ckt_gentoggle_8_odeIdeal/library/vgain/Z','position',[556,299,606,319]);
  add_line('ckt_gentoggle_8_odeIdeal/library/vgain','Z/1','_Z/1');
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_8_odeIdeal/library/vgain/P');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_odeIdeal/library/vgain/_P');
  add_line('ckt_gentoggle_8_odeIdeal/library/vgain','_P/1','P/1');
  set_param('ckt_gentoggle_8_odeIdeal/library/vgain/P','position',[652,388,702,408]);
  add_block('simulink/Math Operations/Product','ckt_gentoggle_8_odeIdeal/library/vgain/div_77');
  set_param('ckt_gentoggle_8_odeIdeal/library/vgain/div_77','Inputs','*/');
  set_param('ckt_gentoggle_8_odeIdeal/library/vgain/div_77','position',[513,841,563,861]);
  add_line('ckt_gentoggle_8_odeIdeal/library/vgain','_X/1','div_77/1');
  add_line('ckt_gentoggle_8_odeIdeal/library/vgain','_Y/1','div_77/2');
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_odeIdeal/library/vgain/const_80');
  set_param('ckt_gentoggle_8_odeIdeal/library/vgain/const_80','Value','0.5');
  set_param('ckt_gentoggle_8_odeIdeal/library/vgain/const_80','position',[758,166,808,186]);
  add_block('simulink/Math Operations/Product','ckt_gentoggle_8_odeIdeal/library/vgain/mul_82');
  set_param('ckt_gentoggle_8_odeIdeal/library/vgain/mul_82','Inputs','***');
  set_param('ckt_gentoggle_8_odeIdeal/library/vgain/mul_82','position',[259,178,309,198]);
  add_line('ckt_gentoggle_8_odeIdeal/library/vgain','div_77/1','mul_82/1');
  add_line('ckt_gentoggle_8_odeIdeal/library/vgain','_Z/1','mul_82/2');
  add_line('ckt_gentoggle_8_odeIdeal/library/vgain','const_80/1','mul_82/3');
  add_line('ckt_gentoggle_8_odeIdeal/library/vgain','mul_82/1','_P/1');
  %
  add_block('simulink/Ports & Subsystems/Subsystem','ckt_gentoggle_8_odeIdeal/library/switch');
  set_param('ckt_gentoggle_8_odeIdeal/library/switch','position',[796,489,846,509]);
  delete_line('ckt_gentoggle_8_odeIdeal/library/switch','In1/1','Out1/1');
  delete_block('ckt_gentoggle_8_odeIdeal/library/switch/In1');
  delete_block('ckt_gentoggle_8_odeIdeal/library/switch/Out1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_8_odeIdeal/library/switch/n');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_odeIdeal/library/switch/_n');
  set_param('ckt_gentoggle_8_odeIdeal/library/switch/n','position',[891,934,941,954]);
  add_line('ckt_gentoggle_8_odeIdeal/library/switch','n/1','_n/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_8_odeIdeal/library/switch/SUB');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_odeIdeal/library/switch/_SUB');
  set_param('ckt_gentoggle_8_odeIdeal/library/switch/SUB','position',[460,778,510,798]);
  add_line('ckt_gentoggle_8_odeIdeal/library/switch','SUB/1','_SUB/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_8_odeIdeal/library/switch/Kmod');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_odeIdeal/library/switch/_Kmod');
  set_param('ckt_gentoggle_8_odeIdeal/library/switch/Kmod','position',[970,804,1020,824]);
  add_line('ckt_gentoggle_8_odeIdeal/library/switch','Kmod/1','_Kmod/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_8_odeIdeal/library/switch/Vmax');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_odeIdeal/library/switch/_Vmax');
  set_param('ckt_gentoggle_8_odeIdeal/library/switch/Vmax','position',[246,829,296,849]);
  add_line('ckt_gentoggle_8_odeIdeal/library/switch','Vmax/1','_Vmax/1');
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_8_odeIdeal/library/switch/PROD');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_odeIdeal/library/switch/_PROD');
  add_line('ckt_gentoggle_8_odeIdeal/library/switch','_PROD/1','PROD/1');
  set_param('ckt_gentoggle_8_odeIdeal/library/switch/PROD','position',[852,511,902,531]);
  add_block('simulink/Math Operations/Product','ckt_gentoggle_8_odeIdeal/library/switch/div_111');
  set_param('ckt_gentoggle_8_odeIdeal/library/switch/div_111','Inputs','*/');
  set_param('ckt_gentoggle_8_odeIdeal/library/switch/div_111','position',[37,561,87,581]);
  add_line('ckt_gentoggle_8_odeIdeal/library/switch','_SUB/1','div_111/1');
  add_line('ckt_gentoggle_8_odeIdeal/library/switch','_Kmod/1','div_111/2');
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_odeIdeal/library/switch/const_114');
  set_param('ckt_gentoggle_8_odeIdeal/library/switch/const_114','Value','1.');
  set_param('ckt_gentoggle_8_odeIdeal/library/switch/const_114','position',[969,611,1019,631]);
  add_block('simulink/Math Operations/Sum','ckt_gentoggle_8_odeIdeal/library/switch/sub_116');
  set_param('ckt_gentoggle_8_odeIdeal/library/switch/sub_116','Inputs','++');
  set_param('ckt_gentoggle_8_odeIdeal/library/switch/sub_116','position',[78,770,128,790]);
  add_line('ckt_gentoggle_8_odeIdeal/library/switch','div_111/1','sub_116/1');
  add_line('ckt_gentoggle_8_odeIdeal/library/switch','const_114/1','sub_116/2');
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_odeIdeal/library/switch/const_119');
  set_param('ckt_gentoggle_8_odeIdeal/library/switch/const_119','Value','500.');
  set_param('ckt_gentoggle_8_odeIdeal/library/switch/const_119','position',[391,205,441,225]);
  add_block('simulink/Math Operations/Product','ckt_gentoggle_8_odeIdeal/library/switch/div_121');
  set_param('ckt_gentoggle_8_odeIdeal/library/switch/div_121','Inputs','*/');
  set_param('ckt_gentoggle_8_odeIdeal/library/switch/div_121','position',[587,57,637,77]);
  add_line('ckt_gentoggle_8_odeIdeal/library/switch','_n/1','div_121/1');
  add_line('ckt_gentoggle_8_odeIdeal/library/switch','const_119/1','div_121/2');
  add_block('simulink/Math Operations/Math Function','ckt_gentoggle_8_odeIdeal/library/switch/pow_124');
  set_param('ckt_gentoggle_8_odeIdeal/library/switch/pow_124','Function','pow');
  set_param('ckt_gentoggle_8_odeIdeal/library/switch/pow_124','position',[992,987,1042,1007]);
  add_line('ckt_gentoggle_8_odeIdeal/library/switch','div_121/1','pow_124/2');
  add_line('ckt_gentoggle_8_odeIdeal/library/switch','sub_116/1','pow_124/1');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_8_odeIdeal/library/switch/div_127');
  set_param('ckt_gentoggle_8_odeIdeal/library/switch/div_127','Inputs','*/');
  set_param('ckt_gentoggle_8_odeIdeal/library/switch/div_127','position',[62,275,112,295]);
  add_line('ckt_gentoggle_8_odeIdeal/library/switch','_Vmax/1','div_127/1');
  add_line('ckt_gentoggle_8_odeIdeal/library/switch','pow_124/1','div_127/2');
  add_line('ckt_gentoggle_8_odeIdeal/library/switch','div_127/1','_PROD/1');
  %
  add_block('simulink/Ports & Subsystems/Subsystem','ckt_gentoggle_8_odeIdeal/library/ihill');
  set_param('ckt_gentoggle_8_odeIdeal/library/ihill','position',[461,548,511,568]);
  delete_line('ckt_gentoggle_8_odeIdeal/library/ihill','In1/1','Out1/1');
  delete_block('ckt_gentoggle_8_odeIdeal/library/ihill/In1');
  delete_block('ckt_gentoggle_8_odeIdeal/library/ihill/Out1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_8_odeIdeal/library/ihill/n');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_odeIdeal/library/ihill/_n');
  set_param('ckt_gentoggle_8_odeIdeal/library/ihill/n','position',[594,758,644,778]);
  add_line('ckt_gentoggle_8_odeIdeal/library/ihill','n/1','_n/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_8_odeIdeal/library/ihill/S');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_odeIdeal/library/ihill/_S');
  set_param('ckt_gentoggle_8_odeIdeal/library/ihill/S','position',[159,291,209,311]);
  add_line('ckt_gentoggle_8_odeIdeal/library/ihill','S/1','_S/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_8_odeIdeal/library/ihill/Km');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_odeIdeal/library/ihill/_Km');
  set_param('ckt_gentoggle_8_odeIdeal/library/ihill/Km','position',[657,548,707,568]);
  add_line('ckt_gentoggle_8_odeIdeal/library/ihill','Km/1','_Km/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_8_odeIdeal/library/ihill/Vmax');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_odeIdeal/library/ihill/_Vmax');
  set_param('ckt_gentoggle_8_odeIdeal/library/ihill/Vmax','position',[935,858,985,878]);
  add_line('ckt_gentoggle_8_odeIdeal/library/ihill','Vmax/1','_Vmax/1');
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_8_odeIdeal/library/ihill/STIM');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_odeIdeal/library/ihill/_STIM');
  add_line('ckt_gentoggle_8_odeIdeal/library/ihill','_STIM/1','STIM/1');
  set_param('ckt_gentoggle_8_odeIdeal/library/ihill/STIM','position',[376,729,426,749]);
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_8_odeIdeal/library/ihill/REP');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_odeIdeal/library/ihill/_REP');
  add_line('ckt_gentoggle_8_odeIdeal/library/ihill','_REP/1','REP/1');
  set_param('ckt_gentoggle_8_odeIdeal/library/ihill/REP','position',[709,49,759,69]);
  add_block('simulink/Math Operations/Product','ckt_gentoggle_8_odeIdeal/library/ihill/div_159');
  set_param('ckt_gentoggle_8_odeIdeal/library/ihill/div_159','Inputs','*/');
  set_param('ckt_gentoggle_8_odeIdeal/library/ihill/div_159','position',[585,145,635,165]);
  add_line('ckt_gentoggle_8_odeIdeal/library/ihill','_S/1','div_159/1');
  add_line('ckt_gentoggle_8_odeIdeal/library/ihill','_Km/1','div_159/2');
  add_block('simulink/Math Operations/Math Function','ckt_gentoggle_8_odeIdeal/library/ihill/pow_162');
  set_param('ckt_gentoggle_8_odeIdeal/library/ihill/pow_162','Function','pow');
  set_param('ckt_gentoggle_8_odeIdeal/library/ihill/pow_162','position',[547,249,597,269]);
  add_line('ckt_gentoggle_8_odeIdeal/library/ihill','_n/1','pow_162/2');
  add_line('ckt_gentoggle_8_odeIdeal/library/ihill','div_159/1','pow_162/1');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_8_odeIdeal/library/ihill/div_165');
  set_param('ckt_gentoggle_8_odeIdeal/library/ihill/div_165','Inputs','*/');
  set_param('ckt_gentoggle_8_odeIdeal/library/ihill/div_165','position',[922,0,972,20]);
  add_line('ckt_gentoggle_8_odeIdeal/library/ihill','_S/1','div_165/1');
  add_line('ckt_gentoggle_8_odeIdeal/library/ihill','_Km/1','div_165/2');
  add_block('simulink/Math Operations/Math Function','ckt_gentoggle_8_odeIdeal/library/ihill/pow_168');
  set_param('ckt_gentoggle_8_odeIdeal/library/ihill/pow_168','Function','pow');
  set_param('ckt_gentoggle_8_odeIdeal/library/ihill/pow_168','position',[341,709,391,729]);
  add_line('ckt_gentoggle_8_odeIdeal/library/ihill','_n/1','pow_168/2');
  add_line('ckt_gentoggle_8_odeIdeal/library/ihill','div_165/1','pow_168/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_odeIdeal/library/ihill/const_171');
  set_param('ckt_gentoggle_8_odeIdeal/library/ihill/const_171','Value','1.');
  set_param('ckt_gentoggle_8_odeIdeal/library/ihill/const_171','position',[29,899,79,919]);
  add_block('simulink/Math Operations/Sum','ckt_gentoggle_8_odeIdeal/library/ihill/sub_173');
  set_param('ckt_gentoggle_8_odeIdeal/library/ihill/sub_173','Inputs','++');
  set_param('ckt_gentoggle_8_odeIdeal/library/ihill/sub_173','position',[387,915,437,935]);
  add_line('ckt_gentoggle_8_odeIdeal/library/ihill','pow_168/1','sub_173/1');
  add_line('ckt_gentoggle_8_odeIdeal/library/ihill','const_171/1','sub_173/2');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_8_odeIdeal/library/ihill/div_176');
  set_param('ckt_gentoggle_8_odeIdeal/library/ihill/div_176','Inputs','*/');
  set_param('ckt_gentoggle_8_odeIdeal/library/ihill/div_176','position',[363,324,413,344]);
  add_line('ckt_gentoggle_8_odeIdeal/library/ihill','pow_162/1','div_176/1');
  add_line('ckt_gentoggle_8_odeIdeal/library/ihill','sub_173/1','div_176/2');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_8_odeIdeal/library/ihill/mul_179');
  set_param('ckt_gentoggle_8_odeIdeal/library/ihill/mul_179','Inputs','**');
  set_param('ckt_gentoggle_8_odeIdeal/library/ihill/mul_179','position',[764,260,814,280]);
  add_line('ckt_gentoggle_8_odeIdeal/library/ihill','_Vmax/1','mul_179/1');
  add_line('ckt_gentoggle_8_odeIdeal/library/ihill','div_176/1','mul_179/2');
  add_line('ckt_gentoggle_8_odeIdeal/library/ihill','mul_179/1','_STIM/1');
  add_block('simulink/Math Operations/Math Function','ckt_gentoggle_8_odeIdeal/library/ihill/pow_182');
  set_param('ckt_gentoggle_8_odeIdeal/library/ihill/pow_182','Function','pow');
  set_param('ckt_gentoggle_8_odeIdeal/library/ihill/pow_182','position',[489,855,539,875]);
  add_line('ckt_gentoggle_8_odeIdeal/library/ihill','_n/1','pow_182/2');
  add_line('ckt_gentoggle_8_odeIdeal/library/ihill','_Km/1','pow_182/1');
  add_block('simulink/Math Operations/Math Function','ckt_gentoggle_8_odeIdeal/library/ihill/pow_185');
  set_param('ckt_gentoggle_8_odeIdeal/library/ihill/pow_185','Function','pow');
  set_param('ckt_gentoggle_8_odeIdeal/library/ihill/pow_185','position',[716,513,766,533]);
  add_line('ckt_gentoggle_8_odeIdeal/library/ihill','_n/1','pow_185/2');
  add_line('ckt_gentoggle_8_odeIdeal/library/ihill','_S/1','pow_185/1');
  add_block('simulink/Math Operations/Math Function','ckt_gentoggle_8_odeIdeal/library/ihill/pow_188');
  set_param('ckt_gentoggle_8_odeIdeal/library/ihill/pow_188','Function','pow');
  set_param('ckt_gentoggle_8_odeIdeal/library/ihill/pow_188','position',[255,64,305,84]);
  add_line('ckt_gentoggle_8_odeIdeal/library/ihill','_n/1','pow_188/2');
  add_line('ckt_gentoggle_8_odeIdeal/library/ihill','_Km/1','pow_188/1');
  add_block('simulink/Math Operations/Sum','ckt_gentoggle_8_odeIdeal/library/ihill/sub_191');
  set_param('ckt_gentoggle_8_odeIdeal/library/ihill/sub_191','Inputs','++');
  set_param('ckt_gentoggle_8_odeIdeal/library/ihill/sub_191','position',[394,301,444,321]);
  add_line('ckt_gentoggle_8_odeIdeal/library/ihill','pow_185/1','sub_191/1');
  add_line('ckt_gentoggle_8_odeIdeal/library/ihill','pow_188/1','sub_191/2');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_8_odeIdeal/library/ihill/div_194');
  set_param('ckt_gentoggle_8_odeIdeal/library/ihill/div_194','Inputs','*/');
  set_param('ckt_gentoggle_8_odeIdeal/library/ihill/div_194','position',[569,84,619,104]);
  add_line('ckt_gentoggle_8_odeIdeal/library/ihill','pow_182/1','div_194/1');
  add_line('ckt_gentoggle_8_odeIdeal/library/ihill','sub_191/1','div_194/2');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_8_odeIdeal/library/ihill/mul_197');
  set_param('ckt_gentoggle_8_odeIdeal/library/ihill/mul_197','Inputs','**');
  set_param('ckt_gentoggle_8_odeIdeal/library/ihill/mul_197','position',[473,952,523,972]);
  add_line('ckt_gentoggle_8_odeIdeal/library/ihill','_Vmax/1','mul_197/1');
  add_line('ckt_gentoggle_8_odeIdeal/library/ihill','div_194/1','mul_197/2');
  add_line('ckt_gentoggle_8_odeIdeal/library/ihill','mul_197/1','_REP/1');
  %
  add_block('simulink/Ports & Subsystems/Subsystem','ckt_gentoggle_8_odeIdeal/library/itov');
  set_param('ckt_gentoggle_8_odeIdeal/library/itov','position',[675,413,725,433]);
  delete_line('ckt_gentoggle_8_odeIdeal/library/itov','In1/1','Out1/1');
  delete_block('ckt_gentoggle_8_odeIdeal/library/itov/In1');
  delete_block('ckt_gentoggle_8_odeIdeal/library/itov/Out1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_8_odeIdeal/library/itov/X');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_odeIdeal/library/itov/_X');
  set_param('ckt_gentoggle_8_odeIdeal/library/itov/X','position',[904,676,954,696]);
  add_line('ckt_gentoggle_8_odeIdeal/library/itov','X/1','_X/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_8_odeIdeal/library/itov/K');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_odeIdeal/library/itov/_K');
  set_param('ckt_gentoggle_8_odeIdeal/library/itov/K','position',[623,675,673,695]);
  add_line('ckt_gentoggle_8_odeIdeal/library/itov','K/1','_K/1');
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_8_odeIdeal/library/itov/Y');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_odeIdeal/library/itov/_Y');
  add_line('ckt_gentoggle_8_odeIdeal/library/itov','_Y/1','Y/1');
  set_param('ckt_gentoggle_8_odeIdeal/library/itov/Y','position',[215,936,265,956]);
  add_block('simulink/Math Operations/Product','ckt_gentoggle_8_odeIdeal/library/itov/mul_215');
  set_param('ckt_gentoggle_8_odeIdeal/library/itov/mul_215','Inputs','**');
  set_param('ckt_gentoggle_8_odeIdeal/library/itov/mul_215','position',[846,688,896,708]);
  add_line('ckt_gentoggle_8_odeIdeal/library/itov','_K/1','mul_215/1');
  add_line('ckt_gentoggle_8_odeIdeal/library/itov','_X/1','mul_215/2');
  add_line('ckt_gentoggle_8_odeIdeal/library/itov','mul_215/1','_Y/1');
  %
  add_block('simulink/Ports & Subsystems/Subsystem','ckt_gentoggle_8_odeIdeal/library/output.I');
  set_param('ckt_gentoggle_8_odeIdeal/library/output.I','position',[168,331,218,351]);
  delete_line('ckt_gentoggle_8_odeIdeal/library/output.I','In1/1','Out1/1');
  delete_block('ckt_gentoggle_8_odeIdeal/library/output.I/In1');
  delete_block('ckt_gentoggle_8_odeIdeal/library/output.I/Out1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_8_odeIdeal/library/output.I/X');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_odeIdeal/library/output.I/_X');
  set_param('ckt_gentoggle_8_odeIdeal/library/output.I/X','position',[463,246,513,266]);
  add_line('ckt_gentoggle_8_odeIdeal/library/output.I','X/1','_X/1');
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_8_odeIdeal/library/output.I/O');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_odeIdeal/library/output.I/_O');
  add_line('ckt_gentoggle_8_odeIdeal/library/output.I','_O/1','O/1');
  set_param('ckt_gentoggle_8_odeIdeal/library/output.I/O','position',[244,50,294,70]);
  add_line('ckt_gentoggle_8_odeIdeal/library/output.I','_X/1','_O/1');
  %
  add_block('simulink/Ports & Subsystems/Subsystem','ckt_gentoggle_8_odeIdeal/library/output.V');
  set_param('ckt_gentoggle_8_odeIdeal/library/output.V','position',[714,947,764,967]);
  delete_line('ckt_gentoggle_8_odeIdeal/library/output.V','In1/1','Out1/1');
  delete_block('ckt_gentoggle_8_odeIdeal/library/output.V/In1');
  delete_block('ckt_gentoggle_8_odeIdeal/library/output.V/Out1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_8_odeIdeal/library/output.V/X');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_odeIdeal/library/output.V/_X');
  set_param('ckt_gentoggle_8_odeIdeal/library/output.V/X','position',[576,80,626,100]);
  add_line('ckt_gentoggle_8_odeIdeal/library/output.V','X/1','_X/1');
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_8_odeIdeal/library/output.V/O');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_odeIdeal/library/output.V/_O');
  add_line('ckt_gentoggle_8_odeIdeal/library/output.V','_O/1','O/1');
  set_param('ckt_gentoggle_8_odeIdeal/library/output.V/O','position',[363,140,413,160]);
  add_line('ckt_gentoggle_8_odeIdeal/library/output.V','_X/1','_O/1');
  %
  add_block('simulink/Ports & Subsystems/Subsystem','ckt_gentoggle_8_odeIdeal/library/input.V');
  set_param('ckt_gentoggle_8_odeIdeal/library/input.V','position',[979,649,1029,669]);
  delete_line('ckt_gentoggle_8_odeIdeal/library/input.V','In1/1','Out1/1');
  delete_block('ckt_gentoggle_8_odeIdeal/library/input.V/In1');
  delete_block('ckt_gentoggle_8_odeIdeal/library/input.V/Out1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_8_odeIdeal/library/input.V/X');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_odeIdeal/library/input.V/_X');
  set_param('ckt_gentoggle_8_odeIdeal/library/input.V/X','position',[353,634,403,654]);
  add_block('simulink/Discontinuities/Quantizer','ckt_gentoggle_8_odeIdeal/library/input.V/smp_244');
  set_param('ckt_gentoggle_8_odeIdeal/library/input.V/smp_244','QuantizationInterval','1e-05');
  set_param('ckt_gentoggle_8_odeIdeal/library/input.V/smp_244','position',[229,103,279,123]);
  add_line('ckt_gentoggle_8_odeIdeal/library/input.V','X/1','smp_244/1');
  add_line('ckt_gentoggle_8_odeIdeal/library/input.V','smp_244/1','_X/1');
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_8_odeIdeal/library/input.V/O');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_odeIdeal/library/input.V/_O');
  add_line('ckt_gentoggle_8_odeIdeal/library/input.V','_O/1','O/1');
  set_param('ckt_gentoggle_8_odeIdeal/library/input.V/O','position',[209,153,259,173]);
  add_line('ckt_gentoggle_8_odeIdeal/library/input.V','_X/1','_O/1');
  %
  add_block('simulink/Ports & Subsystems/Subsystem','ckt_gentoggle_8_odeIdeal/library/copy.V');
  set_param('ckt_gentoggle_8_odeIdeal/library/copy.V','position',[399,31,449,51]);
  delete_line('ckt_gentoggle_8_odeIdeal/library/copy.V','In1/1','Out1/1');
  delete_block('ckt_gentoggle_8_odeIdeal/library/copy.V/In1');
  delete_block('ckt_gentoggle_8_odeIdeal/library/copy.V/Out1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_8_odeIdeal/library/copy.V/X');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_odeIdeal/library/copy.V/_X');
  set_param('ckt_gentoggle_8_odeIdeal/library/copy.V/X','position',[383,799,433,819]);
  add_line('ckt_gentoggle_8_odeIdeal/library/copy.V','X/1','_X/1');
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_8_odeIdeal/library/copy.V/Y');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_odeIdeal/library/copy.V/_Y');
  add_line('ckt_gentoggle_8_odeIdeal/library/copy.V','_Y/1','Y/1');
  set_param('ckt_gentoggle_8_odeIdeal/library/copy.V/Y','position',[761,241,811,261]);
  add_line('ckt_gentoggle_8_odeIdeal/library/copy.V','_X/1','_Y/1');
  %
  add_block('simulink/Ports & Subsystems/Subsystem','ckt_gentoggle_8_odeIdeal/library/vtoi');
  set_param('ckt_gentoggle_8_odeIdeal/library/vtoi','position',[844,848,894,868]);
  delete_line('ckt_gentoggle_8_odeIdeal/library/vtoi','In1/1','Out1/1');
  delete_block('ckt_gentoggle_8_odeIdeal/library/vtoi/In1');
  delete_block('ckt_gentoggle_8_odeIdeal/library/vtoi/Out1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_8_odeIdeal/library/vtoi/X');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_odeIdeal/library/vtoi/_X');
  set_param('ckt_gentoggle_8_odeIdeal/library/vtoi/X','position',[193,800,243,820]);
  add_line('ckt_gentoggle_8_odeIdeal/library/vtoi','X/1','_X/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_8_odeIdeal/library/vtoi/K');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_odeIdeal/library/vtoi/_K');
  set_param('ckt_gentoggle_8_odeIdeal/library/vtoi/K','position',[789,197,839,217]);
  add_line('ckt_gentoggle_8_odeIdeal/library/vtoi','K/1','_K/1');
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_8_odeIdeal/library/vtoi/Y');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_odeIdeal/library/vtoi/_Y');
  add_line('ckt_gentoggle_8_odeIdeal/library/vtoi','_Y/1','Y/1');
  set_param('ckt_gentoggle_8_odeIdeal/library/vtoi/Y','position',[281,114,331,134]);
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_odeIdeal/library/vtoi/const_275');
  set_param('ckt_gentoggle_8_odeIdeal/library/vtoi/const_275','Value','1.');
  set_param('ckt_gentoggle_8_odeIdeal/library/vtoi/const_275','position',[754,945,804,965]);
  add_block('simulink/Math Operations/Product','ckt_gentoggle_8_odeIdeal/library/vtoi/div_277');
  set_param('ckt_gentoggle_8_odeIdeal/library/vtoi/div_277','Inputs','*/');
  set_param('ckt_gentoggle_8_odeIdeal/library/vtoi/div_277','position',[207,963,257,983]);
  add_line('ckt_gentoggle_8_odeIdeal/library/vtoi','const_275/1','div_277/1');
  add_line('ckt_gentoggle_8_odeIdeal/library/vtoi','_K/1','div_277/2');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_8_odeIdeal/library/vtoi/mul_280');
  set_param('ckt_gentoggle_8_odeIdeal/library/vtoi/mul_280','Inputs','**');
  set_param('ckt_gentoggle_8_odeIdeal/library/vtoi/mul_280','position',[386,963,436,983]);
  add_line('ckt_gentoggle_8_odeIdeal/library/vtoi','div_277/1','mul_280/1');
  add_line('ckt_gentoggle_8_odeIdeal/library/vtoi','_X/1','mul_280/2');
  add_line('ckt_gentoggle_8_odeIdeal/library/vtoi','mul_280/1','_Y/1');
  %
  add_block('simulink/Ports & Subsystems/Subsystem','ckt_gentoggle_8_odeIdeal/library/vadd');
  set_param('ckt_gentoggle_8_odeIdeal/library/vadd','position',[223,963,273,983]);
  delete_line('ckt_gentoggle_8_odeIdeal/library/vadd','In1/1','Out1/1');
  delete_block('ckt_gentoggle_8_odeIdeal/library/vadd/In1');
  delete_block('ckt_gentoggle_8_odeIdeal/library/vadd/Out1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_8_odeIdeal/library/vadd/OUT2_0');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_odeIdeal/library/vadd/_OUT2_0');
  set_param('ckt_gentoggle_8_odeIdeal/library/vadd/OUT2_0','position',[601,931,651,951]);
  add_line('ckt_gentoggle_8_odeIdeal/library/vadd','OUT2_0/1','_OUT2_0/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_8_odeIdeal/library/vadd/D');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_odeIdeal/library/vadd/_D');
  set_param('ckt_gentoggle_8_odeIdeal/library/vadd/D','position',[48,453,98,473]);
  add_line('ckt_gentoggle_8_odeIdeal/library/vadd','D/1','_D/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_8_odeIdeal/library/vadd/C');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_odeIdeal/library/vadd/_C');
  set_param('ckt_gentoggle_8_odeIdeal/library/vadd/C','position',[962,190,1012,210]);
  add_line('ckt_gentoggle_8_odeIdeal/library/vadd','C/1','_C/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_8_odeIdeal/library/vadd/A');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_odeIdeal/library/vadd/_A');
  set_param('ckt_gentoggle_8_odeIdeal/library/vadd/A','position',[847,123,897,143]);
  add_line('ckt_gentoggle_8_odeIdeal/library/vadd','A/1','_A/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_8_odeIdeal/library/vadd/B');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_odeIdeal/library/vadd/_B');
  set_param('ckt_gentoggle_8_odeIdeal/library/vadd/B','position',[982,829,1032,849]);
  add_line('ckt_gentoggle_8_odeIdeal/library/vadd','B/1','_B/1');
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_8_odeIdeal/library/vadd/OUT');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_odeIdeal/library/vadd/_OUT');
  add_line('ckt_gentoggle_8_odeIdeal/library/vadd','_OUT/1','OUT/1');
  set_param('ckt_gentoggle_8_odeIdeal/library/vadd/OUT','position',[491,773,541,793]);
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_8_odeIdeal/library/vadd/OUT2');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_odeIdeal/library/vadd/_OUT2');
  add_line('ckt_gentoggle_8_odeIdeal/library/vadd','_OUT2/1','OUT2/1');
  set_param('ckt_gentoggle_8_odeIdeal/library/vadd/OUT2','position',[761,230,811,250]);
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_8_odeIdeal/library/vadd/BSW');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_odeIdeal/library/vadd/_BSW');
  set_param('ckt_gentoggle_8_odeIdeal/library/vadd/BSW','position',[106,940,156,960]);
  add_line('ckt_gentoggle_8_odeIdeal/library/vadd','BSW/1','_BSW/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_8_odeIdeal/library/vadd/CSW');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_odeIdeal/library/vadd/_CSW');
  set_param('ckt_gentoggle_8_odeIdeal/library/vadd/CSW','position',[47,484,97,504]);
  add_line('ckt_gentoggle_8_odeIdeal/library/vadd','CSW/1','_CSW/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_8_odeIdeal/library/vadd/DSW');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_odeIdeal/library/vadd/_DSW');
  set_param('ckt_gentoggle_8_odeIdeal/library/vadd/DSW','position',[313,425,363,445]);
  add_line('ckt_gentoggle_8_odeIdeal/library/vadd','DSW/1','_DSW/1');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_8_odeIdeal/library/vadd/mul_332');
  set_param('ckt_gentoggle_8_odeIdeal/library/vadd/mul_332','Inputs','**');
  set_param('ckt_gentoggle_8_odeIdeal/library/vadd/mul_332','position',[195,662,245,682]);
  add_line('ckt_gentoggle_8_odeIdeal/library/vadd','_BSW/1','mul_332/1');
  add_line('ckt_gentoggle_8_odeIdeal/library/vadd','_B/1','mul_332/2');
  add_block('simulink/Math Operations/Sum','ckt_gentoggle_8_odeIdeal/library/vadd/sub_335');
  set_param('ckt_gentoggle_8_odeIdeal/library/vadd/sub_335','Inputs','++');
  set_param('ckt_gentoggle_8_odeIdeal/library/vadd/sub_335','position',[242,859,292,879]);
  add_line('ckt_gentoggle_8_odeIdeal/library/vadd','_A/1','sub_335/1');
  add_line('ckt_gentoggle_8_odeIdeal/library/vadd','mul_332/1','sub_335/2');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_8_odeIdeal/library/vadd/mul_338');
  set_param('ckt_gentoggle_8_odeIdeal/library/vadd/mul_338','Inputs','**');
  set_param('ckt_gentoggle_8_odeIdeal/library/vadd/mul_338','position',[791,299,841,319]);
  add_line('ckt_gentoggle_8_odeIdeal/library/vadd','_CSW/1','mul_338/1');
  add_line('ckt_gentoggle_8_odeIdeal/library/vadd','_C/1','mul_338/2');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_8_odeIdeal/library/vadd/mul_341');
  set_param('ckt_gentoggle_8_odeIdeal/library/vadd/mul_341','Inputs','**');
  set_param('ckt_gentoggle_8_odeIdeal/library/vadd/mul_341','position',[766,356,816,376]);
  add_line('ckt_gentoggle_8_odeIdeal/library/vadd','_DSW/1','mul_341/1');
  add_line('ckt_gentoggle_8_odeIdeal/library/vadd','_D/1','mul_341/2');
  add_block('simulink/Math Operations/Sum','ckt_gentoggle_8_odeIdeal/library/vadd/sum_344');
  set_param('ckt_gentoggle_8_odeIdeal/library/vadd/sum_344','Inputs','+--');
  set_param('ckt_gentoggle_8_odeIdeal/library/vadd/sum_344','position',[216,935,266,955]);
  add_line('ckt_gentoggle_8_odeIdeal/library/vadd','sub_335/1','sum_344/1');
  add_line('ckt_gentoggle_8_odeIdeal/library/vadd','mul_338/1','sum_344/2');
  add_line('ckt_gentoggle_8_odeIdeal/library/vadd','mul_341/1','sum_344/3');
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_odeIdeal/library/vadd/const_348');
  set_param('ckt_gentoggle_8_odeIdeal/library/vadd/const_348','Value','0.25');
  set_param('ckt_gentoggle_8_odeIdeal/library/vadd/const_348','position',[86,625,136,645]);
  add_block('simulink/Math Operations/Product','ckt_gentoggle_8_odeIdeal/library/vadd/mul_350');
  set_param('ckt_gentoggle_8_odeIdeal/library/vadd/mul_350','Inputs','**');
  set_param('ckt_gentoggle_8_odeIdeal/library/vadd/mul_350','position',[644,786,694,806]);
  add_line('ckt_gentoggle_8_odeIdeal/library/vadd','sum_344/1','mul_350/1');
  add_line('ckt_gentoggle_8_odeIdeal/library/vadd','const_348/1','mul_350/2');
  add_line('ckt_gentoggle_8_odeIdeal/library/vadd','mul_350/1','_OUT/1');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_8_odeIdeal/library/vadd/mul_353');
  set_param('ckt_gentoggle_8_odeIdeal/library/vadd/mul_353','Inputs','**');
  set_param('ckt_gentoggle_8_odeIdeal/library/vadd/mul_353','position',[176,601,226,621]);
  add_line('ckt_gentoggle_8_odeIdeal/library/vadd','_BSW/1','mul_353/1');
  add_line('ckt_gentoggle_8_odeIdeal/library/vadd','_B/1','mul_353/2');
  add_block('simulink/Math Operations/Sum','ckt_gentoggle_8_odeIdeal/library/vadd/sub_356');
  set_param('ckt_gentoggle_8_odeIdeal/library/vadd/sub_356','Inputs','++');
  set_param('ckt_gentoggle_8_odeIdeal/library/vadd/sub_356','position',[533,355,583,375]);
  add_line('ckt_gentoggle_8_odeIdeal/library/vadd','_A/1','sub_356/1');
  add_line('ckt_gentoggle_8_odeIdeal/library/vadd','mul_353/1','sub_356/2');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_8_odeIdeal/library/vadd/mul_359');
  set_param('ckt_gentoggle_8_odeIdeal/library/vadd/mul_359','Inputs','**');
  set_param('ckt_gentoggle_8_odeIdeal/library/vadd/mul_359','position',[677,609,727,629]);
  add_line('ckt_gentoggle_8_odeIdeal/library/vadd','_CSW/1','mul_359/1');
  add_line('ckt_gentoggle_8_odeIdeal/library/vadd','_C/1','mul_359/2');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_8_odeIdeal/library/vadd/mul_362');
  set_param('ckt_gentoggle_8_odeIdeal/library/vadd/mul_362','Inputs','***');
  set_param('ckt_gentoggle_8_odeIdeal/library/vadd/mul_362','position',[568,24,618,44]);
  add_line('ckt_gentoggle_8_odeIdeal/library/vadd','_DSW/1','mul_362/1');
  add_line('ckt_gentoggle_8_odeIdeal/library/vadd','_D/1','mul_362/2');
  add_line('ckt_gentoggle_8_odeIdeal/library/vadd','_OUT2/1','mul_362/3');
  add_block('simulink/Math Operations/Sum','ckt_gentoggle_8_odeIdeal/library/vadd/sum_366');
  set_param('ckt_gentoggle_8_odeIdeal/library/vadd/sum_366','Inputs','+--');
  set_param('ckt_gentoggle_8_odeIdeal/library/vadd/sum_366','position',[617,686,667,706]);
  add_line('ckt_gentoggle_8_odeIdeal/library/vadd','sub_356/1','sum_366/1');
  add_line('ckt_gentoggle_8_odeIdeal/library/vadd','mul_359/1','sum_366/2');
  add_line('ckt_gentoggle_8_odeIdeal/library/vadd','mul_362/1','sum_366/3');
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_odeIdeal/library/vadd/const_370');
  set_param('ckt_gentoggle_8_odeIdeal/library/vadd/const_370','Value','0.25');
  set_param('ckt_gentoggle_8_odeIdeal/library/vadd/const_370','position',[236,741,286,761]);
  add_block('simulink/Math Operations/Product','ckt_gentoggle_8_odeIdeal/library/vadd/mul_372');
  set_param('ckt_gentoggle_8_odeIdeal/library/vadd/mul_372','Inputs','**');
  set_param('ckt_gentoggle_8_odeIdeal/library/vadd/mul_372','position',[614,579,664,599]);
  add_line('ckt_gentoggle_8_odeIdeal/library/vadd','sum_366/1','mul_372/1');
  add_line('ckt_gentoggle_8_odeIdeal/library/vadd','const_370/1','mul_372/2');
  add_block('simulink/Continuous/Integrator','ckt_gentoggle_8_odeIdeal/library/vadd/int_375');
  set_param('ckt_gentoggle_8_odeIdeal/library/vadd/int_375','position',[541,804,591,824]);
  add_line('ckt_gentoggle_8_odeIdeal/library/vadd','mul_372/1','int_375/1');
  add_line('ckt_gentoggle_8_odeIdeal/library/vadd','int_375/1','_OUT2/1');
  %
  add_block('simulink/Ports & Subsystems/Subsystem','ckt_gentoggle_8_odeIdeal/library/copy.I');
  set_param('ckt_gentoggle_8_odeIdeal/library/copy.I','position',[807,709,857,729]);
  delete_line('ckt_gentoggle_8_odeIdeal/library/copy.I','In1/1','Out1/1');
  delete_block('ckt_gentoggle_8_odeIdeal/library/copy.I/In1');
  delete_block('ckt_gentoggle_8_odeIdeal/library/copy.I/Out1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_8_odeIdeal/library/copy.I/X');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_odeIdeal/library/copy.I/_X');
  set_param('ckt_gentoggle_8_odeIdeal/library/copy.I/X','position',[987,598,1037,618]);
  add_line('ckt_gentoggle_8_odeIdeal/library/copy.I','X/1','_X/1');
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_8_odeIdeal/library/copy.I/Y');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_odeIdeal/library/copy.I/_Y');
  add_line('ckt_gentoggle_8_odeIdeal/library/copy.I','_Y/1','Y/1');
  set_param('ckt_gentoggle_8_odeIdeal/library/copy.I/Y','position',[226,660,276,680]);
  add_line('ckt_gentoggle_8_odeIdeal/library/copy.I','_X/1','_Y/1');
  %
  add_block('simulink/Ports & Subsystems/Subsystem','ckt_gentoggle_8_odeIdeal/library/iadd');
  set_param('ckt_gentoggle_8_odeIdeal/library/iadd','position',[795,395,845,415]);
  delete_line('ckt_gentoggle_8_odeIdeal/library/iadd','In1/1','Out1/1');
  delete_block('ckt_gentoggle_8_odeIdeal/library/iadd/In1');
  delete_block('ckt_gentoggle_8_odeIdeal/library/iadd/Out1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_8_odeIdeal/library/iadd/D');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_odeIdeal/library/iadd/_D');
  set_param('ckt_gentoggle_8_odeIdeal/library/iadd/D','position',[116,826,166,846]);
  add_line('ckt_gentoggle_8_odeIdeal/library/iadd','D/1','_D/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_8_odeIdeal/library/iadd/C');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_odeIdeal/library/iadd/_C');
  set_param('ckt_gentoggle_8_odeIdeal/library/iadd/C','position',[919,171,969,191]);
  add_line('ckt_gentoggle_8_odeIdeal/library/iadd','C/1','_C/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_8_odeIdeal/library/iadd/A');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_odeIdeal/library/iadd/_A');
  set_param('ckt_gentoggle_8_odeIdeal/library/iadd/A','position',[784,117,834,137]);
  add_line('ckt_gentoggle_8_odeIdeal/library/iadd','A/1','_A/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_8_odeIdeal/library/iadd/B');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_odeIdeal/library/iadd/_B');
  set_param('ckt_gentoggle_8_odeIdeal/library/iadd/B','position',[371,773,421,793]);
  add_line('ckt_gentoggle_8_odeIdeal/library/iadd','B/1','_B/1');
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_8_odeIdeal/library/iadd/OUT');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_odeIdeal/library/iadd/_OUT');
  add_line('ckt_gentoggle_8_odeIdeal/library/iadd','_OUT/1','OUT/1');
  set_param('ckt_gentoggle_8_odeIdeal/library/iadd/OUT','position',[769,642,819,662]);
  add_block('simulink/Math Operations/Sum','ckt_gentoggle_8_odeIdeal/library/iadd/sub_412');
  set_param('ckt_gentoggle_8_odeIdeal/library/iadd/sub_412','Inputs','++');
  set_param('ckt_gentoggle_8_odeIdeal/library/iadd/sub_412','position',[716,468,766,488]);
  add_line('ckt_gentoggle_8_odeIdeal/library/iadd','_A/1','sub_412/1');
  add_line('ckt_gentoggle_8_odeIdeal/library/iadd','_B/1','sub_412/2');
  add_block('simulink/Math Operations/Sum','ckt_gentoggle_8_odeIdeal/library/iadd/sum_415');
  set_param('ckt_gentoggle_8_odeIdeal/library/iadd/sum_415','Inputs','+--');
  set_param('ckt_gentoggle_8_odeIdeal/library/iadd/sum_415','position',[673,947,723,967]);
  add_line('ckt_gentoggle_8_odeIdeal/library/iadd','sub_412/1','sum_415/1');
  add_line('ckt_gentoggle_8_odeIdeal/library/iadd','_C/1','sum_415/2');
  add_line('ckt_gentoggle_8_odeIdeal/library/iadd','_D/1','sum_415/3');
  add_line('ckt_gentoggle_8_odeIdeal/library/iadd','sum_415/1','_OUT/1');
  %
  add_block('simulink/Ports & Subsystems/Subsystem','ckt_gentoggle_8_odeIdeal/library/input.I');
  set_param('ckt_gentoggle_8_odeIdeal/library/input.I','position',[317,614,367,634]);
  delete_line('ckt_gentoggle_8_odeIdeal/library/input.I','In1/1','Out1/1');
  delete_block('ckt_gentoggle_8_odeIdeal/library/input.I/In1');
  delete_block('ckt_gentoggle_8_odeIdeal/library/input.I/Out1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_8_odeIdeal/library/input.I/X');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_odeIdeal/library/input.I/_X');
  set_param('ckt_gentoggle_8_odeIdeal/library/input.I/X','position',[400,93,450,113]);
  add_block('simulink/Discontinuities/Quantizer','ckt_gentoggle_8_odeIdeal/library/input.I/smp_425');
  set_param('ckt_gentoggle_8_odeIdeal/library/input.I/smp_425','QuantizationInterval','1e-05');
  set_param('ckt_gentoggle_8_odeIdeal/library/input.I/smp_425','position',[452,427,502,447]);
  add_line('ckt_gentoggle_8_odeIdeal/library/input.I','X/1','smp_425/1');
  add_line('ckt_gentoggle_8_odeIdeal/library/input.I','smp_425/1','_X/1');
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_8_odeIdeal/library/input.I/O');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_odeIdeal/library/input.I/_O');
  add_line('ckt_gentoggle_8_odeIdeal/library/input.I','_O/1','O/1');
  set_param('ckt_gentoggle_8_odeIdeal/library/input.I/O','position',[101,841,151,861]);
  add_line('ckt_gentoggle_8_odeIdeal/library/input.I','_X/1','_O/1');
  %
  add_block('simulink/Ports & Subsystems/Subsystem','ckt_gentoggle_8_odeIdeal/library/igenebind');
  set_param('ckt_gentoggle_8_odeIdeal/library/igenebind','position',[67,503,117,523]);
  delete_line('ckt_gentoggle_8_odeIdeal/library/igenebind','In1/1','Out1/1');
  delete_block('ckt_gentoggle_8_odeIdeal/library/igenebind/In1');
  delete_block('ckt_gentoggle_8_odeIdeal/library/igenebind/Out1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_8_odeIdeal/library/igenebind/TF');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_odeIdeal/library/igenebind/_TF');
  set_param('ckt_gentoggle_8_odeIdeal/library/igenebind/TF','position',[704,569,754,589]);
  add_line('ckt_gentoggle_8_odeIdeal/library/igenebind','TF/1','_TF/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_8_odeIdeal/library/igenebind/K');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_odeIdeal/library/igenebind/_K');
  set_param('ckt_gentoggle_8_odeIdeal/library/igenebind/K','position',[289,368,339,388]);
  add_line('ckt_gentoggle_8_odeIdeal/library/igenebind','K/1','_K/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_8_odeIdeal/library/igenebind/Vmax');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_odeIdeal/library/igenebind/_Vmax');
  set_param('ckt_gentoggle_8_odeIdeal/library/igenebind/Vmax','position',[370,491,420,511]);
  add_line('ckt_gentoggle_8_odeIdeal/library/igenebind','Vmax/1','_Vmax/1');
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_8_odeIdeal/library/igenebind/GE');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_odeIdeal/library/igenebind/_GE');
  add_line('ckt_gentoggle_8_odeIdeal/library/igenebind','_GE/1','GE/1');
  set_param('ckt_gentoggle_8_odeIdeal/library/igenebind/GE','position',[428,442,478,462]);
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_odeIdeal/library/igenebind/const_451');
  set_param('ckt_gentoggle_8_odeIdeal/library/igenebind/const_451','Value','1.');
  set_param('ckt_gentoggle_8_odeIdeal/library/igenebind/const_451','position',[695,292,745,312]);
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_odeIdeal/library/igenebind/const_453');
  set_param('ckt_gentoggle_8_odeIdeal/library/igenebind/const_453','Value','1.');
  set_param('ckt_gentoggle_8_odeIdeal/library/igenebind/const_453','position',[898,428,948,448]);
  add_block('simulink/Math Operations/Product','ckt_gentoggle_8_odeIdeal/library/igenebind/mul_455');
  set_param('ckt_gentoggle_8_odeIdeal/library/igenebind/mul_455','Inputs','**');
  set_param('ckt_gentoggle_8_odeIdeal/library/igenebind/mul_455','position',[955,646,1005,666]);
  add_line('ckt_gentoggle_8_odeIdeal/library/igenebind','_K/1','mul_455/1');
  add_line('ckt_gentoggle_8_odeIdeal/library/igenebind','_TF/1','mul_455/2');
  add_block('simulink/Math Operations/Sum','ckt_gentoggle_8_odeIdeal/library/igenebind/sub_458');
  set_param('ckt_gentoggle_8_odeIdeal/library/igenebind/sub_458','Inputs','++');
  set_param('ckt_gentoggle_8_odeIdeal/library/igenebind/sub_458','position',[495,958,545,978]);
  add_line('ckt_gentoggle_8_odeIdeal/library/igenebind','const_453/1','sub_458/1');
  add_line('ckt_gentoggle_8_odeIdeal/library/igenebind','mul_455/1','sub_458/2');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_8_odeIdeal/library/igenebind/div_461');
  set_param('ckt_gentoggle_8_odeIdeal/library/igenebind/div_461','Inputs','*/');
  set_param('ckt_gentoggle_8_odeIdeal/library/igenebind/div_461','position',[209,576,259,596]);
  add_line('ckt_gentoggle_8_odeIdeal/library/igenebind','const_451/1','div_461/1');
  add_line('ckt_gentoggle_8_odeIdeal/library/igenebind','sub_458/1','div_461/2');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_8_odeIdeal/library/igenebind/mul_464');
  set_param('ckt_gentoggle_8_odeIdeal/library/igenebind/mul_464','Inputs','**');
  set_param('ckt_gentoggle_8_odeIdeal/library/igenebind/mul_464','position',[530,121,580,141]);
  add_line('ckt_gentoggle_8_odeIdeal/library/igenebind','_Vmax/1','mul_464/1');
  add_line('ckt_gentoggle_8_odeIdeal/library/igenebind','div_461/1','mul_464/2');
  add_line('ckt_gentoggle_8_odeIdeal/library/igenebind','mul_464/1','_GE/1');
end
%
%
%
