%toplevel script
function main()
  preamble();
  build_comp_library();
  build_circuit();
end
%
%
%circuit build script
function build_circuit()
  add_block('simulink/Ports & Subsystems/Subsystem','ckt_gentoggle_8_sdeIdeal/circuit');
  set_param('ckt_gentoggle_8_sdeIdeal/circuit','position',[480,524,530,544]);
  delete_line('ckt_gentoggle_8_sdeIdeal/circuit','In1/1','Out1/1');
  delete_block('ckt_gentoggle_8_sdeIdeal/circuit/In1');
  delete_block('ckt_gentoggle_8_sdeIdeal/circuit/Out1');
  add_block('ckt_gentoggle_8_sdeIdeal/library/vgain','ckt_gentoggle_8_sdeIdeal/circuit/vgain[0]');
  add_block('ckt_gentoggle_8_sdeIdeal/library/switch','ckt_gentoggle_8_sdeIdeal/circuit/switch[6]');
  add_block('ckt_gentoggle_8_sdeIdeal/library/input.I','ckt_gentoggle_8_sdeIdeal/circuit/input.I[2]');
  add_block('ckt_gentoggle_8_sdeIdeal/library/input.I','ckt_gentoggle_8_sdeIdeal/circuit/input.I[0]');
  add_block('ckt_gentoggle_8_sdeIdeal/library/input.I','ckt_gentoggle_8_sdeIdeal/circuit/input.I[15]');
  add_block('ckt_gentoggle_8_sdeIdeal/library/input.I','ckt_gentoggle_8_sdeIdeal/circuit/input.I[14]');
  add_block('ckt_gentoggle_8_sdeIdeal/library/input.I','ckt_gentoggle_8_sdeIdeal/circuit/input.I[16]');
  add_block('ckt_gentoggle_8_sdeIdeal/library/input.I','ckt_gentoggle_8_sdeIdeal/circuit/input.I[3]');
  add_block('ckt_gentoggle_8_sdeIdeal/library/input.I','ckt_gentoggle_8_sdeIdeal/circuit/input.I[4]');
  add_block('ckt_gentoggle_8_sdeIdeal/library/input.I','ckt_gentoggle_8_sdeIdeal/circuit/input.I[5]');
  add_block('ckt_gentoggle_8_sdeIdeal/library/input.I','ckt_gentoggle_8_sdeIdeal/circuit/input.I[1]');
  add_block('ckt_gentoggle_8_sdeIdeal/library/output.V','ckt_gentoggle_8_sdeIdeal/circuit/output.V[0]');
  add_block('ckt_gentoggle_8_sdeIdeal/library/output.V','ckt_gentoggle_8_sdeIdeal/circuit/output.V[1]');
  add_block('ckt_gentoggle_8_sdeIdeal/library/vadd','ckt_gentoggle_8_sdeIdeal/circuit/vadd[5]');
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_sdeIdeal/circuit/const_686');
  set_param('ckt_gentoggle_8_sdeIdeal/circuit/const_686','Value','1.');
  set_param('ckt_gentoggle_8_sdeIdeal/circuit/const_686','position',[945,396,995,416]);
  add_line('ckt_gentoggle_8_sdeIdeal/circuit','const_686/1','vadd[5]/6');
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_sdeIdeal/circuit/const_688');
  set_param('ckt_gentoggle_8_sdeIdeal/circuit/const_688','Value','1.');
  set_param('ckt_gentoggle_8_sdeIdeal/circuit/const_688','position',[322,768,372,788]);
  add_line('ckt_gentoggle_8_sdeIdeal/circuit','const_688/1','vadd[5]/7');
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_sdeIdeal/circuit/const_690');
  set_param('ckt_gentoggle_8_sdeIdeal/circuit/const_690','Value','1.');
  set_param('ckt_gentoggle_8_sdeIdeal/circuit/const_690','position',[202,849,252,869]);
  add_line('ckt_gentoggle_8_sdeIdeal/circuit','const_690/1','vadd[5]/8');
  set_param('ckt_gentoggle_8_sdeIdeal/circuit/vadd[5]/int_519','InitialCondition','0.');
  add_block('ckt_gentoggle_8_sdeIdeal/library/vadd','ckt_gentoggle_8_sdeIdeal/circuit/vadd[1]');
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_sdeIdeal/circuit/const_692');
  set_param('ckt_gentoggle_8_sdeIdeal/circuit/const_692','Value','1.');
  set_param('ckt_gentoggle_8_sdeIdeal/circuit/const_692','position',[531,250,581,270]);
  add_line('ckt_gentoggle_8_sdeIdeal/circuit','const_692/1','vadd[1]/6');
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_sdeIdeal/circuit/const_694');
  set_param('ckt_gentoggle_8_sdeIdeal/circuit/const_694','Value','1.');
  set_param('ckt_gentoggle_8_sdeIdeal/circuit/const_694','position',[665,216,715,236]);
  add_line('ckt_gentoggle_8_sdeIdeal/circuit','const_694/1','vadd[1]/7');
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_sdeIdeal/circuit/const_696');
  set_param('ckt_gentoggle_8_sdeIdeal/circuit/const_696','Value','1.');
  set_param('ckt_gentoggle_8_sdeIdeal/circuit/const_696','position',[528,400,578,420]);
  add_line('ckt_gentoggle_8_sdeIdeal/circuit','const_696/1','vadd[1]/8');
  set_param('ckt_gentoggle_8_sdeIdeal/circuit/vadd[1]/int_519','InitialCondition','0.');
  add_block('ckt_gentoggle_8_sdeIdeal/library/ihill','ckt_gentoggle_8_sdeIdeal/circuit/ihill[2]');
  add_block('ckt_gentoggle_8_sdeIdeal/library/ihill','ckt_gentoggle_8_sdeIdeal/circuit/ihill[3]');
  add_block('ckt_gentoggle_8_sdeIdeal/library/vtoi','ckt_gentoggle_8_sdeIdeal/circuit/vtoi[0]');
  add_block('ckt_gentoggle_8_sdeIdeal/library/input.V','ckt_gentoggle_8_sdeIdeal/circuit/input.V[2]');
  add_block('ckt_gentoggle_8_sdeIdeal/library/input.V','ckt_gentoggle_8_sdeIdeal/circuit/input.V[8]');
  add_block('ckt_gentoggle_8_sdeIdeal/library/input.V','ckt_gentoggle_8_sdeIdeal/circuit/input.V[7]');
  add_block('ckt_gentoggle_8_sdeIdeal/library/input.V','ckt_gentoggle_8_sdeIdeal/circuit/input.V[13]');
  add_block('ckt_gentoggle_8_sdeIdeal/library/input.V','ckt_gentoggle_8_sdeIdeal/circuit/input.V[12]');
  add_block('ckt_gentoggle_8_sdeIdeal/library/input.V','ckt_gentoggle_8_sdeIdeal/circuit/input.V[9]');
  add_block('ckt_gentoggle_8_sdeIdeal/library/input.V','ckt_gentoggle_8_sdeIdeal/circuit/input.V[0]');
  add_block('ckt_gentoggle_8_sdeIdeal/library/input.V','ckt_gentoggle_8_sdeIdeal/circuit/input.V[11]');
  add_block('ckt_gentoggle_8_sdeIdeal/library/input.V','ckt_gentoggle_8_sdeIdeal/circuit/input.V[10]');
  add_block('ckt_gentoggle_8_sdeIdeal/library/input.V','ckt_gentoggle_8_sdeIdeal/circuit/input.V[6]');
  add_block('ckt_gentoggle_8_sdeIdeal/library/input.V','ckt_gentoggle_8_sdeIdeal/circuit/input.V[16]');
  add_block('ckt_gentoggle_8_sdeIdeal/library/input.V','ckt_gentoggle_8_sdeIdeal/circuit/input.V[3]');
  add_block('ckt_gentoggle_8_sdeIdeal/library/input.V','ckt_gentoggle_8_sdeIdeal/circuit/input.V[4]');
  add_block('ckt_gentoggle_8_sdeIdeal/library/input.V','ckt_gentoggle_8_sdeIdeal/circuit/input.V[5]');
  add_block('ckt_gentoggle_8_sdeIdeal/library/input.V','ckt_gentoggle_8_sdeIdeal/circuit/input.V[1]');
  add_block('ckt_gentoggle_8_sdeIdeal/library/input.V','ckt_gentoggle_8_sdeIdeal/circuit/input.V[17]');
  add_block('ckt_gentoggle_8_sdeIdeal/library/itov','ckt_gentoggle_8_sdeIdeal/circuit/itov[5]');
  add_block('ckt_gentoggle_8_sdeIdeal/library/itov','ckt_gentoggle_8_sdeIdeal/circuit/itov[4]');
  add_block('ckt_gentoggle_8_sdeIdeal/library/iadd','ckt_gentoggle_8_sdeIdeal/circuit/iadd[0]');
  add_line('ckt_gentoggle_8_sdeIdeal/circuit','input.V[17]/1','vtoi[0]/2');
  add_line('ckt_gentoggle_8_sdeIdeal/circuit','vadd[1]/2','output.V[0]/1');
  add_line('ckt_gentoggle_8_sdeIdeal/circuit','vadd[1]/2','vtoi[0]/1');
  add_line('ckt_gentoggle_8_sdeIdeal/circuit','input.I[0]/1','switch[6]/2');
  add_line('ckt_gentoggle_8_sdeIdeal/circuit','input.V[9]/1','vadd[5]/2');
  add_line('ckt_gentoggle_8_sdeIdeal/circuit','input.I[16]/1','iadd[0]/3');
  add_line('ckt_gentoggle_8_sdeIdeal/circuit','input.I[4]/1','ihill[2]/4');
  add_line('ckt_gentoggle_8_sdeIdeal/circuit','input.V[13]/1','vgain[0]/1');
  add_line('ckt_gentoggle_8_sdeIdeal/circuit','input.I[3]/1','ihill[3]/4');
  add_line('ckt_gentoggle_8_sdeIdeal/circuit','input.I[5]/1','switch[6]/3');
  add_line('ckt_gentoggle_8_sdeIdeal/circuit','vtoi[0]/1','ihill[3]/2');
  add_line('ckt_gentoggle_8_sdeIdeal/circuit','ihill[3]/2','itov[4]/1');
  add_line('ckt_gentoggle_8_sdeIdeal/circuit','input.I[14]/1','iadd[0]/2');
  add_line('ckt_gentoggle_8_sdeIdeal/circuit','itov[5]/1','vgain[0]/3');
  add_line('ckt_gentoggle_8_sdeIdeal/circuit','input.V[11]/1','switch[6]/1');
  add_line('ckt_gentoggle_8_sdeIdeal/circuit','input.V[8]/1','vadd[1]/2');
  add_line('ckt_gentoggle_8_sdeIdeal/circuit','input.V[12]/1','ihill[2]/1');
  add_line('ckt_gentoggle_8_sdeIdeal/circuit','input.I[2]/1','ihill[2]/3');
  add_line('ckt_gentoggle_8_sdeIdeal/circuit','ihill[2]/2','itov[5]/1');
  add_line('ckt_gentoggle_8_sdeIdeal/circuit','input.V[2]/1','vadd[1]/4');
  add_line('ckt_gentoggle_8_sdeIdeal/circuit','input.V[3]/1','vadd[1]/3');
  add_line('ckt_gentoggle_8_sdeIdeal/circuit','vadd[5]/2','output.V[1]/1');
  add_line('ckt_gentoggle_8_sdeIdeal/circuit','vadd[5]/2','switch[6]/4');
  add_line('ckt_gentoggle_8_sdeIdeal/circuit','switch[6]/1','iadd[0]/4');
  add_line('ckt_gentoggle_8_sdeIdeal/circuit','iadd[0]/1','ihill[2]/2');
  add_line('ckt_gentoggle_8_sdeIdeal/circuit','input.I[15]/1','iadd[0]/1');
  add_line('ckt_gentoggle_8_sdeIdeal/circuit','input.I[1]/1','ihill[3]/3');
  add_line('ckt_gentoggle_8_sdeIdeal/circuit','input.V[1]/1','vgain[0]/2');
  add_line('ckt_gentoggle_8_sdeIdeal/circuit','vgain[0]/1','vadd[1]/5');
  add_line('ckt_gentoggle_8_sdeIdeal/circuit','input.V[7]/1','vadd[1]/1');
  add_line('ckt_gentoggle_8_sdeIdeal/circuit','input.V[0]/1','ihill[3]/1');
  add_line('ckt_gentoggle_8_sdeIdeal/circuit','input.V[10]/1','itov[4]/2');
  add_line('ckt_gentoggle_8_sdeIdeal/circuit','input.V[16]/1','itov[5]/2');
  add_line('ckt_gentoggle_8_sdeIdeal/circuit','itov[4]/1','vadd[5]/5');
  add_line('ckt_gentoggle_8_sdeIdeal/circuit','input.V[4]/1','vadd[5]/3');
  add_line('ckt_gentoggle_8_sdeIdeal/circuit','input.V[5]/1','vadd[5]/4');
  add_line('ckt_gentoggle_8_sdeIdeal/circuit','input.V[6]/1','vadd[5]/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_8_sdeIdeal/circuit/input.I[0]_in');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_sdeIdeal/circuit/_input.I[0]_in');
  set_param('ckt_gentoggle_8_sdeIdeal/circuit/input.I[0]_in','position',[862,867,912,887]);
  add_line('ckt_gentoggle_8_sdeIdeal/circuit','input.I[0]_in/1','_input.I[0]_in/1');
  add_line('ckt_gentoggle_8_sdeIdeal/circuit','_input.I[0]_in/1','input.I[0]/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_8_sdeIdeal/circuit/input.I[1]_in');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_sdeIdeal/circuit/_input.I[1]_in');
  set_param('ckt_gentoggle_8_sdeIdeal/circuit/input.I[1]_in','position',[531,589,581,609]);
  add_line('ckt_gentoggle_8_sdeIdeal/circuit','input.I[1]_in/1','_input.I[1]_in/1');
  add_line('ckt_gentoggle_8_sdeIdeal/circuit','_input.I[1]_in/1','input.I[1]/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_8_sdeIdeal/circuit/input.I[2]_in');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_sdeIdeal/circuit/_input.I[2]_in');
  set_param('ckt_gentoggle_8_sdeIdeal/circuit/input.I[2]_in','position',[800,24,850,44]);
  add_line('ckt_gentoggle_8_sdeIdeal/circuit','input.I[2]_in/1','_input.I[2]_in/1');
  add_line('ckt_gentoggle_8_sdeIdeal/circuit','_input.I[2]_in/1','input.I[2]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_sdeIdeal/circuit/const_713');
  set_param('ckt_gentoggle_8_sdeIdeal/circuit/const_713','Value','0.15625');
  set_param('ckt_gentoggle_8_sdeIdeal/circuit/const_713','position',[647,148,697,168]);
  add_line('ckt_gentoggle_8_sdeIdeal/circuit','const_713/1','input.I[3]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_sdeIdeal/circuit/const_715');
  set_param('ckt_gentoggle_8_sdeIdeal/circuit/const_715','Value','0.0156');
  set_param('ckt_gentoggle_8_sdeIdeal/circuit/const_715','position',[59,22,109,42]);
  add_line('ckt_gentoggle_8_sdeIdeal/circuit','const_715/1','input.I[4]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_sdeIdeal/circuit/const_717');
  set_param('ckt_gentoggle_8_sdeIdeal/circuit/const_717','Value','2.5');
  set_param('ckt_gentoggle_8_sdeIdeal/circuit/const_717','position',[502,315,552,335]);
  add_line('ckt_gentoggle_8_sdeIdeal/circuit','const_717/1','input.V[0]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_sdeIdeal/circuit/const_719');
  set_param('ckt_gentoggle_8_sdeIdeal/circuit/const_719','Value','0.125');
  set_param('ckt_gentoggle_8_sdeIdeal/circuit/const_719','position',[531,638,581,658]);
  add_line('ckt_gentoggle_8_sdeIdeal/circuit','const_719/1','input.V[1]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_sdeIdeal/circuit/const_721');
  set_param('ckt_gentoggle_8_sdeIdeal/circuit/const_721','Value','0.');
  set_param('ckt_gentoggle_8_sdeIdeal/circuit/const_721','position',[297,950,347,970]);
  add_line('ckt_gentoggle_8_sdeIdeal/circuit','const_721/1','input.I[14]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_sdeIdeal/circuit/const_723');
  set_param('ckt_gentoggle_8_sdeIdeal/circuit/const_723','Value','0.');
  set_param('ckt_gentoggle_8_sdeIdeal/circuit/const_723','position',[202,6,252,26]);
  add_line('ckt_gentoggle_8_sdeIdeal/circuit','const_723/1','input.I[15]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_sdeIdeal/circuit/const_725');
  set_param('ckt_gentoggle_8_sdeIdeal/circuit/const_725','Value','0.');
  set_param('ckt_gentoggle_8_sdeIdeal/circuit/const_725','position',[99,693,149,713]);
  add_line('ckt_gentoggle_8_sdeIdeal/circuit','const_725/1','input.I[16]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_sdeIdeal/circuit/const_727');
  set_param('ckt_gentoggle_8_sdeIdeal/circuit/const_727','Value','0.');
  set_param('ckt_gentoggle_8_sdeIdeal/circuit/const_727','position',[342,364,392,384]);
  add_line('ckt_gentoggle_8_sdeIdeal/circuit','const_727/1','input.V[2]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_sdeIdeal/circuit/const_729');
  set_param('ckt_gentoggle_8_sdeIdeal/circuit/const_729','Value','0.');
  set_param('ckt_gentoggle_8_sdeIdeal/circuit/const_729','position',[796,209,846,229]);
  add_line('ckt_gentoggle_8_sdeIdeal/circuit','const_729/1','input.V[3]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_sdeIdeal/circuit/const_731');
  set_param('ckt_gentoggle_8_sdeIdeal/circuit/const_731','Value','0.');
  set_param('ckt_gentoggle_8_sdeIdeal/circuit/const_731','position',[641,181,691,201]);
  add_line('ckt_gentoggle_8_sdeIdeal/circuit','const_731/1','input.V[4]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_sdeIdeal/circuit/const_733');
  set_param('ckt_gentoggle_8_sdeIdeal/circuit/const_733','Value','0.');
  set_param('ckt_gentoggle_8_sdeIdeal/circuit/const_733','position',[177,987,227,1007]);
  add_line('ckt_gentoggle_8_sdeIdeal/circuit','const_733/1','input.V[5]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_sdeIdeal/circuit/const_735');
  set_param('ckt_gentoggle_8_sdeIdeal/circuit/const_735','Value','0.');
  set_param('ckt_gentoggle_8_sdeIdeal/circuit/const_735','position',[645,73,695,93]);
  add_line('ckt_gentoggle_8_sdeIdeal/circuit','const_735/1','input.V[6]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_sdeIdeal/circuit/const_737');
  set_param('ckt_gentoggle_8_sdeIdeal/circuit/const_737','Value','0.');
  set_param('ckt_gentoggle_8_sdeIdeal/circuit/const_737','position',[452,375,502,395]);
  add_line('ckt_gentoggle_8_sdeIdeal/circuit','const_737/1','input.V[7]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_sdeIdeal/circuit/const_739');
  set_param('ckt_gentoggle_8_sdeIdeal/circuit/const_739','Value','4.');
  set_param('ckt_gentoggle_8_sdeIdeal/circuit/const_739','position',[149,53,199,73]);
  add_line('ckt_gentoggle_8_sdeIdeal/circuit','const_739/1','input.V[8]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_sdeIdeal/circuit/const_741');
  set_param('ckt_gentoggle_8_sdeIdeal/circuit/const_741','Value','4.');
  set_param('ckt_gentoggle_8_sdeIdeal/circuit/const_741','position',[717,353,767,373]);
  add_line('ckt_gentoggle_8_sdeIdeal/circuit','const_741/1','input.V[9]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_sdeIdeal/circuit/const_743');
  set_param('ckt_gentoggle_8_sdeIdeal/circuit/const_743','Value','4.');
  set_param('ckt_gentoggle_8_sdeIdeal/circuit/const_743','position',[587,491,637,511]);
  add_line('ckt_gentoggle_8_sdeIdeal/circuit','const_743/1','input.V[10]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_sdeIdeal/circuit/const_745');
  set_param('ckt_gentoggle_8_sdeIdeal/circuit/const_745','Value','1000.75');
  set_param('ckt_gentoggle_8_sdeIdeal/circuit/const_745','position',[152,296,202,316]);
  add_line('ckt_gentoggle_8_sdeIdeal/circuit','const_745/1','input.V[11]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_sdeIdeal/circuit/const_747');
  set_param('ckt_gentoggle_8_sdeIdeal/circuit/const_747','Value','0.0029618');
  set_param('ckt_gentoggle_8_sdeIdeal/circuit/const_747','position',[10,459,60,479]);
  add_line('ckt_gentoggle_8_sdeIdeal/circuit','const_747/1','input.I[5]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_sdeIdeal/circuit/const_749');
  set_param('ckt_gentoggle_8_sdeIdeal/circuit/const_749','Value','1.');
  set_param('ckt_gentoggle_8_sdeIdeal/circuit/const_749','position',[27,151,77,171]);
  add_line('ckt_gentoggle_8_sdeIdeal/circuit','const_749/1','input.V[16]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_sdeIdeal/circuit/const_751');
  set_param('ckt_gentoggle_8_sdeIdeal/circuit/const_751','Value','1.');
  set_param('ckt_gentoggle_8_sdeIdeal/circuit/const_751','position',[730,467,780,487]);
  add_line('ckt_gentoggle_8_sdeIdeal/circuit','const_751/1','input.V[17]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_sdeIdeal/circuit/const_753');
  set_param('ckt_gentoggle_8_sdeIdeal/circuit/const_753','Value','1.');
  set_param('ckt_gentoggle_8_sdeIdeal/circuit/const_753','position',[858,631,908,651]);
  add_line('ckt_gentoggle_8_sdeIdeal/circuit','const_753/1','input.V[12]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_sdeIdeal/circuit/const_755');
  set_param('ckt_gentoggle_8_sdeIdeal/circuit/const_755','Value','1.');
  set_param('ckt_gentoggle_8_sdeIdeal/circuit/const_755','position',[926,395,976,415]);
  add_line('ckt_gentoggle_8_sdeIdeal/circuit','const_755/1','input.V[13]/1');
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_8_sdeIdeal/circuit/output.V[0]_out');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_sdeIdeal/circuit/_output.V[0]_out');
  add_line('ckt_gentoggle_8_sdeIdeal/circuit','_output.V[0]_out/1','output.V[0]_out/1');
  set_param('ckt_gentoggle_8_sdeIdeal/circuit/output.V[0]_out','position',[602,619,652,639]);
  add_line('ckt_gentoggle_8_sdeIdeal/circuit','output.V[0]/1','_output.V[0]_out/1');
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_8_sdeIdeal/circuit/output.V[1]_out');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_sdeIdeal/circuit/_output.V[1]_out');
  add_line('ckt_gentoggle_8_sdeIdeal/circuit','_output.V[1]_out/1','output.V[1]_out/1');
  set_param('ckt_gentoggle_8_sdeIdeal/circuit/output.V[1]_out','position',[772,6,822,26]);
  add_line('ckt_gentoggle_8_sdeIdeal/circuit','output.V[1]/1','_output.V[1]_out/1');
end
%
%
%preamble function
function preamble()
  %define model name
  model_name='ckt_gentoggle_8_sdeIdeal';
  %create and open the model
  open_system(new_system(model_name));
  %set solver method
  set_param(model_name,'Solver','ode3');
end
%
%
%library assembly function
function build_comp_library()
  add_block('simulink/Ports & Subsystems/Subsystem','ckt_gentoggle_8_sdeIdeal/library');
  set_param('ckt_gentoggle_8_sdeIdeal/library','position',[887,555,937,575]);
  delete_line('ckt_gentoggle_8_sdeIdeal/library','In1/1','Out1/1');
  delete_block('ckt_gentoggle_8_sdeIdeal/library/In1');
  delete_block('ckt_gentoggle_8_sdeIdeal/library/Out1');
  %
  %
  %
  add_block('simulink/Ports & Subsystems/Subsystem','ckt_gentoggle_8_sdeIdeal/library/mm');
  set_param('ckt_gentoggle_8_sdeIdeal/library/mm','position',[458,11,508,31]);
  delete_line('ckt_gentoggle_8_sdeIdeal/library/mm','In1/1','Out1/1');
  delete_block('ckt_gentoggle_8_sdeIdeal/library/mm/In1');
  delete_block('ckt_gentoggle_8_sdeIdeal/library/mm/Out1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_8_sdeIdeal/library/mm/kr');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_sdeIdeal/library/mm/_kr');
  set_param('ckt_gentoggle_8_sdeIdeal/library/mm/kr','position',[291,434,341,454]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/mm','kr/1','_kr/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_8_sdeIdeal/library/mm/XY0');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_sdeIdeal/library/mm/_XY0');
  set_param('ckt_gentoggle_8_sdeIdeal/library/mm/XY0','position',[936,265,986,285]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/mm','XY0/1','_XY0/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_8_sdeIdeal/library/mm/Ytot');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_sdeIdeal/library/mm/_Ytot');
  set_param('ckt_gentoggle_8_sdeIdeal/library/mm/Ytot','position',[324,518,374,538]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/mm','Ytot/1','_Ytot/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_8_sdeIdeal/library/mm/kf');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_sdeIdeal/library/mm/_kf');
  set_param('ckt_gentoggle_8_sdeIdeal/library/mm/kf','position',[142,118,192,138]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/mm','kf/1','_kf/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_8_sdeIdeal/library/mm/Xtot');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_sdeIdeal/library/mm/_Xtot');
  set_param('ckt_gentoggle_8_sdeIdeal/library/mm/Xtot','position',[490,687,540,707]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/mm','Xtot/1','_Xtot/1');
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_8_sdeIdeal/library/mm/X');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_sdeIdeal/library/mm/_X');
  add_line('ckt_gentoggle_8_sdeIdeal/library/mm','_X/1','X/1');
  set_param('ckt_gentoggle_8_sdeIdeal/library/mm/X','position',[72,932,122,952]);
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_8_sdeIdeal/library/mm/XY');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_sdeIdeal/library/mm/_XY');
  add_line('ckt_gentoggle_8_sdeIdeal/library/mm','_XY/1','XY/1');
  set_param('ckt_gentoggle_8_sdeIdeal/library/mm/XY','position',[545,685,595,705]);
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_8_sdeIdeal/library/mm/Y');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_sdeIdeal/library/mm/_Y');
  add_line('ckt_gentoggle_8_sdeIdeal/library/mm','_Y/1','Y/1');
  set_param('ckt_gentoggle_8_sdeIdeal/library/mm/Y','position',[581,444,631,464]);
  add_block('simulink/Math Operations/Sum','ckt_gentoggle_8_sdeIdeal/library/mm/sum_39');
  set_param('ckt_gentoggle_8_sdeIdeal/library/mm/sum_39','Inputs','+-');
  set_param('ckt_gentoggle_8_sdeIdeal/library/mm/sum_39','position',[977,433,1027,453]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/mm','_Xtot/1','sum_39/1');
  add_line('ckt_gentoggle_8_sdeIdeal/library/mm','_XY/1','sum_39/2');
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_sdeIdeal/library/mm/const_42');
  set_param('ckt_gentoggle_8_sdeIdeal/library/mm/const_42','Value','0.');
  set_param('ckt_gentoggle_8_sdeIdeal/library/mm/const_42','position',[790,14,840,34]);
  add_block('simulink/Sources/Uniform Random Number','ckt_gentoggle_8_sdeIdeal/library/mm/unz_44');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_8_sdeIdeal/library/mm/unzv_44');
  add_block('simulink/Math Operations/Sum','ckt_gentoggle_8_sdeIdeal/library/mm/unza_44');
  set_param('ckt_gentoggle_8_sdeIdeal/library/mm/unza_44','Inputs','++');
  set_param('ckt_gentoggle_8_sdeIdeal/library/mm/unzv_44','Inputs','**');
  set_param('ckt_gentoggle_8_sdeIdeal/library/mm/unz_44','position',[918,135,968,155]);
  set_param('ckt_gentoggle_8_sdeIdeal/library/mm/unza_44','position',[848,27,898,47]);
  set_param('ckt_gentoggle_8_sdeIdeal/library/mm/unzv_44','position',[851,10,901,30]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/mm','unz_44/1','unzv_44/2');
  add_line('ckt_gentoggle_8_sdeIdeal/library/mm','unzv_44/1','unza_44/2');
  add_line('ckt_gentoggle_8_sdeIdeal/library/mm','sum_39/1','unza_44/1');
  add_line('ckt_gentoggle_8_sdeIdeal/library/mm','const_42/1','unzv_44/1');
  add_line('ckt_gentoggle_8_sdeIdeal/library/mm','unza_44/1','_X/1');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_8_sdeIdeal/library/mm/mul_52');
  set_param('ckt_gentoggle_8_sdeIdeal/library/mm/mul_52','Inputs','***');
  set_param('ckt_gentoggle_8_sdeIdeal/library/mm/mul_52','position',[301,561,351,581]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/mm','_kf/1','mul_52/1');
  add_line('ckt_gentoggle_8_sdeIdeal/library/mm','_X/1','mul_52/2');
  add_line('ckt_gentoggle_8_sdeIdeal/library/mm','_Y/1','mul_52/3');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_8_sdeIdeal/library/mm/mul_56');
  set_param('ckt_gentoggle_8_sdeIdeal/library/mm/mul_56','Inputs','**');
  set_param('ckt_gentoggle_8_sdeIdeal/library/mm/mul_56','position',[76,358,126,378]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/mm','_kr/1','mul_56/1');
  add_line('ckt_gentoggle_8_sdeIdeal/library/mm','_XY/1','mul_56/2');
  add_block('simulink/Math Operations/Sum','ckt_gentoggle_8_sdeIdeal/library/mm/sum_59');
  set_param('ckt_gentoggle_8_sdeIdeal/library/mm/sum_59','Inputs','+-');
  set_param('ckt_gentoggle_8_sdeIdeal/library/mm/sum_59','position',[622,755,672,775]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/mm','mul_52/1','sum_59/1');
  add_line('ckt_gentoggle_8_sdeIdeal/library/mm','mul_56/1','sum_59/2');
  add_block('simulink/Continuous/Integrator','ckt_gentoggle_8_sdeIdeal/library/mm/int_62');
  set_param('ckt_gentoggle_8_sdeIdeal/library/mm/int_62','position',[421,507,471,527]);
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_sdeIdeal/library/mm/const_64');
  set_param('ckt_gentoggle_8_sdeIdeal/library/mm/const_64','Value','0.001');
  set_param('ckt_gentoggle_8_sdeIdeal/library/mm/const_64','position',[229,660,279,680]);
  add_block('simulink/Math Operations/Product','ckt_gentoggle_8_sdeIdeal/library/mm/mul_66');
  set_param('ckt_gentoggle_8_sdeIdeal/library/mm/mul_66','Inputs','**');
  set_param('ckt_gentoggle_8_sdeIdeal/library/mm/mul_66','position',[632,963,682,983]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/mm','const_64/1','mul_66/1');
  add_line('ckt_gentoggle_8_sdeIdeal/library/mm','_XY/1','mul_66/2');
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_sdeIdeal/library/mm/const_69');
  set_param('ckt_gentoggle_8_sdeIdeal/library/mm/const_69','Value','0.1');
  set_param('ckt_gentoggle_8_sdeIdeal/library/mm/const_69','position',[840,961,890,981]);
  add_block('simulink/Math Operations/Sum','ckt_gentoggle_8_sdeIdeal/library/mm/sub_71');
  set_param('ckt_gentoggle_8_sdeIdeal/library/mm/sub_71','Inputs','++');
  set_param('ckt_gentoggle_8_sdeIdeal/library/mm/sub_71','position',[13,473,63,493]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/mm','mul_66/1','sub_71/1');
  add_line('ckt_gentoggle_8_sdeIdeal/library/mm','const_69/1','sub_71/2');
  add_block('simulink/Sources/Uniform Random Number','ckt_gentoggle_8_sdeIdeal/library/mm/unz_74');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_8_sdeIdeal/library/mm/unzv_74');
  add_block('simulink/Math Operations/Sum','ckt_gentoggle_8_sdeIdeal/library/mm/unza_74');
  set_param('ckt_gentoggle_8_sdeIdeal/library/mm/unza_74','Inputs','++');
  set_param('ckt_gentoggle_8_sdeIdeal/library/mm/unzv_74','Inputs','**');
  set_param('ckt_gentoggle_8_sdeIdeal/library/mm/unz_74','position',[262,11,312,31]);
  set_param('ckt_gentoggle_8_sdeIdeal/library/mm/unza_74','position',[409,432,459,452]);
  set_param('ckt_gentoggle_8_sdeIdeal/library/mm/unzv_74','position',[330,541,380,561]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/mm','unz_74/1','unzv_74/2');
  add_line('ckt_gentoggle_8_sdeIdeal/library/mm','unzv_74/1','unza_74/2');
  add_line('ckt_gentoggle_8_sdeIdeal/library/mm','sum_59/1','unza_74/1');
  add_line('ckt_gentoggle_8_sdeIdeal/library/mm','sub_71/1','unzv_74/1');
  add_line('ckt_gentoggle_8_sdeIdeal/library/mm','unza_74/1','int_62/1');
  add_line('ckt_gentoggle_8_sdeIdeal/library/mm','int_62/1','_XY/1');
  add_block('simulink/Math Operations/Sum','ckt_gentoggle_8_sdeIdeal/library/mm/sum_82');
  set_param('ckt_gentoggle_8_sdeIdeal/library/mm/sum_82','Inputs','+-');
  set_param('ckt_gentoggle_8_sdeIdeal/library/mm/sum_82','position',[510,939,560,959]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/mm','_Ytot/1','sum_82/1');
  add_line('ckt_gentoggle_8_sdeIdeal/library/mm','_XY/1','sum_82/2');
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_sdeIdeal/library/mm/const_85');
  set_param('ckt_gentoggle_8_sdeIdeal/library/mm/const_85','Value','0.');
  set_param('ckt_gentoggle_8_sdeIdeal/library/mm/const_85','position',[694,981,744,1001]);
  add_block('simulink/Sources/Uniform Random Number','ckt_gentoggle_8_sdeIdeal/library/mm/unz_87');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_8_sdeIdeal/library/mm/unzv_87');
  add_block('simulink/Math Operations/Sum','ckt_gentoggle_8_sdeIdeal/library/mm/unza_87');
  set_param('ckt_gentoggle_8_sdeIdeal/library/mm/unza_87','Inputs','++');
  set_param('ckt_gentoggle_8_sdeIdeal/library/mm/unzv_87','Inputs','**');
  set_param('ckt_gentoggle_8_sdeIdeal/library/mm/unz_87','position',[193,804,243,824]);
  set_param('ckt_gentoggle_8_sdeIdeal/library/mm/unza_87','position',[631,481,681,501]);
  set_param('ckt_gentoggle_8_sdeIdeal/library/mm/unzv_87','position',[10,148,60,168]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/mm','unz_87/1','unzv_87/2');
  add_line('ckt_gentoggle_8_sdeIdeal/library/mm','unzv_87/1','unza_87/2');
  add_line('ckt_gentoggle_8_sdeIdeal/library/mm','sum_82/1','unza_87/1');
  add_line('ckt_gentoggle_8_sdeIdeal/library/mm','const_85/1','unzv_87/1');
  add_line('ckt_gentoggle_8_sdeIdeal/library/mm','unza_87/1','_Y/1');
  %
  add_block('simulink/Ports & Subsystems/Subsystem','ckt_gentoggle_8_sdeIdeal/library/vgain');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vgain','position',[44,427,94,447]);
  delete_line('ckt_gentoggle_8_sdeIdeal/library/vgain','In1/1','Out1/1');
  delete_block('ckt_gentoggle_8_sdeIdeal/library/vgain/In1');
  delete_block('ckt_gentoggle_8_sdeIdeal/library/vgain/Out1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_8_sdeIdeal/library/vgain/X');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_sdeIdeal/library/vgain/_X');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vgain/X','position',[882,401,932,421]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/vgain','X/1','_X/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_8_sdeIdeal/library/vgain/Y');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_sdeIdeal/library/vgain/_Y');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vgain/Y','position',[194,742,244,762]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/vgain','Y/1','_Y/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_8_sdeIdeal/library/vgain/Z');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_sdeIdeal/library/vgain/_Z');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vgain/Z','position',[757,894,807,914]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/vgain','Z/1','_Z/1');
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_8_sdeIdeal/library/vgain/P');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_sdeIdeal/library/vgain/_P');
  add_line('ckt_gentoggle_8_sdeIdeal/library/vgain','_P/1','P/1');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vgain/P','position',[642,489,692,509]);
  add_block('simulink/Math Operations/Product','ckt_gentoggle_8_sdeIdeal/library/vgain/div_115');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vgain/div_115','Inputs','*/');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vgain/div_115','position',[423,337,473,357]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/vgain','_X/1','div_115/1');
  add_line('ckt_gentoggle_8_sdeIdeal/library/vgain','_Y/1','div_115/2');
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_sdeIdeal/library/vgain/const_118');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vgain/const_118','Value','0.5');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vgain/const_118','position',[94,435,144,455]);
  add_block('simulink/Math Operations/Product','ckt_gentoggle_8_sdeIdeal/library/vgain/mul_120');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vgain/mul_120','Inputs','***');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vgain/mul_120','position',[221,994,271,1014]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/vgain','div_115/1','mul_120/1');
  add_line('ckt_gentoggle_8_sdeIdeal/library/vgain','_Z/1','mul_120/2');
  add_line('ckt_gentoggle_8_sdeIdeal/library/vgain','const_118/1','mul_120/3');
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_sdeIdeal/library/vgain/const_124');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vgain/const_124','Value','0.0001');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vgain/const_124','position',[564,61,614,81]);
  add_block('simulink/Math Operations/Product','ckt_gentoggle_8_sdeIdeal/library/vgain/mul_126');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vgain/mul_126','Inputs','**');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vgain/mul_126','position',[575,494,625,514]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/vgain','const_124/1','mul_126/1');
  add_line('ckt_gentoggle_8_sdeIdeal/library/vgain','_P/1','mul_126/2');
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_sdeIdeal/library/vgain/const_129');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vgain/const_129','Value','0.01');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vgain/const_129','position',[934,385,984,405]);
  add_block('simulink/Math Operations/Sum','ckt_gentoggle_8_sdeIdeal/library/vgain/sub_131');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vgain/sub_131','Inputs','++');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vgain/sub_131','position',[551,549,601,569]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/vgain','mul_126/1','sub_131/1');
  add_line('ckt_gentoggle_8_sdeIdeal/library/vgain','const_129/1','sub_131/2');
  add_block('simulink/Sources/Uniform Random Number','ckt_gentoggle_8_sdeIdeal/library/vgain/unz_134');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_8_sdeIdeal/library/vgain/unzv_134');
  add_block('simulink/Math Operations/Sum','ckt_gentoggle_8_sdeIdeal/library/vgain/unza_134');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vgain/unza_134','Inputs','++');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vgain/unzv_134','Inputs','**');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vgain/unz_134','position',[144,978,194,998]);
  set_param('ckt_gentoggle_8_sdeIdeal/library/vgain/unza_134','position',[240,439,290,459]);
  set_param('ckt_gentoggle_8_sdeIdeal/library/vgain/unzv_134','position',[812,254,862,274]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/vgain','unz_134/1','unzv_134/2');
  add_line('ckt_gentoggle_8_sdeIdeal/library/vgain','unzv_134/1','unza_134/2');
  add_line('ckt_gentoggle_8_sdeIdeal/library/vgain','mul_120/1','unza_134/1');
  add_line('ckt_gentoggle_8_sdeIdeal/library/vgain','sub_131/1','unzv_134/1');
  add_line('ckt_gentoggle_8_sdeIdeal/library/vgain','unza_134/1','_P/1');
  %
  add_block('simulink/Ports & Subsystems/Subsystem','ckt_gentoggle_8_sdeIdeal/library/switch');
  set_param('ckt_gentoggle_8_sdeIdeal/library/switch','position',[105,438,155,458]);
  delete_line('ckt_gentoggle_8_sdeIdeal/library/switch','In1/1','Out1/1');
  delete_block('ckt_gentoggle_8_sdeIdeal/library/switch/In1');
  delete_block('ckt_gentoggle_8_sdeIdeal/library/switch/Out1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_8_sdeIdeal/library/switch/n');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_sdeIdeal/library/switch/_n');
  set_param('ckt_gentoggle_8_sdeIdeal/library/switch/n','position',[528,270,578,290]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/switch','n/1','_n/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_8_sdeIdeal/library/switch/SUB');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_sdeIdeal/library/switch/_SUB');
  set_param('ckt_gentoggle_8_sdeIdeal/library/switch/SUB','position',[702,679,752,699]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/switch','SUB/1','_SUB/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_8_sdeIdeal/library/switch/Kmod');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_sdeIdeal/library/switch/_Kmod');
  set_param('ckt_gentoggle_8_sdeIdeal/library/switch/Kmod','position',[557,37,607,57]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/switch','Kmod/1','_Kmod/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_8_sdeIdeal/library/switch/Vmax');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_sdeIdeal/library/switch/_Vmax');
  set_param('ckt_gentoggle_8_sdeIdeal/library/switch/Vmax','position',[515,787,565,807]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/switch','Vmax/1','_Vmax/1');
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_8_sdeIdeal/library/switch/PROD');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_sdeIdeal/library/switch/_PROD');
  add_line('ckt_gentoggle_8_sdeIdeal/library/switch','_PROD/1','PROD/1');
  set_param('ckt_gentoggle_8_sdeIdeal/library/switch/PROD','position',[779,58,829,78]);
  add_block('simulink/Math Operations/Product','ckt_gentoggle_8_sdeIdeal/library/switch/div_167');
  set_param('ckt_gentoggle_8_sdeIdeal/library/switch/div_167','Inputs','*/');
  set_param('ckt_gentoggle_8_sdeIdeal/library/switch/div_167','position',[972,6,1022,26]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/switch','_SUB/1','div_167/1');
  add_line('ckt_gentoggle_8_sdeIdeal/library/switch','_Kmod/1','div_167/2');
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_sdeIdeal/library/switch/const_170');
  set_param('ckt_gentoggle_8_sdeIdeal/library/switch/const_170','Value','1.');
  set_param('ckt_gentoggle_8_sdeIdeal/library/switch/const_170','position',[934,611,984,631]);
  add_block('simulink/Math Operations/Sum','ckt_gentoggle_8_sdeIdeal/library/switch/sub_172');
  set_param('ckt_gentoggle_8_sdeIdeal/library/switch/sub_172','Inputs','++');
  set_param('ckt_gentoggle_8_sdeIdeal/library/switch/sub_172','position',[219,925,269,945]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/switch','div_167/1','sub_172/1');
  add_line('ckt_gentoggle_8_sdeIdeal/library/switch','const_170/1','sub_172/2');
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_sdeIdeal/library/switch/const_175');
  set_param('ckt_gentoggle_8_sdeIdeal/library/switch/const_175','Value','500.');
  set_param('ckt_gentoggle_8_sdeIdeal/library/switch/const_175','position',[303,253,353,273]);
  add_block('simulink/Math Operations/Product','ckt_gentoggle_8_sdeIdeal/library/switch/div_177');
  set_param('ckt_gentoggle_8_sdeIdeal/library/switch/div_177','Inputs','*/');
  set_param('ckt_gentoggle_8_sdeIdeal/library/switch/div_177','position',[43,774,93,794]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/switch','_n/1','div_177/1');
  add_line('ckt_gentoggle_8_sdeIdeal/library/switch','const_175/1','div_177/2');
  add_block('simulink/Math Operations/Math Function','ckt_gentoggle_8_sdeIdeal/library/switch/pow_180');
  set_param('ckt_gentoggle_8_sdeIdeal/library/switch/pow_180','Function','pow');
  set_param('ckt_gentoggle_8_sdeIdeal/library/switch/pow_180','position',[856,564,906,584]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/switch','div_177/1','pow_180/2');
  add_line('ckt_gentoggle_8_sdeIdeal/library/switch','sub_172/1','pow_180/1');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_8_sdeIdeal/library/switch/div_183');
  set_param('ckt_gentoggle_8_sdeIdeal/library/switch/div_183','Inputs','*/');
  set_param('ckt_gentoggle_8_sdeIdeal/library/switch/div_183','position',[405,725,455,745]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/switch','_Vmax/1','div_183/1');
  add_line('ckt_gentoggle_8_sdeIdeal/library/switch','pow_180/1','div_183/2');
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_sdeIdeal/library/switch/const_186');
  set_param('ckt_gentoggle_8_sdeIdeal/library/switch/const_186','Value','0.');
  set_param('ckt_gentoggle_8_sdeIdeal/library/switch/const_186','position',[817,359,867,379]);
  add_block('simulink/Sources/Uniform Random Number','ckt_gentoggle_8_sdeIdeal/library/switch/unz_188');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_8_sdeIdeal/library/switch/unzv_188');
  add_block('simulink/Math Operations/Sum','ckt_gentoggle_8_sdeIdeal/library/switch/unza_188');
  set_param('ckt_gentoggle_8_sdeIdeal/library/switch/unza_188','Inputs','++');
  set_param('ckt_gentoggle_8_sdeIdeal/library/switch/unzv_188','Inputs','**');
  set_param('ckt_gentoggle_8_sdeIdeal/library/switch/unz_188','position',[7,116,57,136]);
  set_param('ckt_gentoggle_8_sdeIdeal/library/switch/unza_188','position',[497,989,547,1009]);
  set_param('ckt_gentoggle_8_sdeIdeal/library/switch/unzv_188','position',[760,862,810,882]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/switch','unz_188/1','unzv_188/2');
  add_line('ckt_gentoggle_8_sdeIdeal/library/switch','unzv_188/1','unza_188/2');
  add_line('ckt_gentoggle_8_sdeIdeal/library/switch','div_183/1','unza_188/1');
  add_line('ckt_gentoggle_8_sdeIdeal/library/switch','const_186/1','unzv_188/1');
  add_line('ckt_gentoggle_8_sdeIdeal/library/switch','unza_188/1','_PROD/1');
  %
  add_block('simulink/Ports & Subsystems/Subsystem','ckt_gentoggle_8_sdeIdeal/library/ihill');
  set_param('ckt_gentoggle_8_sdeIdeal/library/ihill','position',[22,341,72,361]);
  delete_line('ckt_gentoggle_8_sdeIdeal/library/ihill','In1/1','Out1/1');
  delete_block('ckt_gentoggle_8_sdeIdeal/library/ihill/In1');
  delete_block('ckt_gentoggle_8_sdeIdeal/library/ihill/Out1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_8_sdeIdeal/library/ihill/n');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_sdeIdeal/library/ihill/_n');
  set_param('ckt_gentoggle_8_sdeIdeal/library/ihill/n','position',[654,313,704,333]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/ihill','n/1','_n/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_8_sdeIdeal/library/ihill/S');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_sdeIdeal/library/ihill/_S');
  set_param('ckt_gentoggle_8_sdeIdeal/library/ihill/S','position',[976,801,1026,821]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/ihill','S/1','_S/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_8_sdeIdeal/library/ihill/Km');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_sdeIdeal/library/ihill/_Km');
  set_param('ckt_gentoggle_8_sdeIdeal/library/ihill/Km','position',[284,918,334,938]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/ihill','Km/1','_Km/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_8_sdeIdeal/library/ihill/Vmax');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_sdeIdeal/library/ihill/_Vmax');
  set_param('ckt_gentoggle_8_sdeIdeal/library/ihill/Vmax','position',[509,332,559,352]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/ihill','Vmax/1','_Vmax/1');
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_8_sdeIdeal/library/ihill/STIM');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_sdeIdeal/library/ihill/_STIM');
  add_line('ckt_gentoggle_8_sdeIdeal/library/ihill','_STIM/1','STIM/1');
  set_param('ckt_gentoggle_8_sdeIdeal/library/ihill/STIM','position',[186,725,236,745]);
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_8_sdeIdeal/library/ihill/REP');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_sdeIdeal/library/ihill/_REP');
  add_line('ckt_gentoggle_8_sdeIdeal/library/ihill','_REP/1','REP/1');
  set_param('ckt_gentoggle_8_sdeIdeal/library/ihill/REP','position',[484,21,534,41]);
  add_block('simulink/Math Operations/Product','ckt_gentoggle_8_sdeIdeal/library/ihill/div_225');
  set_param('ckt_gentoggle_8_sdeIdeal/library/ihill/div_225','Inputs','*/');
  set_param('ckt_gentoggle_8_sdeIdeal/library/ihill/div_225','position',[384,947,434,967]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/ihill','_S/1','div_225/1');
  add_line('ckt_gentoggle_8_sdeIdeal/library/ihill','_Km/1','div_225/2');
  add_block('simulink/Math Operations/Math Function','ckt_gentoggle_8_sdeIdeal/library/ihill/pow_228');
  set_param('ckt_gentoggle_8_sdeIdeal/library/ihill/pow_228','Function','pow');
  set_param('ckt_gentoggle_8_sdeIdeal/library/ihill/pow_228','position',[213,654,263,674]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/ihill','_n/1','pow_228/2');
  add_line('ckt_gentoggle_8_sdeIdeal/library/ihill','div_225/1','pow_228/1');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_8_sdeIdeal/library/ihill/div_231');
  set_param('ckt_gentoggle_8_sdeIdeal/library/ihill/div_231','Inputs','*/');
  set_param('ckt_gentoggle_8_sdeIdeal/library/ihill/div_231','position',[816,290,866,310]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/ihill','_S/1','div_231/1');
  add_line('ckt_gentoggle_8_sdeIdeal/library/ihill','_Km/1','div_231/2');
  add_block('simulink/Math Operations/Math Function','ckt_gentoggle_8_sdeIdeal/library/ihill/pow_234');
  set_param('ckt_gentoggle_8_sdeIdeal/library/ihill/pow_234','Function','pow');
  set_param('ckt_gentoggle_8_sdeIdeal/library/ihill/pow_234','position',[325,678,375,698]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/ihill','_n/1','pow_234/2');
  add_line('ckt_gentoggle_8_sdeIdeal/library/ihill','div_231/1','pow_234/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_sdeIdeal/library/ihill/const_237');
  set_param('ckt_gentoggle_8_sdeIdeal/library/ihill/const_237','Value','1.');
  set_param('ckt_gentoggle_8_sdeIdeal/library/ihill/const_237','position',[612,672,662,692]);
  add_block('simulink/Math Operations/Sum','ckt_gentoggle_8_sdeIdeal/library/ihill/sub_239');
  set_param('ckt_gentoggle_8_sdeIdeal/library/ihill/sub_239','Inputs','++');
  set_param('ckt_gentoggle_8_sdeIdeal/library/ihill/sub_239','position',[792,520,842,540]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/ihill','pow_234/1','sub_239/1');
  add_line('ckt_gentoggle_8_sdeIdeal/library/ihill','const_237/1','sub_239/2');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_8_sdeIdeal/library/ihill/div_242');
  set_param('ckt_gentoggle_8_sdeIdeal/library/ihill/div_242','Inputs','*/');
  set_param('ckt_gentoggle_8_sdeIdeal/library/ihill/div_242','position',[215,878,265,898]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/ihill','pow_228/1','div_242/1');
  add_line('ckt_gentoggle_8_sdeIdeal/library/ihill','sub_239/1','div_242/2');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_8_sdeIdeal/library/ihill/mul_245');
  set_param('ckt_gentoggle_8_sdeIdeal/library/ihill/mul_245','Inputs','**');
  set_param('ckt_gentoggle_8_sdeIdeal/library/ihill/mul_245','position',[838,239,888,259]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/ihill','_Vmax/1','mul_245/1');
  add_line('ckt_gentoggle_8_sdeIdeal/library/ihill','div_242/1','mul_245/2');
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_sdeIdeal/library/ihill/const_248');
  set_param('ckt_gentoggle_8_sdeIdeal/library/ihill/const_248','Value','0.');
  set_param('ckt_gentoggle_8_sdeIdeal/library/ihill/const_248','position',[564,438,614,458]);
  add_block('simulink/Sources/Uniform Random Number','ckt_gentoggle_8_sdeIdeal/library/ihill/unz_250');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_8_sdeIdeal/library/ihill/unzv_250');
  add_block('simulink/Math Operations/Sum','ckt_gentoggle_8_sdeIdeal/library/ihill/unza_250');
  set_param('ckt_gentoggle_8_sdeIdeal/library/ihill/unza_250','Inputs','++');
  set_param('ckt_gentoggle_8_sdeIdeal/library/ihill/unzv_250','Inputs','**');
  set_param('ckt_gentoggle_8_sdeIdeal/library/ihill/unz_250','position',[477,785,527,805]);
  set_param('ckt_gentoggle_8_sdeIdeal/library/ihill/unza_250','position',[578,793,628,813]);
  set_param('ckt_gentoggle_8_sdeIdeal/library/ihill/unzv_250','position',[831,105,881,125]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/ihill','unz_250/1','unzv_250/2');
  add_line('ckt_gentoggle_8_sdeIdeal/library/ihill','unzv_250/1','unza_250/2');
  add_line('ckt_gentoggle_8_sdeIdeal/library/ihill','mul_245/1','unza_250/1');
  add_line('ckt_gentoggle_8_sdeIdeal/library/ihill','const_248/1','unzv_250/1');
  add_line('ckt_gentoggle_8_sdeIdeal/library/ihill','unza_250/1','_STIM/1');
  add_block('simulink/Math Operations/Math Function','ckt_gentoggle_8_sdeIdeal/library/ihill/pow_258');
  set_param('ckt_gentoggle_8_sdeIdeal/library/ihill/pow_258','Function','pow');
  set_param('ckt_gentoggle_8_sdeIdeal/library/ihill/pow_258','position',[772,501,822,521]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/ihill','_n/1','pow_258/2');
  add_line('ckt_gentoggle_8_sdeIdeal/library/ihill','_Km/1','pow_258/1');
  add_block('simulink/Math Operations/Math Function','ckt_gentoggle_8_sdeIdeal/library/ihill/pow_261');
  set_param('ckt_gentoggle_8_sdeIdeal/library/ihill/pow_261','Function','pow');
  set_param('ckt_gentoggle_8_sdeIdeal/library/ihill/pow_261','position',[687,998,737,1018]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/ihill','_n/1','pow_261/2');
  add_line('ckt_gentoggle_8_sdeIdeal/library/ihill','_S/1','pow_261/1');
  add_block('simulink/Math Operations/Math Function','ckt_gentoggle_8_sdeIdeal/library/ihill/pow_264');
  set_param('ckt_gentoggle_8_sdeIdeal/library/ihill/pow_264','Function','pow');
  set_param('ckt_gentoggle_8_sdeIdeal/library/ihill/pow_264','position',[771,228,821,248]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/ihill','_n/1','pow_264/2');
  add_line('ckt_gentoggle_8_sdeIdeal/library/ihill','_Km/1','pow_264/1');
  add_block('simulink/Math Operations/Sum','ckt_gentoggle_8_sdeIdeal/library/ihill/sub_267');
  set_param('ckt_gentoggle_8_sdeIdeal/library/ihill/sub_267','Inputs','++');
  set_param('ckt_gentoggle_8_sdeIdeal/library/ihill/sub_267','position',[657,341,707,361]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/ihill','pow_261/1','sub_267/1');
  add_line('ckt_gentoggle_8_sdeIdeal/library/ihill','pow_264/1','sub_267/2');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_8_sdeIdeal/library/ihill/div_270');
  set_param('ckt_gentoggle_8_sdeIdeal/library/ihill/div_270','Inputs','*/');
  set_param('ckt_gentoggle_8_sdeIdeal/library/ihill/div_270','position',[195,972,245,992]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/ihill','pow_258/1','div_270/1');
  add_line('ckt_gentoggle_8_sdeIdeal/library/ihill','sub_267/1','div_270/2');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_8_sdeIdeal/library/ihill/mul_273');
  set_param('ckt_gentoggle_8_sdeIdeal/library/ihill/mul_273','Inputs','**');
  set_param('ckt_gentoggle_8_sdeIdeal/library/ihill/mul_273','position',[419,186,469,206]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/ihill','_Vmax/1','mul_273/1');
  add_line('ckt_gentoggle_8_sdeIdeal/library/ihill','div_270/1','mul_273/2');
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_sdeIdeal/library/ihill/const_276');
  set_param('ckt_gentoggle_8_sdeIdeal/library/ihill/const_276','Value','0.');
  set_param('ckt_gentoggle_8_sdeIdeal/library/ihill/const_276','position',[849,973,899,993]);
  add_block('simulink/Sources/Uniform Random Number','ckt_gentoggle_8_sdeIdeal/library/ihill/unz_278');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_8_sdeIdeal/library/ihill/unzv_278');
  add_block('simulink/Math Operations/Sum','ckt_gentoggle_8_sdeIdeal/library/ihill/unza_278');
  set_param('ckt_gentoggle_8_sdeIdeal/library/ihill/unza_278','Inputs','++');
  set_param('ckt_gentoggle_8_sdeIdeal/library/ihill/unzv_278','Inputs','**');
  set_param('ckt_gentoggle_8_sdeIdeal/library/ihill/unz_278','position',[516,23,566,43]);
  set_param('ckt_gentoggle_8_sdeIdeal/library/ihill/unza_278','position',[867,539,917,559]);
  set_param('ckt_gentoggle_8_sdeIdeal/library/ihill/unzv_278','position',[381,980,431,1000]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/ihill','unz_278/1','unzv_278/2');
  add_line('ckt_gentoggle_8_sdeIdeal/library/ihill','unzv_278/1','unza_278/2');
  add_line('ckt_gentoggle_8_sdeIdeal/library/ihill','mul_273/1','unza_278/1');
  add_line('ckt_gentoggle_8_sdeIdeal/library/ihill','const_276/1','unzv_278/1');
  add_line('ckt_gentoggle_8_sdeIdeal/library/ihill','unza_278/1','_REP/1');
  %
  add_block('simulink/Ports & Subsystems/Subsystem','ckt_gentoggle_8_sdeIdeal/library/itov');
  set_param('ckt_gentoggle_8_sdeIdeal/library/itov','position',[206,27,256,47]);
  delete_line('ckt_gentoggle_8_sdeIdeal/library/itov','In1/1','Out1/1');
  delete_block('ckt_gentoggle_8_sdeIdeal/library/itov/In1');
  delete_block('ckt_gentoggle_8_sdeIdeal/library/itov/Out1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_8_sdeIdeal/library/itov/X');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_sdeIdeal/library/itov/_X');
  set_param('ckt_gentoggle_8_sdeIdeal/library/itov/X','position',[355,809,405,829]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/itov','X/1','_X/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_8_sdeIdeal/library/itov/K');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_sdeIdeal/library/itov/_K');
  set_param('ckt_gentoggle_8_sdeIdeal/library/itov/K','position',[315,828,365,848]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/itov','K/1','_K/1');
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_8_sdeIdeal/library/itov/Y');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_sdeIdeal/library/itov/_Y');
  add_line('ckt_gentoggle_8_sdeIdeal/library/itov','_Y/1','Y/1');
  set_param('ckt_gentoggle_8_sdeIdeal/library/itov/Y','position',[505,958,555,978]);
  add_block('simulink/Math Operations/Product','ckt_gentoggle_8_sdeIdeal/library/itov/mul_301');
  set_param('ckt_gentoggle_8_sdeIdeal/library/itov/mul_301','Inputs','**');
  set_param('ckt_gentoggle_8_sdeIdeal/library/itov/mul_301','position',[310,949,360,969]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/itov','_K/1','mul_301/1');
  add_line('ckt_gentoggle_8_sdeIdeal/library/itov','_X/1','mul_301/2');
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_sdeIdeal/library/itov/const_304');
  set_param('ckt_gentoggle_8_sdeIdeal/library/itov/const_304','Value','0.1');
  set_param('ckt_gentoggle_8_sdeIdeal/library/itov/const_304','position',[447,474,497,494]);
  add_block('simulink/Sources/Uniform Random Number','ckt_gentoggle_8_sdeIdeal/library/itov/unz_306');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_8_sdeIdeal/library/itov/unzv_306');
  add_block('simulink/Math Operations/Sum','ckt_gentoggle_8_sdeIdeal/library/itov/unza_306');
  set_param('ckt_gentoggle_8_sdeIdeal/library/itov/unza_306','Inputs','++');
  set_param('ckt_gentoggle_8_sdeIdeal/library/itov/unzv_306','Inputs','**');
  set_param('ckt_gentoggle_8_sdeIdeal/library/itov/unz_306','position',[838,347,888,367]);
  set_param('ckt_gentoggle_8_sdeIdeal/library/itov/unza_306','position',[703,879,753,899]);
  set_param('ckt_gentoggle_8_sdeIdeal/library/itov/unzv_306','position',[183,743,233,763]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/itov','unz_306/1','unzv_306/2');
  add_line('ckt_gentoggle_8_sdeIdeal/library/itov','unzv_306/1','unza_306/2');
  add_line('ckt_gentoggle_8_sdeIdeal/library/itov','mul_301/1','unza_306/1');
  add_line('ckt_gentoggle_8_sdeIdeal/library/itov','const_304/1','unzv_306/1');
  add_line('ckt_gentoggle_8_sdeIdeal/library/itov','unza_306/1','_Y/1');
  %
  add_block('simulink/Ports & Subsystems/Subsystem','ckt_gentoggle_8_sdeIdeal/library/output.I');
  set_param('ckt_gentoggle_8_sdeIdeal/library/output.I','position',[656,173,706,193]);
  delete_line('ckt_gentoggle_8_sdeIdeal/library/output.I','In1/1','Out1/1');
  delete_block('ckt_gentoggle_8_sdeIdeal/library/output.I/In1');
  delete_block('ckt_gentoggle_8_sdeIdeal/library/output.I/Out1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_8_sdeIdeal/library/output.I/X');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_sdeIdeal/library/output.I/_X');
  set_param('ckt_gentoggle_8_sdeIdeal/library/output.I/X','position',[717,812,767,832]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/output.I','X/1','_X/1');
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_8_sdeIdeal/library/output.I/O');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_sdeIdeal/library/output.I/_O');
  add_line('ckt_gentoggle_8_sdeIdeal/library/output.I','_O/1','O/1');
  set_param('ckt_gentoggle_8_sdeIdeal/library/output.I/O','position',[39,395,89,415]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/output.I','_X/1','_O/1');
  %
  add_block('simulink/Ports & Subsystems/Subsystem','ckt_gentoggle_8_sdeIdeal/library/output.V');
  set_param('ckt_gentoggle_8_sdeIdeal/library/output.V','position',[415,250,465,270]);
  delete_line('ckt_gentoggle_8_sdeIdeal/library/output.V','In1/1','Out1/1');
  delete_block('ckt_gentoggle_8_sdeIdeal/library/output.V/In1');
  delete_block('ckt_gentoggle_8_sdeIdeal/library/output.V/Out1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_8_sdeIdeal/library/output.V/X');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_sdeIdeal/library/output.V/_X');
  set_param('ckt_gentoggle_8_sdeIdeal/library/output.V/X','position',[157,524,207,544]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/output.V','X/1','_X/1');
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_8_sdeIdeal/library/output.V/O');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_sdeIdeal/library/output.V/_O');
  add_line('ckt_gentoggle_8_sdeIdeal/library/output.V','_O/1','O/1');
  set_param('ckt_gentoggle_8_sdeIdeal/library/output.V/O','position',[791,434,841,454]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/output.V','_X/1','_O/1');
  %
  add_block('simulink/Ports & Subsystems/Subsystem','ckt_gentoggle_8_sdeIdeal/library/input.V');
  set_param('ckt_gentoggle_8_sdeIdeal/library/input.V','position',[835,857,885,877]);
  delete_line('ckt_gentoggle_8_sdeIdeal/library/input.V','In1/1','Out1/1');
  delete_block('ckt_gentoggle_8_sdeIdeal/library/input.V/In1');
  delete_block('ckt_gentoggle_8_sdeIdeal/library/input.V/Out1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_8_sdeIdeal/library/input.V/X');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_sdeIdeal/library/input.V/_X');
  set_param('ckt_gentoggle_8_sdeIdeal/library/input.V/X','position',[924,768,974,788]);
  add_block('simulink/Discontinuities/Quantizer','ckt_gentoggle_8_sdeIdeal/library/input.V/smp_340');
  set_param('ckt_gentoggle_8_sdeIdeal/library/input.V/smp_340','QuantizationInterval','1e-05');
  set_param('ckt_gentoggle_8_sdeIdeal/library/input.V/smp_340','position',[518,170,568,190]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/input.V','X/1','smp_340/1');
  add_line('ckt_gentoggle_8_sdeIdeal/library/input.V','smp_340/1','_X/1');
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_8_sdeIdeal/library/input.V/O');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_sdeIdeal/library/input.V/_O');
  add_line('ckt_gentoggle_8_sdeIdeal/library/input.V','_O/1','O/1');
  set_param('ckt_gentoggle_8_sdeIdeal/library/input.V/O','position',[114,243,164,263]);
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_sdeIdeal/library/input.V/const_346');
  set_param('ckt_gentoggle_8_sdeIdeal/library/input.V/const_346','Value','0.');
  set_param('ckt_gentoggle_8_sdeIdeal/library/input.V/const_346','position',[364,366,414,386]);
  add_block('simulink/Sources/Uniform Random Number','ckt_gentoggle_8_sdeIdeal/library/input.V/unz_348');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_8_sdeIdeal/library/input.V/unzv_348');
  add_block('simulink/Math Operations/Sum','ckt_gentoggle_8_sdeIdeal/library/input.V/unza_348');
  set_param('ckt_gentoggle_8_sdeIdeal/library/input.V/unza_348','Inputs','++');
  set_param('ckt_gentoggle_8_sdeIdeal/library/input.V/unzv_348','Inputs','**');
  set_param('ckt_gentoggle_8_sdeIdeal/library/input.V/unz_348','position',[966,95,1016,115]);
  set_param('ckt_gentoggle_8_sdeIdeal/library/input.V/unza_348','position',[328,267,378,287]);
  set_param('ckt_gentoggle_8_sdeIdeal/library/input.V/unzv_348','position',[258,33,308,53]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/input.V','unz_348/1','unzv_348/2');
  add_line('ckt_gentoggle_8_sdeIdeal/library/input.V','unzv_348/1','unza_348/2');
  add_line('ckt_gentoggle_8_sdeIdeal/library/input.V','_X/1','unza_348/1');
  add_line('ckt_gentoggle_8_sdeIdeal/library/input.V','const_346/1','unzv_348/1');
  add_line('ckt_gentoggle_8_sdeIdeal/library/input.V','unza_348/1','_O/1');
  %
  add_block('simulink/Ports & Subsystems/Subsystem','ckt_gentoggle_8_sdeIdeal/library/copy.V');
  set_param('ckt_gentoggle_8_sdeIdeal/library/copy.V','position',[873,276,923,296]);
  delete_line('ckt_gentoggle_8_sdeIdeal/library/copy.V','In1/1','Out1/1');
  delete_block('ckt_gentoggle_8_sdeIdeal/library/copy.V/In1');
  delete_block('ckt_gentoggle_8_sdeIdeal/library/copy.V/Out1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_8_sdeIdeal/library/copy.V/X');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_sdeIdeal/library/copy.V/_X');
  set_param('ckt_gentoggle_8_sdeIdeal/library/copy.V/X','position',[183,42,233,62]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/copy.V','X/1','_X/1');
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_8_sdeIdeal/library/copy.V/Y');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_sdeIdeal/library/copy.V/_Y');
  add_line('ckt_gentoggle_8_sdeIdeal/library/copy.V','_Y/1','Y/1');
  set_param('ckt_gentoggle_8_sdeIdeal/library/copy.V/Y','position',[515,323,565,343]);
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_sdeIdeal/library/copy.V/const_366');
  set_param('ckt_gentoggle_8_sdeIdeal/library/copy.V/const_366','Value','0.');
  set_param('ckt_gentoggle_8_sdeIdeal/library/copy.V/const_366','position',[377,734,427,754]);
  add_block('simulink/Sources/Uniform Random Number','ckt_gentoggle_8_sdeIdeal/library/copy.V/unz_368');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_8_sdeIdeal/library/copy.V/unzv_368');
  add_block('simulink/Math Operations/Sum','ckt_gentoggle_8_sdeIdeal/library/copy.V/unza_368');
  set_param('ckt_gentoggle_8_sdeIdeal/library/copy.V/unza_368','Inputs','++');
  set_param('ckt_gentoggle_8_sdeIdeal/library/copy.V/unzv_368','Inputs','**');
  set_param('ckt_gentoggle_8_sdeIdeal/library/copy.V/unz_368','position',[285,422,335,442]);
  set_param('ckt_gentoggle_8_sdeIdeal/library/copy.V/unza_368','position',[316,607,366,627]);
  set_param('ckt_gentoggle_8_sdeIdeal/library/copy.V/unzv_368','position',[462,505,512,525]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/copy.V','unz_368/1','unzv_368/2');
  add_line('ckt_gentoggle_8_sdeIdeal/library/copy.V','unzv_368/1','unza_368/2');
  add_line('ckt_gentoggle_8_sdeIdeal/library/copy.V','_X/1','unza_368/1');
  add_line('ckt_gentoggle_8_sdeIdeal/library/copy.V','const_366/1','unzv_368/1');
  add_line('ckt_gentoggle_8_sdeIdeal/library/copy.V','unza_368/1','_Y/1');
  %
  add_block('simulink/Ports & Subsystems/Subsystem','ckt_gentoggle_8_sdeIdeal/library/vtoi');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vtoi','position',[964,257,1014,277]);
  delete_line('ckt_gentoggle_8_sdeIdeal/library/vtoi','In1/1','Out1/1');
  delete_block('ckt_gentoggle_8_sdeIdeal/library/vtoi/In1');
  delete_block('ckt_gentoggle_8_sdeIdeal/library/vtoi/Out1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_8_sdeIdeal/library/vtoi/X');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_sdeIdeal/library/vtoi/_X');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vtoi/X','position',[887,529,937,549]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/vtoi','X/1','_X/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_8_sdeIdeal/library/vtoi/K');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_sdeIdeal/library/vtoi/_K');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vtoi/K','position',[823,232,873,252]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/vtoi','K/1','_K/1');
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_8_sdeIdeal/library/vtoi/Y');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_sdeIdeal/library/vtoi/_Y');
  add_line('ckt_gentoggle_8_sdeIdeal/library/vtoi','_Y/1','Y/1');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vtoi/Y','position',[587,148,637,168]);
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_sdeIdeal/library/vtoi/const_391');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vtoi/const_391','Value','1.');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vtoi/const_391','position',[269,944,319,964]);
  add_block('simulink/Math Operations/Product','ckt_gentoggle_8_sdeIdeal/library/vtoi/div_393');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vtoi/div_393','Inputs','*/');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vtoi/div_393','position',[15,63,65,83]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/vtoi','const_391/1','div_393/1');
  add_line('ckt_gentoggle_8_sdeIdeal/library/vtoi','_K/1','div_393/2');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_8_sdeIdeal/library/vtoi/mul_396');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vtoi/mul_396','Inputs','**');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vtoi/mul_396','position',[438,143,488,163]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/vtoi','div_393/1','mul_396/1');
  add_line('ckt_gentoggle_8_sdeIdeal/library/vtoi','_X/1','mul_396/2');
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_sdeIdeal/library/vtoi/const_399');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vtoi/const_399','Value','1e-06');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vtoi/const_399','position',[27,181,77,201]);
  add_block('simulink/Sources/Uniform Random Number','ckt_gentoggle_8_sdeIdeal/library/vtoi/unz_401');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_8_sdeIdeal/library/vtoi/unzv_401');
  add_block('simulink/Math Operations/Sum','ckt_gentoggle_8_sdeIdeal/library/vtoi/unza_401');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vtoi/unza_401','Inputs','++');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vtoi/unzv_401','Inputs','**');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vtoi/unz_401','position',[688,154,738,174]);
  set_param('ckt_gentoggle_8_sdeIdeal/library/vtoi/unza_401','position',[292,917,342,937]);
  set_param('ckt_gentoggle_8_sdeIdeal/library/vtoi/unzv_401','position',[845,593,895,613]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/vtoi','unz_401/1','unzv_401/2');
  add_line('ckt_gentoggle_8_sdeIdeal/library/vtoi','unzv_401/1','unza_401/2');
  add_line('ckt_gentoggle_8_sdeIdeal/library/vtoi','mul_396/1','unza_401/1');
  add_line('ckt_gentoggle_8_sdeIdeal/library/vtoi','const_399/1','unzv_401/1');
  add_line('ckt_gentoggle_8_sdeIdeal/library/vtoi','unza_401/1','_Y/1');
  %
  add_block('simulink/Ports & Subsystems/Subsystem','ckt_gentoggle_8_sdeIdeal/library/vadd');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vadd','position',[322,671,372,691]);
  delete_line('ckt_gentoggle_8_sdeIdeal/library/vadd','In1/1','Out1/1');
  delete_block('ckt_gentoggle_8_sdeIdeal/library/vadd/In1');
  delete_block('ckt_gentoggle_8_sdeIdeal/library/vadd/Out1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_8_sdeIdeal/library/vadd/OUT2_0');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_sdeIdeal/library/vadd/_OUT2_0');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vadd/OUT2_0','position',[283,331,333,351]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/vadd','OUT2_0/1','_OUT2_0/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_8_sdeIdeal/library/vadd/D');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_sdeIdeal/library/vadd/_D');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vadd/D','position',[566,303,616,323]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/vadd','D/1','_D/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_8_sdeIdeal/library/vadd/C');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_sdeIdeal/library/vadd/_C');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vadd/C','position',[846,436,896,456]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/vadd','C/1','_C/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_8_sdeIdeal/library/vadd/A');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_sdeIdeal/library/vadd/_A');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vadd/A','position',[687,140,737,160]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/vadd','A/1','_A/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_8_sdeIdeal/library/vadd/B');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_sdeIdeal/library/vadd/_B');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vadd/B','position',[896,94,946,114]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/vadd','B/1','_B/1');
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_8_sdeIdeal/library/vadd/OUT');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_sdeIdeal/library/vadd/_OUT');
  add_line('ckt_gentoggle_8_sdeIdeal/library/vadd','_OUT/1','OUT/1');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vadd/OUT','position',[514,248,564,268]);
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_8_sdeIdeal/library/vadd/OUT2');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_sdeIdeal/library/vadd/_OUT2');
  add_line('ckt_gentoggle_8_sdeIdeal/library/vadd','_OUT2/1','OUT2/1');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vadd/OUT2','position',[424,790,474,810]);
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_8_sdeIdeal/library/vadd/BSW');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_sdeIdeal/library/vadd/_BSW');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vadd/BSW','position',[144,911,194,931]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/vadd','BSW/1','_BSW/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_8_sdeIdeal/library/vadd/CSW');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_sdeIdeal/library/vadd/_CSW');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vadd/CSW','position',[341,696,391,716]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/vadd','CSW/1','_CSW/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_8_sdeIdeal/library/vadd/DSW');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_sdeIdeal/library/vadd/_DSW');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vadd/DSW','position',[202,894,252,914]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/vadd','DSW/1','_DSW/1');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_8_sdeIdeal/library/vadd/mul_458');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vadd/mul_458','Inputs','**');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vadd/mul_458','position',[523,777,573,797]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/vadd','_BSW/1','mul_458/1');
  add_line('ckt_gentoggle_8_sdeIdeal/library/vadd','_B/1','mul_458/2');
  add_block('simulink/Math Operations/Sum','ckt_gentoggle_8_sdeIdeal/library/vadd/sub_461');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vadd/sub_461','Inputs','++');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vadd/sub_461','position',[899,523,949,543]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/vadd','_A/1','sub_461/1');
  add_line('ckt_gentoggle_8_sdeIdeal/library/vadd','mul_458/1','sub_461/2');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_8_sdeIdeal/library/vadd/mul_464');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vadd/mul_464','Inputs','**');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vadd/mul_464','position',[344,251,394,271]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/vadd','_CSW/1','mul_464/1');
  add_line('ckt_gentoggle_8_sdeIdeal/library/vadd','_C/1','mul_464/2');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_8_sdeIdeal/library/vadd/mul_467');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vadd/mul_467','Inputs','**');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vadd/mul_467','position',[389,568,439,588]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/vadd','_DSW/1','mul_467/1');
  add_line('ckt_gentoggle_8_sdeIdeal/library/vadd','_D/1','mul_467/2');
  add_block('simulink/Math Operations/Sum','ckt_gentoggle_8_sdeIdeal/library/vadd/sum_470');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vadd/sum_470','Inputs','+--');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vadd/sum_470','position',[368,320,418,340]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/vadd','sub_461/1','sum_470/1');
  add_line('ckt_gentoggle_8_sdeIdeal/library/vadd','mul_464/1','sum_470/2');
  add_line('ckt_gentoggle_8_sdeIdeal/library/vadd','mul_467/1','sum_470/3');
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_sdeIdeal/library/vadd/const_474');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vadd/const_474','Value','0.25');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vadd/const_474','position',[754,938,804,958]);
  add_block('simulink/Math Operations/Product','ckt_gentoggle_8_sdeIdeal/library/vadd/mul_476');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vadd/mul_476','Inputs','**');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vadd/mul_476','position',[856,249,906,269]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/vadd','sum_470/1','mul_476/1');
  add_line('ckt_gentoggle_8_sdeIdeal/library/vadd','const_474/1','mul_476/2');
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_sdeIdeal/library/vadd/const_479');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vadd/const_479','Value','0.001');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vadd/const_479','position',[827,444,877,464]);
  add_block('simulink/Math Operations/Product','ckt_gentoggle_8_sdeIdeal/library/vadd/mul_481');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vadd/mul_481','Inputs','**');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vadd/mul_481','position',[298,662,348,682]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/vadd','const_479/1','mul_481/1');
  add_line('ckt_gentoggle_8_sdeIdeal/library/vadd','_OUT/1','mul_481/2');
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_sdeIdeal/library/vadd/const_484');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vadd/const_484','Value','0.1');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vadd/const_484','position',[223,258,273,278]);
  add_block('simulink/Math Operations/Sum','ckt_gentoggle_8_sdeIdeal/library/vadd/sub_486');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vadd/sub_486','Inputs','++');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vadd/sub_486','position',[318,364,368,384]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/vadd','mul_481/1','sub_486/1');
  add_line('ckt_gentoggle_8_sdeIdeal/library/vadd','const_484/1','sub_486/2');
  add_block('simulink/Sources/Uniform Random Number','ckt_gentoggle_8_sdeIdeal/library/vadd/unz_489');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_8_sdeIdeal/library/vadd/unzv_489');
  add_block('simulink/Math Operations/Sum','ckt_gentoggle_8_sdeIdeal/library/vadd/unza_489');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vadd/unza_489','Inputs','++');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vadd/unzv_489','Inputs','**');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vadd/unz_489','position',[926,524,976,544]);
  set_param('ckt_gentoggle_8_sdeIdeal/library/vadd/unza_489','position',[94,19,144,39]);
  set_param('ckt_gentoggle_8_sdeIdeal/library/vadd/unzv_489','position',[853,163,903,183]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/vadd','unz_489/1','unzv_489/2');
  add_line('ckt_gentoggle_8_sdeIdeal/library/vadd','unzv_489/1','unza_489/2');
  add_line('ckt_gentoggle_8_sdeIdeal/library/vadd','mul_476/1','unza_489/1');
  add_line('ckt_gentoggle_8_sdeIdeal/library/vadd','sub_486/1','unzv_489/1');
  add_line('ckt_gentoggle_8_sdeIdeal/library/vadd','unza_489/1','_OUT/1');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_8_sdeIdeal/library/vadd/mul_497');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vadd/mul_497','Inputs','**');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vadd/mul_497','position',[829,183,879,203]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/vadd','_BSW/1','mul_497/1');
  add_line('ckt_gentoggle_8_sdeIdeal/library/vadd','_B/1','mul_497/2');
  add_block('simulink/Math Operations/Sum','ckt_gentoggle_8_sdeIdeal/library/vadd/sub_500');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vadd/sub_500','Inputs','++');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vadd/sub_500','position',[540,655,590,675]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/vadd','_A/1','sub_500/1');
  add_line('ckt_gentoggle_8_sdeIdeal/library/vadd','mul_497/1','sub_500/2');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_8_sdeIdeal/library/vadd/mul_503');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vadd/mul_503','Inputs','**');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vadd/mul_503','position',[350,553,400,573]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/vadd','_CSW/1','mul_503/1');
  add_line('ckt_gentoggle_8_sdeIdeal/library/vadd','_C/1','mul_503/2');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_8_sdeIdeal/library/vadd/mul_506');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vadd/mul_506','Inputs','***');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vadd/mul_506','position',[743,386,793,406]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/vadd','_DSW/1','mul_506/1');
  add_line('ckt_gentoggle_8_sdeIdeal/library/vadd','_D/1','mul_506/2');
  add_line('ckt_gentoggle_8_sdeIdeal/library/vadd','_OUT2/1','mul_506/3');
  add_block('simulink/Math Operations/Sum','ckt_gentoggle_8_sdeIdeal/library/vadd/sum_510');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vadd/sum_510','Inputs','+--');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vadd/sum_510','position',[869,785,919,805]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/vadd','sub_500/1','sum_510/1');
  add_line('ckt_gentoggle_8_sdeIdeal/library/vadd','mul_503/1','sum_510/2');
  add_line('ckt_gentoggle_8_sdeIdeal/library/vadd','mul_506/1','sum_510/3');
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_sdeIdeal/library/vadd/const_514');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vadd/const_514','Value','0.25');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vadd/const_514','position',[944,146,994,166]);
  add_block('simulink/Math Operations/Product','ckt_gentoggle_8_sdeIdeal/library/vadd/mul_516');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vadd/mul_516','Inputs','**');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vadd/mul_516','position',[77,198,127,218]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/vadd','sum_510/1','mul_516/1');
  add_line('ckt_gentoggle_8_sdeIdeal/library/vadd','const_514/1','mul_516/2');
  add_block('simulink/Continuous/Integrator','ckt_gentoggle_8_sdeIdeal/library/vadd/int_519');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vadd/int_519','position',[501,438,551,458]);
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_sdeIdeal/library/vadd/const_521');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vadd/const_521','Value','0.001');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vadd/const_521','position',[882,938,932,958]);
  add_block('simulink/Math Operations/Product','ckt_gentoggle_8_sdeIdeal/library/vadd/mul_523');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vadd/mul_523','Inputs','**');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vadd/mul_523','position',[620,537,670,557]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/vadd','const_521/1','mul_523/1');
  add_line('ckt_gentoggle_8_sdeIdeal/library/vadd','_OUT2/1','mul_523/2');
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_sdeIdeal/library/vadd/const_526');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vadd/const_526','Value','0.1');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vadd/const_526','position',[316,891,366,911]);
  add_block('simulink/Math Operations/Sum','ckt_gentoggle_8_sdeIdeal/library/vadd/sub_528');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vadd/sub_528','Inputs','++');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vadd/sub_528','position',[63,370,113,390]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/vadd','mul_523/1','sub_528/1');
  add_line('ckt_gentoggle_8_sdeIdeal/library/vadd','const_526/1','sub_528/2');
  add_block('simulink/Sources/Uniform Random Number','ckt_gentoggle_8_sdeIdeal/library/vadd/unz_531');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_8_sdeIdeal/library/vadd/unzv_531');
  add_block('simulink/Math Operations/Sum','ckt_gentoggle_8_sdeIdeal/library/vadd/unza_531');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vadd/unza_531','Inputs','++');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vadd/unzv_531','Inputs','**');
  set_param('ckt_gentoggle_8_sdeIdeal/library/vadd/unz_531','position',[598,839,648,859]);
  set_param('ckt_gentoggle_8_sdeIdeal/library/vadd/unza_531','position',[790,280,840,300]);
  set_param('ckt_gentoggle_8_sdeIdeal/library/vadd/unzv_531','position',[883,778,933,798]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/vadd','unz_531/1','unzv_531/2');
  add_line('ckt_gentoggle_8_sdeIdeal/library/vadd','unzv_531/1','unza_531/2');
  add_line('ckt_gentoggle_8_sdeIdeal/library/vadd','mul_516/1','unza_531/1');
  add_line('ckt_gentoggle_8_sdeIdeal/library/vadd','sub_528/1','unzv_531/1');
  add_line('ckt_gentoggle_8_sdeIdeal/library/vadd','unza_531/1','int_519/1');
  add_line('ckt_gentoggle_8_sdeIdeal/library/vadd','int_519/1','_OUT2/1');
  %
  add_block('simulink/Ports & Subsystems/Subsystem','ckt_gentoggle_8_sdeIdeal/library/copy.I');
  set_param('ckt_gentoggle_8_sdeIdeal/library/copy.I','position',[454,954,504,974]);
  delete_line('ckt_gentoggle_8_sdeIdeal/library/copy.I','In1/1','Out1/1');
  delete_block('ckt_gentoggle_8_sdeIdeal/library/copy.I/In1');
  delete_block('ckt_gentoggle_8_sdeIdeal/library/copy.I/Out1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_8_sdeIdeal/library/copy.I/X');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_sdeIdeal/library/copy.I/_X');
  set_param('ckt_gentoggle_8_sdeIdeal/library/copy.I/X','position',[426,332,476,352]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/copy.I','X/1','_X/1');
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_8_sdeIdeal/library/copy.I/Y');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_sdeIdeal/library/copy.I/_Y');
  add_line('ckt_gentoggle_8_sdeIdeal/library/copy.I','_Y/1','Y/1');
  set_param('ckt_gentoggle_8_sdeIdeal/library/copy.I/Y','position',[36,916,86,936]);
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_sdeIdeal/library/copy.I/const_549');
  set_param('ckt_gentoggle_8_sdeIdeal/library/copy.I/const_549','Value','1e-05');
  set_param('ckt_gentoggle_8_sdeIdeal/library/copy.I/const_549','position',[512,723,562,743]);
  add_block('simulink/Math Operations/Product','ckt_gentoggle_8_sdeIdeal/library/copy.I/mul_551');
  set_param('ckt_gentoggle_8_sdeIdeal/library/copy.I/mul_551','Inputs','**');
  set_param('ckt_gentoggle_8_sdeIdeal/library/copy.I/mul_551','position',[230,507,280,527]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/copy.I','_Y/1','mul_551/1');
  add_line('ckt_gentoggle_8_sdeIdeal/library/copy.I','const_549/1','mul_551/2');
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_sdeIdeal/library/copy.I/const_554');
  set_param('ckt_gentoggle_8_sdeIdeal/library/copy.I/const_554','Value','0.0001');
  set_param('ckt_gentoggle_8_sdeIdeal/library/copy.I/const_554','position',[594,880,644,900]);
  add_block('simulink/Math Operations/Sum','ckt_gentoggle_8_sdeIdeal/library/copy.I/sub_556');
  set_param('ckt_gentoggle_8_sdeIdeal/library/copy.I/sub_556','Inputs','++');
  set_param('ckt_gentoggle_8_sdeIdeal/library/copy.I/sub_556','position',[47,752,97,772]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/copy.I','mul_551/1','sub_556/1');
  add_line('ckt_gentoggle_8_sdeIdeal/library/copy.I','const_554/1','sub_556/2');
  add_block('simulink/Sources/Uniform Random Number','ckt_gentoggle_8_sdeIdeal/library/copy.I/unz_559');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_8_sdeIdeal/library/copy.I/unzv_559');
  add_block('simulink/Math Operations/Sum','ckt_gentoggle_8_sdeIdeal/library/copy.I/unza_559');
  set_param('ckt_gentoggle_8_sdeIdeal/library/copy.I/unza_559','Inputs','++');
  set_param('ckt_gentoggle_8_sdeIdeal/library/copy.I/unzv_559','Inputs','**');
  set_param('ckt_gentoggle_8_sdeIdeal/library/copy.I/unz_559','position',[860,565,910,585]);
  set_param('ckt_gentoggle_8_sdeIdeal/library/copy.I/unza_559','position',[490,712,540,732]);
  set_param('ckt_gentoggle_8_sdeIdeal/library/copy.I/unzv_559','position',[231,384,281,404]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/copy.I','unz_559/1','unzv_559/2');
  add_line('ckt_gentoggle_8_sdeIdeal/library/copy.I','unzv_559/1','unza_559/2');
  add_line('ckt_gentoggle_8_sdeIdeal/library/copy.I','_X/1','unza_559/1');
  add_line('ckt_gentoggle_8_sdeIdeal/library/copy.I','sub_556/1','unzv_559/1');
  add_line('ckt_gentoggle_8_sdeIdeal/library/copy.I','unza_559/1','_Y/1');
  %
  add_block('simulink/Ports & Subsystems/Subsystem','ckt_gentoggle_8_sdeIdeal/library/iadd');
  set_param('ckt_gentoggle_8_sdeIdeal/library/iadd','position',[919,549,969,569]);
  delete_line('ckt_gentoggle_8_sdeIdeal/library/iadd','In1/1','Out1/1');
  delete_block('ckt_gentoggle_8_sdeIdeal/library/iadd/In1');
  delete_block('ckt_gentoggle_8_sdeIdeal/library/iadd/Out1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_8_sdeIdeal/library/iadd/D');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_sdeIdeal/library/iadd/_D');
  set_param('ckt_gentoggle_8_sdeIdeal/library/iadd/D','position',[522,557,572,577]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/iadd','D/1','_D/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_8_sdeIdeal/library/iadd/C');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_sdeIdeal/library/iadd/_C');
  set_param('ckt_gentoggle_8_sdeIdeal/library/iadd/C','position',[16,102,66,122]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/iadd','C/1','_C/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_8_sdeIdeal/library/iadd/A');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_sdeIdeal/library/iadd/_A');
  set_param('ckt_gentoggle_8_sdeIdeal/library/iadd/A','position',[941,625,991,645]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/iadd','A/1','_A/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_8_sdeIdeal/library/iadd/B');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_sdeIdeal/library/iadd/_B');
  set_param('ckt_gentoggle_8_sdeIdeal/library/iadd/B','position',[524,326,574,346]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/iadd','B/1','_B/1');
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_8_sdeIdeal/library/iadd/OUT');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_sdeIdeal/library/iadd/_OUT');
  add_line('ckt_gentoggle_8_sdeIdeal/library/iadd','_OUT/1','OUT/1');
  set_param('ckt_gentoggle_8_sdeIdeal/library/iadd/OUT','position',[355,249,405,269]);
  add_block('simulink/Math Operations/Sum','ckt_gentoggle_8_sdeIdeal/library/iadd/sub_592');
  set_param('ckt_gentoggle_8_sdeIdeal/library/iadd/sub_592','Inputs','++');
  set_param('ckt_gentoggle_8_sdeIdeal/library/iadd/sub_592','position',[279,361,329,381]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/iadd','_A/1','sub_592/1');
  add_line('ckt_gentoggle_8_sdeIdeal/library/iadd','_B/1','sub_592/2');
  add_block('simulink/Math Operations/Sum','ckt_gentoggle_8_sdeIdeal/library/iadd/sum_595');
  set_param('ckt_gentoggle_8_sdeIdeal/library/iadd/sum_595','Inputs','+--');
  set_param('ckt_gentoggle_8_sdeIdeal/library/iadd/sum_595','position',[62,442,112,462]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/iadd','sub_592/1','sum_595/1');
  add_line('ckt_gentoggle_8_sdeIdeal/library/iadd','_C/1','sum_595/2');
  add_line('ckt_gentoggle_8_sdeIdeal/library/iadd','_D/1','sum_595/3');
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_sdeIdeal/library/iadd/const_599');
  set_param('ckt_gentoggle_8_sdeIdeal/library/iadd/const_599','Value','1e-05');
  set_param('ckt_gentoggle_8_sdeIdeal/library/iadd/const_599','position',[75,987,125,1007]);
  add_block('simulink/Math Operations/Product','ckt_gentoggle_8_sdeIdeal/library/iadd/mul_601');
  set_param('ckt_gentoggle_8_sdeIdeal/library/iadd/mul_601','Inputs','**');
  set_param('ckt_gentoggle_8_sdeIdeal/library/iadd/mul_601','position',[135,569,185,589]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/iadd','const_599/1','mul_601/1');
  add_line('ckt_gentoggle_8_sdeIdeal/library/iadd','_OUT/1','mul_601/2');
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_sdeIdeal/library/iadd/const_604');
  set_param('ckt_gentoggle_8_sdeIdeal/library/iadd/const_604','Value','0.001');
  set_param('ckt_gentoggle_8_sdeIdeal/library/iadd/const_604','position',[15,728,65,748]);
  add_block('simulink/Math Operations/Sum','ckt_gentoggle_8_sdeIdeal/library/iadd/sub_606');
  set_param('ckt_gentoggle_8_sdeIdeal/library/iadd/sub_606','Inputs','++');
  set_param('ckt_gentoggle_8_sdeIdeal/library/iadd/sub_606','position',[470,643,520,663]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/iadd','mul_601/1','sub_606/1');
  add_line('ckt_gentoggle_8_sdeIdeal/library/iadd','const_604/1','sub_606/2');
  add_block('simulink/Sources/Uniform Random Number','ckt_gentoggle_8_sdeIdeal/library/iadd/unz_609');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_8_sdeIdeal/library/iadd/unzv_609');
  add_block('simulink/Math Operations/Sum','ckt_gentoggle_8_sdeIdeal/library/iadd/unza_609');
  set_param('ckt_gentoggle_8_sdeIdeal/library/iadd/unza_609','Inputs','++');
  set_param('ckt_gentoggle_8_sdeIdeal/library/iadd/unzv_609','Inputs','**');
  set_param('ckt_gentoggle_8_sdeIdeal/library/iadd/unz_609','position',[445,667,495,687]);
  set_param('ckt_gentoggle_8_sdeIdeal/library/iadd/unza_609','position',[242,161,292,181]);
  set_param('ckt_gentoggle_8_sdeIdeal/library/iadd/unzv_609','position',[219,705,269,725]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/iadd','unz_609/1','unzv_609/2');
  add_line('ckt_gentoggle_8_sdeIdeal/library/iadd','unzv_609/1','unza_609/2');
  add_line('ckt_gentoggle_8_sdeIdeal/library/iadd','sum_595/1','unza_609/1');
  add_line('ckt_gentoggle_8_sdeIdeal/library/iadd','sub_606/1','unzv_609/1');
  add_line('ckt_gentoggle_8_sdeIdeal/library/iadd','unza_609/1','_OUT/1');
  %
  add_block('simulink/Ports & Subsystems/Subsystem','ckt_gentoggle_8_sdeIdeal/library/input.I');
  set_param('ckt_gentoggle_8_sdeIdeal/library/input.I','position',[836,823,886,843]);
  delete_line('ckt_gentoggle_8_sdeIdeal/library/input.I','In1/1','Out1/1');
  delete_block('ckt_gentoggle_8_sdeIdeal/library/input.I/In1');
  delete_block('ckt_gentoggle_8_sdeIdeal/library/input.I/Out1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_8_sdeIdeal/library/input.I/X');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_sdeIdeal/library/input.I/_X');
  set_param('ckt_gentoggle_8_sdeIdeal/library/input.I/X','position',[530,907,580,927]);
  add_block('simulink/Discontinuities/Quantizer','ckt_gentoggle_8_sdeIdeal/library/input.I/smp_623');
  set_param('ckt_gentoggle_8_sdeIdeal/library/input.I/smp_623','QuantizationInterval','1e-05');
  set_param('ckt_gentoggle_8_sdeIdeal/library/input.I/smp_623','position',[65,582,115,602]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/input.I','X/1','smp_623/1');
  add_line('ckt_gentoggle_8_sdeIdeal/library/input.I','smp_623/1','_X/1');
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_8_sdeIdeal/library/input.I/O');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_sdeIdeal/library/input.I/_O');
  add_line('ckt_gentoggle_8_sdeIdeal/library/input.I','_O/1','O/1');
  set_param('ckt_gentoggle_8_sdeIdeal/library/input.I/O','position',[139,636,189,656]);
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_sdeIdeal/library/input.I/const_629');
  set_param('ckt_gentoggle_8_sdeIdeal/library/input.I/const_629','Value','0.');
  set_param('ckt_gentoggle_8_sdeIdeal/library/input.I/const_629','position',[436,372,486,392]);
  add_block('simulink/Sources/Uniform Random Number','ckt_gentoggle_8_sdeIdeal/library/input.I/unz_631');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_8_sdeIdeal/library/input.I/unzv_631');
  add_block('simulink/Math Operations/Sum','ckt_gentoggle_8_sdeIdeal/library/input.I/unza_631');
  set_param('ckt_gentoggle_8_sdeIdeal/library/input.I/unza_631','Inputs','++');
  set_param('ckt_gentoggle_8_sdeIdeal/library/input.I/unzv_631','Inputs','**');
  set_param('ckt_gentoggle_8_sdeIdeal/library/input.I/unz_631','position',[166,558,216,578]);
  set_param('ckt_gentoggle_8_sdeIdeal/library/input.I/unza_631','position',[18,867,68,887]);
  set_param('ckt_gentoggle_8_sdeIdeal/library/input.I/unzv_631','position',[347,503,397,523]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/input.I','unz_631/1','unzv_631/2');
  add_line('ckt_gentoggle_8_sdeIdeal/library/input.I','unzv_631/1','unza_631/2');
  add_line('ckt_gentoggle_8_sdeIdeal/library/input.I','_X/1','unza_631/1');
  add_line('ckt_gentoggle_8_sdeIdeal/library/input.I','const_629/1','unzv_631/1');
  add_line('ckt_gentoggle_8_sdeIdeal/library/input.I','unza_631/1','_O/1');
  %
  add_block('simulink/Ports & Subsystems/Subsystem','ckt_gentoggle_8_sdeIdeal/library/igenebind');
  set_param('ckt_gentoggle_8_sdeIdeal/library/igenebind','position',[925,829,975,849]);
  delete_line('ckt_gentoggle_8_sdeIdeal/library/igenebind','In1/1','Out1/1');
  delete_block('ckt_gentoggle_8_sdeIdeal/library/igenebind/In1');
  delete_block('ckt_gentoggle_8_sdeIdeal/library/igenebind/Out1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_8_sdeIdeal/library/igenebind/TF');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_sdeIdeal/library/igenebind/_TF');
  set_param('ckt_gentoggle_8_sdeIdeal/library/igenebind/TF','position',[132,108,182,128]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/igenebind','TF/1','_TF/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_8_sdeIdeal/library/igenebind/K');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_sdeIdeal/library/igenebind/_K');
  set_param('ckt_gentoggle_8_sdeIdeal/library/igenebind/K','position',[603,993,653,1013]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/igenebind','K/1','_K/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_8_sdeIdeal/library/igenebind/Vmax');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_sdeIdeal/library/igenebind/_Vmax');
  set_param('ckt_gentoggle_8_sdeIdeal/library/igenebind/Vmax','position',[30,495,80,515]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/igenebind','Vmax/1','_Vmax/1');
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_8_sdeIdeal/library/igenebind/GE');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_8_sdeIdeal/library/igenebind/_GE');
  add_line('ckt_gentoggle_8_sdeIdeal/library/igenebind','_GE/1','GE/1');
  set_param('ckt_gentoggle_8_sdeIdeal/library/igenebind/GE','position',[221,700,271,720]);
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_sdeIdeal/library/igenebind/const_659');
  set_param('ckt_gentoggle_8_sdeIdeal/library/igenebind/const_659','Value','1.');
  set_param('ckt_gentoggle_8_sdeIdeal/library/igenebind/const_659','position',[877,562,927,582]);
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_sdeIdeal/library/igenebind/const_661');
  set_param('ckt_gentoggle_8_sdeIdeal/library/igenebind/const_661','Value','1.');
  set_param('ckt_gentoggle_8_sdeIdeal/library/igenebind/const_661','position',[806,947,856,967]);
  add_block('simulink/Math Operations/Product','ckt_gentoggle_8_sdeIdeal/library/igenebind/mul_663');
  set_param('ckt_gentoggle_8_sdeIdeal/library/igenebind/mul_663','Inputs','**');
  set_param('ckt_gentoggle_8_sdeIdeal/library/igenebind/mul_663','position',[452,229,502,249]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/igenebind','_K/1','mul_663/1');
  add_line('ckt_gentoggle_8_sdeIdeal/library/igenebind','_TF/1','mul_663/2');
  add_block('simulink/Math Operations/Sum','ckt_gentoggle_8_sdeIdeal/library/igenebind/sub_666');
  set_param('ckt_gentoggle_8_sdeIdeal/library/igenebind/sub_666','Inputs','++');
  set_param('ckt_gentoggle_8_sdeIdeal/library/igenebind/sub_666','position',[427,968,477,988]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/igenebind','const_661/1','sub_666/1');
  add_line('ckt_gentoggle_8_sdeIdeal/library/igenebind','mul_663/1','sub_666/2');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_8_sdeIdeal/library/igenebind/div_669');
  set_param('ckt_gentoggle_8_sdeIdeal/library/igenebind/div_669','Inputs','*/');
  set_param('ckt_gentoggle_8_sdeIdeal/library/igenebind/div_669','position',[820,49,870,69]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/igenebind','const_659/1','div_669/1');
  add_line('ckt_gentoggle_8_sdeIdeal/library/igenebind','sub_666/1','div_669/2');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_8_sdeIdeal/library/igenebind/mul_672');
  set_param('ckt_gentoggle_8_sdeIdeal/library/igenebind/mul_672','Inputs','**');
  set_param('ckt_gentoggle_8_sdeIdeal/library/igenebind/mul_672','position',[3,576,53,596]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/igenebind','_Vmax/1','mul_672/1');
  add_line('ckt_gentoggle_8_sdeIdeal/library/igenebind','div_669/1','mul_672/2');
  add_block('simulink/Sources/Constant','ckt_gentoggle_8_sdeIdeal/library/igenebind/const_675');
  set_param('ckt_gentoggle_8_sdeIdeal/library/igenebind/const_675','Value','0.');
  set_param('ckt_gentoggle_8_sdeIdeal/library/igenebind/const_675','position',[812,402,862,422]);
  add_block('simulink/Sources/Uniform Random Number','ckt_gentoggle_8_sdeIdeal/library/igenebind/unz_677');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_8_sdeIdeal/library/igenebind/unzv_677');
  add_block('simulink/Math Operations/Sum','ckt_gentoggle_8_sdeIdeal/library/igenebind/unza_677');
  set_param('ckt_gentoggle_8_sdeIdeal/library/igenebind/unza_677','Inputs','++');
  set_param('ckt_gentoggle_8_sdeIdeal/library/igenebind/unzv_677','Inputs','**');
  set_param('ckt_gentoggle_8_sdeIdeal/library/igenebind/unz_677','position',[540,689,590,709]);
  set_param('ckt_gentoggle_8_sdeIdeal/library/igenebind/unza_677','position',[632,253,682,273]);
  set_param('ckt_gentoggle_8_sdeIdeal/library/igenebind/unzv_677','position',[404,140,454,160]);
  add_line('ckt_gentoggle_8_sdeIdeal/library/igenebind','unz_677/1','unzv_677/2');
  add_line('ckt_gentoggle_8_sdeIdeal/library/igenebind','unzv_677/1','unza_677/2');
  add_line('ckt_gentoggle_8_sdeIdeal/library/igenebind','mul_672/1','unza_677/1');
  add_line('ckt_gentoggle_8_sdeIdeal/library/igenebind','const_675/1','unzv_677/1');
  add_line('ckt_gentoggle_8_sdeIdeal/library/igenebind','unza_677/1','_GE/1');
end
%
%
%
