%toplevel script
function main()
  preamble();
  build_comp_library();
  build_circuit();
end
%
%
%circuit build script
function build_circuit()
  add_block('simulink/Ports & Subsystems/Subsystem','ckt_gentoggle_0_odeIdeal/circuit');
  set_param('ckt_gentoggle_0_odeIdeal/circuit','position',[136,304,186,324]);
  delete_line('ckt_gentoggle_0_odeIdeal/circuit','In1/1','Out1/1');
  delete_block('ckt_gentoggle_0_odeIdeal/circuit/In1');
  delete_block('ckt_gentoggle_0_odeIdeal/circuit/Out1');
  add_block('ckt_gentoggle_0_odeIdeal/library/vgain','ckt_gentoggle_0_odeIdeal/circuit/vgain[6]');
  add_block('ckt_gentoggle_0_odeIdeal/library/vgain','ckt_gentoggle_0_odeIdeal/circuit/vgain[14]');
  add_block('ckt_gentoggle_0_odeIdeal/library/switch','ckt_gentoggle_0_odeIdeal/circuit/switch[16]');
  add_block('ckt_gentoggle_0_odeIdeal/library/switch','ckt_gentoggle_0_odeIdeal/circuit/switch[1]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.I','ckt_gentoggle_0_odeIdeal/circuit/input.I[2]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.I','ckt_gentoggle_0_odeIdeal/circuit/input.I[20]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.I','ckt_gentoggle_0_odeIdeal/circuit/input.I[29]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.I','ckt_gentoggle_0_odeIdeal/circuit/input.I[8]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.I','ckt_gentoggle_0_odeIdeal/circuit/input.I[7]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.I','ckt_gentoggle_0_odeIdeal/circuit/input.I[13]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.I','ckt_gentoggle_0_odeIdeal/circuit/input.I[12]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.I','ckt_gentoggle_0_odeIdeal/circuit/input.I[31]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.I','ckt_gentoggle_0_odeIdeal/circuit/input.I[9]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.I','ckt_gentoggle_0_odeIdeal/circuit/input.I[0]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.I','ckt_gentoggle_0_odeIdeal/circuit/input.I[11]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.I','ckt_gentoggle_0_odeIdeal/circuit/input.I[10]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.I','ckt_gentoggle_0_odeIdeal/circuit/input.I[15]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.I','ckt_gentoggle_0_odeIdeal/circuit/input.I[6]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.I','ckt_gentoggle_0_odeIdeal/circuit/input.I[14]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.I','ckt_gentoggle_0_odeIdeal/circuit/input.I[21]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.I','ckt_gentoggle_0_odeIdeal/circuit/input.I[16]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.I','ckt_gentoggle_0_odeIdeal/circuit/input.I[30]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.I','ckt_gentoggle_0_odeIdeal/circuit/input.I[3]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.I','ckt_gentoggle_0_odeIdeal/circuit/input.I[4]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.I','ckt_gentoggle_0_odeIdeal/circuit/input.I[5]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.I','ckt_gentoggle_0_odeIdeal/circuit/input.I[1]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.I','ckt_gentoggle_0_odeIdeal/circuit/input.I[17]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.I','ckt_gentoggle_0_odeIdeal/circuit/input.I[32]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.I','ckt_gentoggle_0_odeIdeal/circuit/input.I[18]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.I','ckt_gentoggle_0_odeIdeal/circuit/input.I[19]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.I','ckt_gentoggle_0_odeIdeal/circuit/input.I[22]');
  add_block('ckt_gentoggle_0_odeIdeal/library/output.V','ckt_gentoggle_0_odeIdeal/circuit/output.V[0]');
  add_block('ckt_gentoggle_0_odeIdeal/library/output.V','ckt_gentoggle_0_odeIdeal/circuit/output.V[1]');
  add_block('ckt_gentoggle_0_odeIdeal/library/vadd','ckt_gentoggle_0_odeIdeal/circuit/vadd[7]');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_468');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_468','Value','1.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_468','position',[600,310,650,330]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_468/1','vadd[7]/6');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_470');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_470','Value','1.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_470','position',[916,479,966,499]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_470/1','vadd[7]/7');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_472');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_472','Value','1.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_472','position',[432,273,482,293]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_472/1','vadd[7]/8');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/vadd[7]/int_375','InitialCondition','0.');
  add_block('ckt_gentoggle_0_odeIdeal/library/vadd','ckt_gentoggle_0_odeIdeal/circuit/vadd[5]');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_474');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_474','Value','1.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_474','position',[559,754,609,774]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_474/1','vadd[5]/6');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_476');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_476','Value','1.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_476','position',[414,58,464,78]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_476/1','vadd[5]/7');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_478');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_478','Value','1.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_478','position',[410,865,460,885]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_478/1','vadd[5]/8');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/vadd[5]/int_375','InitialCondition','0.');
  add_block('ckt_gentoggle_0_odeIdeal/library/vtoi','ckt_gentoggle_0_odeIdeal/circuit/vtoi[13]');
  add_block('ckt_gentoggle_0_odeIdeal/library/vtoi','ckt_gentoggle_0_odeIdeal/circuit/vtoi[9]');
  add_block('ckt_gentoggle_0_odeIdeal/library/vtoi','ckt_gentoggle_0_odeIdeal/circuit/vtoi[0]');
  add_block('ckt_gentoggle_0_odeIdeal/library/igenebind','ckt_gentoggle_0_odeIdeal/circuit/igenebind[8]');
  add_block('ckt_gentoggle_0_odeIdeal/library/igenebind','ckt_gentoggle_0_odeIdeal/circuit/igenebind[10]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.V','ckt_gentoggle_0_odeIdeal/circuit/input.V[2]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.V','ckt_gentoggle_0_odeIdeal/circuit/input.V[8]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.V','ckt_gentoggle_0_odeIdeal/circuit/input.V[7]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.V','ckt_gentoggle_0_odeIdeal/circuit/input.V[13]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.V','ckt_gentoggle_0_odeIdeal/circuit/input.V[12]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.V','ckt_gentoggle_0_odeIdeal/circuit/input.V[9]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.V','ckt_gentoggle_0_odeIdeal/circuit/input.V[0]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.V','ckt_gentoggle_0_odeIdeal/circuit/input.V[11]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.V','ckt_gentoggle_0_odeIdeal/circuit/input.V[10]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.V','ckt_gentoggle_0_odeIdeal/circuit/input.V[15]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.V','ckt_gentoggle_0_odeIdeal/circuit/input.V[6]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.V','ckt_gentoggle_0_odeIdeal/circuit/input.V[14]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.V','ckt_gentoggle_0_odeIdeal/circuit/input.V[16]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.V','ckt_gentoggle_0_odeIdeal/circuit/input.V[3]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.V','ckt_gentoggle_0_odeIdeal/circuit/input.V[4]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.V','ckt_gentoggle_0_odeIdeal/circuit/input.V[5]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.V','ckt_gentoggle_0_odeIdeal/circuit/input.V[1]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.V','ckt_gentoggle_0_odeIdeal/circuit/input.V[17]');
  add_block('ckt_gentoggle_0_odeIdeal/library/input.V','ckt_gentoggle_0_odeIdeal/circuit/input.V[18]');
  add_block('ckt_gentoggle_0_odeIdeal/library/itov','ckt_gentoggle_0_odeIdeal/circuit/itov[15]');
  add_block('ckt_gentoggle_0_odeIdeal/library/itov','ckt_gentoggle_0_odeIdeal/circuit/itov[16]');
  add_block('ckt_gentoggle_0_odeIdeal/library/itov','ckt_gentoggle_0_odeIdeal/circuit/itov[4]');
  add_block('ckt_gentoggle_0_odeIdeal/library/iadd','ckt_gentoggle_0_odeIdeal/circuit/iadd[2]');
  add_block('ckt_gentoggle_0_odeIdeal/library/iadd','ckt_gentoggle_0_odeIdeal/circuit/iadd[12]');
  add_block('ckt_gentoggle_0_odeIdeal/library/iadd','ckt_gentoggle_0_odeIdeal/circuit/iadd[11]');
  add_block('ckt_gentoggle_0_odeIdeal/library/iadd','ckt_gentoggle_0_odeIdeal/circuit/iadd[3]');
  add_block('ckt_gentoggle_0_odeIdeal/library/iadd','ckt_gentoggle_0_odeIdeal/circuit/iadd[17]');
  add_block('ckt_gentoggle_0_odeIdeal/library/iadd','ckt_gentoggle_0_odeIdeal/circuit/iadd[18]');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','switch[1]/1','iadd[18]/3');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.I[0]/1','igenebind[10]/3');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.I[22]/1','switch[16]/4');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.V[15]/1','vgain[6]/1');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.I[32]/1','itov[16]/1');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.V[13]/1','vgain[6]/2');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','vgain[14]/1','vtoi[13]/2');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.V[14]/1','vtoi[0]/1');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','vtoi[0]/1','iadd[3]/4');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','iadd[12]/1','iadd[11]/4');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.I[30]/1','iadd[18]/4');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.V[11]/1','vadd[5]/2');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.I[14]/1','iadd[17]/4');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','itov[15]/1','vgain[14]/3');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','switch[16]/1','itov[15]/1');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','vadd[5]/2','output.V[1]/1');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','vadd[5]/2','switch[1]/4');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.I[10]/1','iadd[11]/2');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.I[12]/1','iadd[12]/3');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','iadd[11]/1','igenebind[10]/1');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.I[7]/1','iadd[3]/2');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','iadd[3]/1','iadd[2]/4');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','iadd[17]/1','switch[16]/2');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','iadd[18]/1','igenebind[8]/2');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','iadd[2]/1','switch[1]/3');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.I[8]/1','iadd[11]/1');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.I[21]/1','iadd[17]/2');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','itov[16]/1','vgain[6]/3');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.V[16]/1','vtoi[13]/1');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.V[5]/1','vadd[7]/4');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','vtoi[9]/1','iadd[17]/1');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.V[6]/1','vadd[7]/3');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.I[11]/1','iadd[12]/1');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','vadd[7]/2','output.V[0]/1');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','vadd[7]/2','vtoi[9]/1');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.V[17]/1','vgain[14]/2');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.I[6]/1','iadd[3]/3');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.I[31]/1','iadd[18]/1');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.V[9]/1','vtoi[9]/2');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','vtoi[13]/1','iadd[12]/4');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','igenebind[8]/1','itov[16]/2');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.I[18]/1','igenebind[8]/1');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.I[9]/1','iadd[11]/3');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.I[4]/1','iadd[2]/2');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','igenebind[10]/1','itov[4]/2');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.I[16]/1','switch[1]/2');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.I[3]/1','iadd[2]/3');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','vgain[6]/1','vadd[7]/5');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.I[5]/1','iadd[3]/1');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.V[8]/1','vadd[5]/1');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.I[2]/1','iadd[2]/1');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.V[12]/1','switch[1]/1');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.I[29]/1','iadd[18]/2');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.I[20]/1','switch[16]/3');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.V[3]/1','vadd[5]/4');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.V[2]/1','switch[16]/1');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.I[15]/1','iadd[17]/3');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.I[1]/1','igenebind[8]/3');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.I[13]/1','iadd[12]/2');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.V[1]/1','vgain[14]/1');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.I[17]/1','itov[4]/1');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.V[7]/1','vadd[7]/1');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.V[10]/1','vadd[7]/2');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.V[0]/1','vtoi[0]/2');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.V[18]/1','itov[15]/2');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','itov[4]/1','vadd[5]/5');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.I[19]/1','igenebind[10]/2');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.V[4]/1','vadd[5]/3');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/circuit/input.V[0]_in');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/circuit/_input.V[0]_in');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/input.V[0]_in','position',[342,220,392,240]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','input.V[0]_in/1','_input.V[0]_in/1');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','_input.V[0]_in/1','input.V[0]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_485');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_485','Value','2.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_485','position',[561,469,611,489]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_485/1','input.V[1]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_487');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_487','Value','0.15625');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_487','position',[166,594,216,614]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_487/1','input.I[0]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_489');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_489','Value','1250.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_489','position',[613,169,663,189]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_489/1','input.V[2]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_491');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_491','Value','0.0156');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_491','position',[203,509,253,529]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_491/1','input.I[1]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_493');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_493','Value','0.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_493','position',[348,487,398,507]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_493/1','input.I[29]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_495');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_495','Value','0.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_495','position',[174,97,224,117]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_495/1','input.I[30]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_497');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_497','Value','0.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_497','position',[38,839,88,859]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_497/1','input.I[31]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_499');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_499','Value','0.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_499','position',[750,366,800,386]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_499/1','input.I[2]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_501');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_501','Value','0.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_501','position',[477,971,527,991]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_501/1','input.I[3]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_503');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_503','Value','0.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_503','position',[67,156,117,176]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_503/1','input.I[4]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_505');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_505','Value','0.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_505','position',[879,910,929,930]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_505/1','input.I[5]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_507');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_507','Value','0.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_507','position',[994,289,1044,309]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_507/1','input.I[6]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_509');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_509','Value','0.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_509','position',[791,993,841,1013]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_509/1','input.I[7]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_511');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_511','Value','0.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_511','position',[471,575,521,595]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_511/1','input.V[3]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_513');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_513','Value','0.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_513','position',[286,855,336,875]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_513/1','input.V[4]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_515');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_515','Value','0.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_515','position',[509,752,559,772]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_515/1','input.V[5]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_517');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_517','Value','0.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_517','position',[470,320,520,340]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_517/1','input.V[6]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_519');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_519','Value','0.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_519','position',[934,516,984,536]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_519/1','input.I[8]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_521');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_521','Value','0.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_521','position',[975,139,1025,159]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_521/1','input.I[9]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_523');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_523','Value','0.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_523','position',[986,471,1036,491]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_523/1','input.I[10]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_525');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_525','Value','0.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_525','position',[561,491,611,511]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_525/1','input.I[11]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_527');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_527','Value','0.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_527','position',[306,775,356,795]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_527/1','input.I[12]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_529');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_529','Value','0.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_529','position',[796,134,846,154]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_529/1','input.I[13]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_531');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_531','Value','0.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_531','position',[724,369,774,389]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_531/1','input.I[14]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_533');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_533','Value','0.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_533','position',[380,221,430,241]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_533/1','input.I[15]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_535');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_535','Value','0.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_535','position',[948,644,998,664]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_535/1','input.V[7]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_537');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_537','Value','0.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_537','position',[661,269,711,289]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_537/1','input.V[8]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_539');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_539','Value','337.632520764');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_539','position',[615,532,665,552]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_539/1','input.I[16]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_541');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_541','Value','-1.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_541','position',[371,552,421,572]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_541/1','input.V[9]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_543');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_543','Value','4000.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_543','position',[222,823,272,843]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_543/1','input.I[17]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_545');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_545','Value','4.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_545','position',[243,896,293,916]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_545/1','input.V[10]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_547');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_547','Value','4.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_547','position',[5,714,55,734]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_547/1','input.V[11]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_549');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_549','Value','1000.75');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_549','position',[611,820,661,840]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_549/1','input.V[12]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_551');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_551','Value','0.000125');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_551','position',[153,98,203,118]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_551/1','input.V[13]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_553');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_553','Value','1.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_553','position',[11,5,61,25]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_553/1','input.I[32]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_555');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_555','Value','1.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_555','position',[478,891,528,911]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_555/1','input.V[14]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_557');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_557','Value','1.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_557','position',[121,201,171,221]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_557/1','input.V[15]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_559');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_559','Value','1.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_559','position',[39,527,89,547]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_559/1','input.I[18]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_561');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_561','Value','1.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_561','position',[821,675,871,695]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_561/1','input.I[19]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_563');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_563','Value','1.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_563','position',[224,727,274,747]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_563/1','input.V[16]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_565');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_565','Value','1.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_565','position',[216,177,266,197]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_565/1','input.V[17]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_567');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_567','Value','1.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_567','position',[324,615,374,635]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_567/1','input.V[18]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_569');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_569','Value','1.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_569','position',[286,944,336,964]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_569/1','input.I[20]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_571');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_571','Value','1.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_571','position',[888,132,938,152]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_571/1','input.I[21]/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/circuit/const_573');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_573','Value','1.');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/const_573','position',[522,857,572,877]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','const_573/1','input.I[22]/1');
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_0_odeIdeal/circuit/output.V[0]_out');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/circuit/_output.V[0]_out');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','_output.V[0]_out/1','output.V[0]_out/1');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/output.V[0]_out','position',[220,345,270,365]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','output.V[0]/1','_output.V[0]_out/1');
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_0_odeIdeal/circuit/output.V[1]_out');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/circuit/_output.V[1]_out');
  add_line('ckt_gentoggle_0_odeIdeal/circuit','_output.V[1]_out/1','output.V[1]_out/1');
  set_param('ckt_gentoggle_0_odeIdeal/circuit/output.V[1]_out','position',[363,212,413,232]);
  add_line('ckt_gentoggle_0_odeIdeal/circuit','output.V[1]/1','_output.V[1]_out/1');
end
%
%
%preamble function
function preamble()
  %define model name
  model_name='ckt_gentoggle_0_odeIdeal';
  %create and open the model
  open_system(new_system(model_name));
  %set solver method
  set_param(model_name,'Solver','ode3');
end
%
%
%library assembly function
function build_comp_library()
  add_block('simulink/Ports & Subsystems/Subsystem','ckt_gentoggle_0_odeIdeal/library');
  set_param('ckt_gentoggle_0_odeIdeal/library','position',[484,406,534,426]);
  delete_line('ckt_gentoggle_0_odeIdeal/library','In1/1','Out1/1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/In1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/Out1');
  %
  %
  %
  add_block('simulink/Ports & Subsystems/Subsystem','ckt_gentoggle_0_odeIdeal/library/mm');
  set_param('ckt_gentoggle_0_odeIdeal/library/mm','position',[475,832,525,852]);
  delete_line('ckt_gentoggle_0_odeIdeal/library/mm','In1/1','Out1/1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/mm/In1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/mm/Out1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/mm/kr');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/mm/_kr');
  set_param('ckt_gentoggle_0_odeIdeal/library/mm/kr','position',[669,821,719,841]);
  add_line('ckt_gentoggle_0_odeIdeal/library/mm','kr/1','_kr/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/mm/XY0');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/mm/_XY0');
  set_param('ckt_gentoggle_0_odeIdeal/library/mm/XY0','position',[472,541,522,561]);
  add_line('ckt_gentoggle_0_odeIdeal/library/mm','XY0/1','_XY0/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/mm/Ytot');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/mm/_Ytot');
  set_param('ckt_gentoggle_0_odeIdeal/library/mm/Ytot','position',[678,213,728,233]);
  add_line('ckt_gentoggle_0_odeIdeal/library/mm','Ytot/1','_Ytot/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/mm/kf');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/mm/_kf');
  set_param('ckt_gentoggle_0_odeIdeal/library/mm/kf','position',[915,256,965,276]);
  add_line('ckt_gentoggle_0_odeIdeal/library/mm','kf/1','_kf/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/mm/Xtot');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/mm/_Xtot');
  set_param('ckt_gentoggle_0_odeIdeal/library/mm/Xtot','position',[398,458,448,478]);
  add_line('ckt_gentoggle_0_odeIdeal/library/mm','Xtot/1','_Xtot/1');
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_0_odeIdeal/library/mm/X');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/mm/_X');
  add_line('ckt_gentoggle_0_odeIdeal/library/mm','_X/1','X/1');
  set_param('ckt_gentoggle_0_odeIdeal/library/mm/X','position',[67,616,117,636]);
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_0_odeIdeal/library/mm/XY');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/mm/_XY');
  add_line('ckt_gentoggle_0_odeIdeal/library/mm','_XY/1','XY/1');
  set_param('ckt_gentoggle_0_odeIdeal/library/mm/XY','position',[560,478,610,498]);
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_0_odeIdeal/library/mm/Y');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/mm/_Y');
  add_line('ckt_gentoggle_0_odeIdeal/library/mm','_Y/1','Y/1');
  set_param('ckt_gentoggle_0_odeIdeal/library/mm/Y','position',[169,589,219,609]);
  add_block('simulink/Math Operations/Sum','ckt_gentoggle_0_odeIdeal/library/mm/sum_39');
  set_param('ckt_gentoggle_0_odeIdeal/library/mm/sum_39','Inputs','+-');
  set_param('ckt_gentoggle_0_odeIdeal/library/mm/sum_39','position',[541,961,591,981]);
  add_line('ckt_gentoggle_0_odeIdeal/library/mm','_Xtot/1','sum_39/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/mm','_XY/1','sum_39/2');
  add_line('ckt_gentoggle_0_odeIdeal/library/mm','sum_39/1','_X/1');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_0_odeIdeal/library/mm/mul_42');
  set_param('ckt_gentoggle_0_odeIdeal/library/mm/mul_42','Inputs','***');
  set_param('ckt_gentoggle_0_odeIdeal/library/mm/mul_42','position',[649,764,699,784]);
  add_line('ckt_gentoggle_0_odeIdeal/library/mm','_kf/1','mul_42/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/mm','_X/1','mul_42/2');
  add_line('ckt_gentoggle_0_odeIdeal/library/mm','_Y/1','mul_42/3');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_0_odeIdeal/library/mm/mul_46');
  set_param('ckt_gentoggle_0_odeIdeal/library/mm/mul_46','Inputs','**');
  set_param('ckt_gentoggle_0_odeIdeal/library/mm/mul_46','position',[696,475,746,495]);
  add_line('ckt_gentoggle_0_odeIdeal/library/mm','_kr/1','mul_46/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/mm','_XY/1','mul_46/2');
  add_block('simulink/Math Operations/Sum','ckt_gentoggle_0_odeIdeal/library/mm/sum_49');
  set_param('ckt_gentoggle_0_odeIdeal/library/mm/sum_49','Inputs','+-');
  set_param('ckt_gentoggle_0_odeIdeal/library/mm/sum_49','position',[101,531,151,551]);
  add_line('ckt_gentoggle_0_odeIdeal/library/mm','mul_42/1','sum_49/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/mm','mul_46/1','sum_49/2');
  add_block('simulink/Continuous/Integrator','ckt_gentoggle_0_odeIdeal/library/mm/int_52');
  set_param('ckt_gentoggle_0_odeIdeal/library/mm/int_52','position',[783,309,833,329]);
  add_line('ckt_gentoggle_0_odeIdeal/library/mm','sum_49/1','int_52/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/mm','int_52/1','_XY/1');
  add_block('simulink/Math Operations/Sum','ckt_gentoggle_0_odeIdeal/library/mm/sum_54');
  set_param('ckt_gentoggle_0_odeIdeal/library/mm/sum_54','Inputs','+-');
  set_param('ckt_gentoggle_0_odeIdeal/library/mm/sum_54','position',[590,805,640,825]);
  add_line('ckt_gentoggle_0_odeIdeal/library/mm','_Ytot/1','sum_54/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/mm','_XY/1','sum_54/2');
  add_line('ckt_gentoggle_0_odeIdeal/library/mm','sum_54/1','_Y/1');
  %
  add_block('simulink/Ports & Subsystems/Subsystem','ckt_gentoggle_0_odeIdeal/library/vgain');
  set_param('ckt_gentoggle_0_odeIdeal/library/vgain','position',[810,10,860,30]);
  delete_line('ckt_gentoggle_0_odeIdeal/library/vgain','In1/1','Out1/1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/vgain/In1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/vgain/Out1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/vgain/X');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/vgain/_X');
  set_param('ckt_gentoggle_0_odeIdeal/library/vgain/X','position',[415,454,465,474]);
  add_line('ckt_gentoggle_0_odeIdeal/library/vgain','X/1','_X/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/vgain/Y');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/vgain/_Y');
  set_param('ckt_gentoggle_0_odeIdeal/library/vgain/Y','position',[777,517,827,537]);
  add_line('ckt_gentoggle_0_odeIdeal/library/vgain','Y/1','_Y/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/vgain/Z');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/vgain/_Z');
  set_param('ckt_gentoggle_0_odeIdeal/library/vgain/Z','position',[800,393,850,413]);
  add_line('ckt_gentoggle_0_odeIdeal/library/vgain','Z/1','_Z/1');
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_0_odeIdeal/library/vgain/P');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/vgain/_P');
  add_line('ckt_gentoggle_0_odeIdeal/library/vgain','_P/1','P/1');
  set_param('ckt_gentoggle_0_odeIdeal/library/vgain/P','position',[255,489,305,509]);
  add_block('simulink/Math Operations/Product','ckt_gentoggle_0_odeIdeal/library/vgain/div_77');
  set_param('ckt_gentoggle_0_odeIdeal/library/vgain/div_77','Inputs','*/');
  set_param('ckt_gentoggle_0_odeIdeal/library/vgain/div_77','position',[263,322,313,342]);
  add_line('ckt_gentoggle_0_odeIdeal/library/vgain','_X/1','div_77/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/vgain','_Y/1','div_77/2');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/library/vgain/const_80');
  set_param('ckt_gentoggle_0_odeIdeal/library/vgain/const_80','Value','0.5');
  set_param('ckt_gentoggle_0_odeIdeal/library/vgain/const_80','position',[22,646,72,666]);
  add_block('simulink/Math Operations/Product','ckt_gentoggle_0_odeIdeal/library/vgain/mul_82');
  set_param('ckt_gentoggle_0_odeIdeal/library/vgain/mul_82','Inputs','***');
  set_param('ckt_gentoggle_0_odeIdeal/library/vgain/mul_82','position',[818,57,868,77]);
  add_line('ckt_gentoggle_0_odeIdeal/library/vgain','div_77/1','mul_82/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/vgain','_Z/1','mul_82/2');
  add_line('ckt_gentoggle_0_odeIdeal/library/vgain','const_80/1','mul_82/3');
  add_line('ckt_gentoggle_0_odeIdeal/library/vgain','mul_82/1','_P/1');
  %
  add_block('simulink/Ports & Subsystems/Subsystem','ckt_gentoggle_0_odeIdeal/library/switch');
  set_param('ckt_gentoggle_0_odeIdeal/library/switch','position',[415,582,465,602]);
  delete_line('ckt_gentoggle_0_odeIdeal/library/switch','In1/1','Out1/1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/switch/In1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/switch/Out1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/switch/n');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/switch/_n');
  set_param('ckt_gentoggle_0_odeIdeal/library/switch/n','position',[501,217,551,237]);
  add_line('ckt_gentoggle_0_odeIdeal/library/switch','n/1','_n/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/switch/SUB');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/switch/_SUB');
  set_param('ckt_gentoggle_0_odeIdeal/library/switch/SUB','position',[429,636,479,656]);
  add_line('ckt_gentoggle_0_odeIdeal/library/switch','SUB/1','_SUB/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/switch/Kmod');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/switch/_Kmod');
  set_param('ckt_gentoggle_0_odeIdeal/library/switch/Kmod','position',[54,893,104,913]);
  add_line('ckt_gentoggle_0_odeIdeal/library/switch','Kmod/1','_Kmod/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/switch/Vmax');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/switch/_Vmax');
  set_param('ckt_gentoggle_0_odeIdeal/library/switch/Vmax','position',[364,337,414,357]);
  add_line('ckt_gentoggle_0_odeIdeal/library/switch','Vmax/1','_Vmax/1');
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_0_odeIdeal/library/switch/PROD');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/switch/_PROD');
  add_line('ckt_gentoggle_0_odeIdeal/library/switch','_PROD/1','PROD/1');
  set_param('ckt_gentoggle_0_odeIdeal/library/switch/PROD','position',[125,743,175,763]);
  add_block('simulink/Math Operations/Product','ckt_gentoggle_0_odeIdeal/library/switch/div_111');
  set_param('ckt_gentoggle_0_odeIdeal/library/switch/div_111','Inputs','*/');
  set_param('ckt_gentoggle_0_odeIdeal/library/switch/div_111','position',[496,645,546,665]);
  add_line('ckt_gentoggle_0_odeIdeal/library/switch','_SUB/1','div_111/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/switch','_Kmod/1','div_111/2');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/library/switch/const_114');
  set_param('ckt_gentoggle_0_odeIdeal/library/switch/const_114','Value','1.');
  set_param('ckt_gentoggle_0_odeIdeal/library/switch/const_114','position',[387,267,437,287]);
  add_block('simulink/Math Operations/Sum','ckt_gentoggle_0_odeIdeal/library/switch/sub_116');
  set_param('ckt_gentoggle_0_odeIdeal/library/switch/sub_116','Inputs','++');
  set_param('ckt_gentoggle_0_odeIdeal/library/switch/sub_116','position',[709,675,759,695]);
  add_line('ckt_gentoggle_0_odeIdeal/library/switch','div_111/1','sub_116/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/switch','const_114/1','sub_116/2');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/library/switch/const_119');
  set_param('ckt_gentoggle_0_odeIdeal/library/switch/const_119','Value','500.');
  set_param('ckt_gentoggle_0_odeIdeal/library/switch/const_119','position',[139,516,189,536]);
  add_block('simulink/Math Operations/Product','ckt_gentoggle_0_odeIdeal/library/switch/div_121');
  set_param('ckt_gentoggle_0_odeIdeal/library/switch/div_121','Inputs','*/');
  set_param('ckt_gentoggle_0_odeIdeal/library/switch/div_121','position',[188,171,238,191]);
  add_line('ckt_gentoggle_0_odeIdeal/library/switch','_n/1','div_121/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/switch','const_119/1','div_121/2');
  add_block('simulink/Math Operations/Math Function','ckt_gentoggle_0_odeIdeal/library/switch/pow_124');
  set_param('ckt_gentoggle_0_odeIdeal/library/switch/pow_124','Function','pow');
  set_param('ckt_gentoggle_0_odeIdeal/library/switch/pow_124','position',[132,879,182,899]);
  add_line('ckt_gentoggle_0_odeIdeal/library/switch','div_121/1','pow_124/2');
  add_line('ckt_gentoggle_0_odeIdeal/library/switch','sub_116/1','pow_124/1');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_0_odeIdeal/library/switch/div_127');
  set_param('ckt_gentoggle_0_odeIdeal/library/switch/div_127','Inputs','*/');
  set_param('ckt_gentoggle_0_odeIdeal/library/switch/div_127','position',[76,817,126,837]);
  add_line('ckt_gentoggle_0_odeIdeal/library/switch','_Vmax/1','div_127/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/switch','pow_124/1','div_127/2');
  add_line('ckt_gentoggle_0_odeIdeal/library/switch','div_127/1','_PROD/1');
  %
  add_block('simulink/Ports & Subsystems/Subsystem','ckt_gentoggle_0_odeIdeal/library/ihill');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill','position',[620,602,670,622]);
  delete_line('ckt_gentoggle_0_odeIdeal/library/ihill','In1/1','Out1/1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/ihill/In1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/ihill/Out1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/ihill/n');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/ihill/_n');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/n','position',[835,563,885,583]);
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','n/1','_n/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/ihill/S');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/ihill/_S');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/S','position',[260,477,310,497]);
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','S/1','_S/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/ihill/Km');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/ihill/_Km');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/Km','position',[740,279,790,299]);
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','Km/1','_Km/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/ihill/Vmax');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/ihill/_Vmax');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/Vmax','position',[929,599,979,619]);
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','Vmax/1','_Vmax/1');
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_0_odeIdeal/library/ihill/STIM');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/ihill/_STIM');
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','_STIM/1','STIM/1');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/STIM','position',[695,389,745,409]);
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_0_odeIdeal/library/ihill/REP');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/ihill/_REP');
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','_REP/1','REP/1');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/REP','position',[356,618,406,638]);
  add_block('simulink/Math Operations/Product','ckt_gentoggle_0_odeIdeal/library/ihill/div_159');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/div_159','Inputs','*/');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/div_159','position',[205,344,255,364]);
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','_S/1','div_159/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','_Km/1','div_159/2');
  add_block('simulink/Math Operations/Math Function','ckt_gentoggle_0_odeIdeal/library/ihill/pow_162');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/pow_162','Function','pow');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/pow_162','position',[151,719,201,739]);
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','_n/1','pow_162/2');
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','div_159/1','pow_162/1');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_0_odeIdeal/library/ihill/div_165');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/div_165','Inputs','*/');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/div_165','position',[816,291,866,311]);
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','_S/1','div_165/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','_Km/1','div_165/2');
  add_block('simulink/Math Operations/Math Function','ckt_gentoggle_0_odeIdeal/library/ihill/pow_168');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/pow_168','Function','pow');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/pow_168','position',[351,198,401,218]);
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','_n/1','pow_168/2');
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','div_165/1','pow_168/1');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/library/ihill/const_171');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/const_171','Value','1.');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/const_171','position',[34,127,84,147]);
  add_block('simulink/Math Operations/Sum','ckt_gentoggle_0_odeIdeal/library/ihill/sub_173');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/sub_173','Inputs','++');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/sub_173','position',[983,409,1033,429]);
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','pow_168/1','sub_173/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','const_171/1','sub_173/2');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_0_odeIdeal/library/ihill/div_176');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/div_176','Inputs','*/');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/div_176','position',[941,219,991,239]);
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','pow_162/1','div_176/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','sub_173/1','div_176/2');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_0_odeIdeal/library/ihill/mul_179');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/mul_179','Inputs','**');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/mul_179','position',[565,955,615,975]);
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','_Vmax/1','mul_179/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','div_176/1','mul_179/2');
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','mul_179/1','_STIM/1');
  add_block('simulink/Math Operations/Math Function','ckt_gentoggle_0_odeIdeal/library/ihill/pow_182');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/pow_182','Function','pow');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/pow_182','position',[825,506,875,526]);
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','_n/1','pow_182/2');
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','_Km/1','pow_182/1');
  add_block('simulink/Math Operations/Math Function','ckt_gentoggle_0_odeIdeal/library/ihill/pow_185');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/pow_185','Function','pow');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/pow_185','position',[205,314,255,334]);
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','_n/1','pow_185/2');
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','_S/1','pow_185/1');
  add_block('simulink/Math Operations/Math Function','ckt_gentoggle_0_odeIdeal/library/ihill/pow_188');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/pow_188','Function','pow');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/pow_188','position',[371,426,421,446]);
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','_n/1','pow_188/2');
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','_Km/1','pow_188/1');
  add_block('simulink/Math Operations/Sum','ckt_gentoggle_0_odeIdeal/library/ihill/sub_191');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/sub_191','Inputs','++');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/sub_191','position',[614,312,664,332]);
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','pow_185/1','sub_191/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','pow_188/1','sub_191/2');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_0_odeIdeal/library/ihill/div_194');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/div_194','Inputs','*/');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/div_194','position',[341,113,391,133]);
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','pow_182/1','div_194/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','sub_191/1','div_194/2');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_0_odeIdeal/library/ihill/mul_197');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/mul_197','Inputs','**');
  set_param('ckt_gentoggle_0_odeIdeal/library/ihill/mul_197','position',[36,241,86,261]);
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','_Vmax/1','mul_197/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','div_194/1','mul_197/2');
  add_line('ckt_gentoggle_0_odeIdeal/library/ihill','mul_197/1','_REP/1');
  %
  add_block('simulink/Ports & Subsystems/Subsystem','ckt_gentoggle_0_odeIdeal/library/itov');
  set_param('ckt_gentoggle_0_odeIdeal/library/itov','position',[37,196,87,216]);
  delete_line('ckt_gentoggle_0_odeIdeal/library/itov','In1/1','Out1/1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/itov/In1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/itov/Out1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/itov/X');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/itov/_X');
  set_param('ckt_gentoggle_0_odeIdeal/library/itov/X','position',[38,746,88,766]);
  add_line('ckt_gentoggle_0_odeIdeal/library/itov','X/1','_X/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/itov/K');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/itov/_K');
  set_param('ckt_gentoggle_0_odeIdeal/library/itov/K','position',[230,66,280,86]);
  add_line('ckt_gentoggle_0_odeIdeal/library/itov','K/1','_K/1');
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_0_odeIdeal/library/itov/Y');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/itov/_Y');
  add_line('ckt_gentoggle_0_odeIdeal/library/itov','_Y/1','Y/1');
  set_param('ckt_gentoggle_0_odeIdeal/library/itov/Y','position',[624,287,674,307]);
  add_block('simulink/Math Operations/Product','ckt_gentoggle_0_odeIdeal/library/itov/mul_215');
  set_param('ckt_gentoggle_0_odeIdeal/library/itov/mul_215','Inputs','**');
  set_param('ckt_gentoggle_0_odeIdeal/library/itov/mul_215','position',[261,4,311,24]);
  add_line('ckt_gentoggle_0_odeIdeal/library/itov','_K/1','mul_215/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/itov','_X/1','mul_215/2');
  add_line('ckt_gentoggle_0_odeIdeal/library/itov','mul_215/1','_Y/1');
  %
  add_block('simulink/Ports & Subsystems/Subsystem','ckt_gentoggle_0_odeIdeal/library/output.I');
  set_param('ckt_gentoggle_0_odeIdeal/library/output.I','position',[960,477,1010,497]);
  delete_line('ckt_gentoggle_0_odeIdeal/library/output.I','In1/1','Out1/1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/output.I/In1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/output.I/Out1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/output.I/X');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/output.I/_X');
  set_param('ckt_gentoggle_0_odeIdeal/library/output.I/X','position',[170,106,220,126]);
  add_line('ckt_gentoggle_0_odeIdeal/library/output.I','X/1','_X/1');
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_0_odeIdeal/library/output.I/O');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/output.I/_O');
  add_line('ckt_gentoggle_0_odeIdeal/library/output.I','_O/1','O/1');
  set_param('ckt_gentoggle_0_odeIdeal/library/output.I/O','position',[772,613,822,633]);
  add_line('ckt_gentoggle_0_odeIdeal/library/output.I','_X/1','_O/1');
  %
  add_block('simulink/Ports & Subsystems/Subsystem','ckt_gentoggle_0_odeIdeal/library/output.V');
  set_param('ckt_gentoggle_0_odeIdeal/library/output.V','position',[597,947,647,967]);
  delete_line('ckt_gentoggle_0_odeIdeal/library/output.V','In1/1','Out1/1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/output.V/In1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/output.V/Out1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/output.V/X');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/output.V/_X');
  set_param('ckt_gentoggle_0_odeIdeal/library/output.V/X','position',[967,993,1017,1013]);
  add_line('ckt_gentoggle_0_odeIdeal/library/output.V','X/1','_X/1');
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_0_odeIdeal/library/output.V/O');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/output.V/_O');
  add_line('ckt_gentoggle_0_odeIdeal/library/output.V','_O/1','O/1');
  set_param('ckt_gentoggle_0_odeIdeal/library/output.V/O','position',[94,748,144,768]);
  add_line('ckt_gentoggle_0_odeIdeal/library/output.V','_X/1','_O/1');
  %
  add_block('simulink/Ports & Subsystems/Subsystem','ckt_gentoggle_0_odeIdeal/library/input.V');
  set_param('ckt_gentoggle_0_odeIdeal/library/input.V','position',[814,308,864,328]);
  delete_line('ckt_gentoggle_0_odeIdeal/library/input.V','In1/1','Out1/1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/input.V/In1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/input.V/Out1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/input.V/X');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/input.V/_X');
  set_param('ckt_gentoggle_0_odeIdeal/library/input.V/X','position',[103,72,153,92]);
  add_block('simulink/Discontinuities/Quantizer','ckt_gentoggle_0_odeIdeal/library/input.V/smp_244');
  set_param('ckt_gentoggle_0_odeIdeal/library/input.V/smp_244','QuantizationInterval','1e-05');
  set_param('ckt_gentoggle_0_odeIdeal/library/input.V/smp_244','position',[640,138,690,158]);
  add_line('ckt_gentoggle_0_odeIdeal/library/input.V','X/1','smp_244/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/input.V','smp_244/1','_X/1');
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_0_odeIdeal/library/input.V/O');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/input.V/_O');
  add_line('ckt_gentoggle_0_odeIdeal/library/input.V','_O/1','O/1');
  set_param('ckt_gentoggle_0_odeIdeal/library/input.V/O','position',[958,716,1008,736]);
  add_line('ckt_gentoggle_0_odeIdeal/library/input.V','_X/1','_O/1');
  %
  add_block('simulink/Ports & Subsystems/Subsystem','ckt_gentoggle_0_odeIdeal/library/copy.V');
  set_param('ckt_gentoggle_0_odeIdeal/library/copy.V','position',[680,201,730,221]);
  delete_line('ckt_gentoggle_0_odeIdeal/library/copy.V','In1/1','Out1/1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/copy.V/In1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/copy.V/Out1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/copy.V/X');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/copy.V/_X');
  set_param('ckt_gentoggle_0_odeIdeal/library/copy.V/X','position',[105,50,155,70]);
  add_line('ckt_gentoggle_0_odeIdeal/library/copy.V','X/1','_X/1');
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_0_odeIdeal/library/copy.V/Y');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/copy.V/_Y');
  add_line('ckt_gentoggle_0_odeIdeal/library/copy.V','_Y/1','Y/1');
  set_param('ckt_gentoggle_0_odeIdeal/library/copy.V/Y','position',[187,547,237,567]);
  add_line('ckt_gentoggle_0_odeIdeal/library/copy.V','_X/1','_Y/1');
  %
  add_block('simulink/Ports & Subsystems/Subsystem','ckt_gentoggle_0_odeIdeal/library/vtoi');
  set_param('ckt_gentoggle_0_odeIdeal/library/vtoi','position',[883,264,933,284]);
  delete_line('ckt_gentoggle_0_odeIdeal/library/vtoi','In1/1','Out1/1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/vtoi/In1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/vtoi/Out1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/vtoi/X');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/vtoi/_X');
  set_param('ckt_gentoggle_0_odeIdeal/library/vtoi/X','position',[213,606,263,626]);
  add_line('ckt_gentoggle_0_odeIdeal/library/vtoi','X/1','_X/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/vtoi/K');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/vtoi/_K');
  set_param('ckt_gentoggle_0_odeIdeal/library/vtoi/K','position',[592,383,642,403]);
  add_line('ckt_gentoggle_0_odeIdeal/library/vtoi','K/1','_K/1');
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_0_odeIdeal/library/vtoi/Y');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/vtoi/_Y');
  add_line('ckt_gentoggle_0_odeIdeal/library/vtoi','_Y/1','Y/1');
  set_param('ckt_gentoggle_0_odeIdeal/library/vtoi/Y','position',[598,710,648,730]);
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/library/vtoi/const_275');
  set_param('ckt_gentoggle_0_odeIdeal/library/vtoi/const_275','Value','1.');
  set_param('ckt_gentoggle_0_odeIdeal/library/vtoi/const_275','position',[97,165,147,185]);
  add_block('simulink/Math Operations/Product','ckt_gentoggle_0_odeIdeal/library/vtoi/div_277');
  set_param('ckt_gentoggle_0_odeIdeal/library/vtoi/div_277','Inputs','*/');
  set_param('ckt_gentoggle_0_odeIdeal/library/vtoi/div_277','position',[533,177,583,197]);
  add_line('ckt_gentoggle_0_odeIdeal/library/vtoi','const_275/1','div_277/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/vtoi','_K/1','div_277/2');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_0_odeIdeal/library/vtoi/mul_280');
  set_param('ckt_gentoggle_0_odeIdeal/library/vtoi/mul_280','Inputs','**');
  set_param('ckt_gentoggle_0_odeIdeal/library/vtoi/mul_280','position',[331,982,381,1002]);
  add_line('ckt_gentoggle_0_odeIdeal/library/vtoi','div_277/1','mul_280/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/vtoi','_X/1','mul_280/2');
  add_line('ckt_gentoggle_0_odeIdeal/library/vtoi','mul_280/1','_Y/1');
  %
  add_block('simulink/Ports & Subsystems/Subsystem','ckt_gentoggle_0_odeIdeal/library/vadd');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd','position',[61,590,111,610]);
  delete_line('ckt_gentoggle_0_odeIdeal/library/vadd','In1/1','Out1/1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/vadd/In1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/vadd/Out1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/vadd/OUT2_0');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/vadd/_OUT2_0');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/OUT2_0','position',[745,583,795,603]);
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','OUT2_0/1','_OUT2_0/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/vadd/D');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/vadd/_D');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/D','position',[428,846,478,866]);
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','D/1','_D/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/vadd/C');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/vadd/_C');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/C','position',[54,295,104,315]);
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','C/1','_C/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/vadd/A');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/vadd/_A');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/A','position',[780,667,830,687]);
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','A/1','_A/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/vadd/B');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/vadd/_B');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/B','position',[643,366,693,386]);
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','B/1','_B/1');
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_0_odeIdeal/library/vadd/OUT');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/vadd/_OUT');
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','_OUT/1','OUT/1');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/OUT','position',[211,318,261,338]);
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_0_odeIdeal/library/vadd/OUT2');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/vadd/_OUT2');
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','_OUT2/1','OUT2/1');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/OUT2','position',[171,360,221,380]);
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/vadd/BSW');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/vadd/_BSW');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/BSW','position',[374,137,424,157]);
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','BSW/1','_BSW/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/vadd/CSW');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/vadd/_CSW');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/CSW','position',[372,213,422,233]);
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','CSW/1','_CSW/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/vadd/DSW');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/vadd/_DSW');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/DSW','position',[485,173,535,193]);
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','DSW/1','_DSW/1');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_0_odeIdeal/library/vadd/mul_332');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/mul_332','Inputs','**');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/mul_332','position',[704,189,754,209]);
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','_BSW/1','mul_332/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','_B/1','mul_332/2');
  add_block('simulink/Math Operations/Sum','ckt_gentoggle_0_odeIdeal/library/vadd/sub_335');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/sub_335','Inputs','++');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/sub_335','position',[906,565,956,585]);
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','_A/1','sub_335/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','mul_332/1','sub_335/2');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_0_odeIdeal/library/vadd/mul_338');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/mul_338','Inputs','**');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/mul_338','position',[644,184,694,204]);
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','_CSW/1','mul_338/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','_C/1','mul_338/2');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_0_odeIdeal/library/vadd/mul_341');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/mul_341','Inputs','**');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/mul_341','position',[259,332,309,352]);
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','_DSW/1','mul_341/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','_D/1','mul_341/2');
  add_block('simulink/Math Operations/Sum','ckt_gentoggle_0_odeIdeal/library/vadd/sum_344');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/sum_344','Inputs','+--');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/sum_344','position',[889,618,939,638]);
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','sub_335/1','sum_344/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','mul_338/1','sum_344/2');
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','mul_341/1','sum_344/3');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/library/vadd/const_348');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/const_348','Value','0.25');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/const_348','position',[297,701,347,721]);
  add_block('simulink/Math Operations/Product','ckt_gentoggle_0_odeIdeal/library/vadd/mul_350');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/mul_350','Inputs','**');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/mul_350','position',[213,857,263,877]);
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','sum_344/1','mul_350/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','const_348/1','mul_350/2');
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','mul_350/1','_OUT/1');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_0_odeIdeal/library/vadd/mul_353');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/mul_353','Inputs','**');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/mul_353','position',[335,115,385,135]);
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','_BSW/1','mul_353/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','_B/1','mul_353/2');
  add_block('simulink/Math Operations/Sum','ckt_gentoggle_0_odeIdeal/library/vadd/sub_356');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/sub_356','Inputs','++');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/sub_356','position',[374,319,424,339]);
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','_A/1','sub_356/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','mul_353/1','sub_356/2');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_0_odeIdeal/library/vadd/mul_359');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/mul_359','Inputs','**');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/mul_359','position',[629,959,679,979]);
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','_CSW/1','mul_359/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','_C/1','mul_359/2');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_0_odeIdeal/library/vadd/mul_362');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/mul_362','Inputs','***');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/mul_362','position',[103,539,153,559]);
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','_DSW/1','mul_362/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','_D/1','mul_362/2');
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','_OUT2/1','mul_362/3');
  add_block('simulink/Math Operations/Sum','ckt_gentoggle_0_odeIdeal/library/vadd/sum_366');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/sum_366','Inputs','+--');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/sum_366','position',[910,605,960,625]);
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','sub_356/1','sum_366/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','mul_359/1','sum_366/2');
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','mul_362/1','sum_366/3');
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/library/vadd/const_370');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/const_370','Value','0.25');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/const_370','position',[21,777,71,797]);
  add_block('simulink/Math Operations/Product','ckt_gentoggle_0_odeIdeal/library/vadd/mul_372');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/mul_372','Inputs','**');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/mul_372','position',[371,138,421,158]);
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','sum_366/1','mul_372/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','const_370/1','mul_372/2');
  add_block('simulink/Continuous/Integrator','ckt_gentoggle_0_odeIdeal/library/vadd/int_375');
  set_param('ckt_gentoggle_0_odeIdeal/library/vadd/int_375','position',[521,479,571,499]);
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','mul_372/1','int_375/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/vadd','int_375/1','_OUT2/1');
  %
  add_block('simulink/Ports & Subsystems/Subsystem','ckt_gentoggle_0_odeIdeal/library/copy.I');
  set_param('ckt_gentoggle_0_odeIdeal/library/copy.I','position',[330,21,380,41]);
  delete_line('ckt_gentoggle_0_odeIdeal/library/copy.I','In1/1','Out1/1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/copy.I/In1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/copy.I/Out1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/copy.I/X');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/copy.I/_X');
  set_param('ckt_gentoggle_0_odeIdeal/library/copy.I/X','position',[356,189,406,209]);
  add_line('ckt_gentoggle_0_odeIdeal/library/copy.I','X/1','_X/1');
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_0_odeIdeal/library/copy.I/Y');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/copy.I/_Y');
  add_line('ckt_gentoggle_0_odeIdeal/library/copy.I','_Y/1','Y/1');
  set_param('ckt_gentoggle_0_odeIdeal/library/copy.I/Y','position',[761,969,811,989]);
  add_line('ckt_gentoggle_0_odeIdeal/library/copy.I','_X/1','_Y/1');
  %
  add_block('simulink/Ports & Subsystems/Subsystem','ckt_gentoggle_0_odeIdeal/library/iadd');
  set_param('ckt_gentoggle_0_odeIdeal/library/iadd','position',[335,382,385,402]);
  delete_line('ckt_gentoggle_0_odeIdeal/library/iadd','In1/1','Out1/1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/iadd/In1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/iadd/Out1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/iadd/D');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/iadd/_D');
  set_param('ckt_gentoggle_0_odeIdeal/library/iadd/D','position',[76,692,126,712]);
  add_line('ckt_gentoggle_0_odeIdeal/library/iadd','D/1','_D/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/iadd/C');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/iadd/_C');
  set_param('ckt_gentoggle_0_odeIdeal/library/iadd/C','position',[363,959,413,979]);
  add_line('ckt_gentoggle_0_odeIdeal/library/iadd','C/1','_C/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/iadd/A');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/iadd/_A');
  set_param('ckt_gentoggle_0_odeIdeal/library/iadd/A','position',[220,85,270,105]);
  add_line('ckt_gentoggle_0_odeIdeal/library/iadd','A/1','_A/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/iadd/B');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/iadd/_B');
  set_param('ckt_gentoggle_0_odeIdeal/library/iadd/B','position',[619,852,669,872]);
  add_line('ckt_gentoggle_0_odeIdeal/library/iadd','B/1','_B/1');
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_0_odeIdeal/library/iadd/OUT');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/iadd/_OUT');
  add_line('ckt_gentoggle_0_odeIdeal/library/iadd','_OUT/1','OUT/1');
  set_param('ckt_gentoggle_0_odeIdeal/library/iadd/OUT','position',[705,546,755,566]);
  add_block('simulink/Math Operations/Sum','ckt_gentoggle_0_odeIdeal/library/iadd/sub_412');
  set_param('ckt_gentoggle_0_odeIdeal/library/iadd/sub_412','Inputs','++');
  set_param('ckt_gentoggle_0_odeIdeal/library/iadd/sub_412','position',[286,540,336,560]);
  add_line('ckt_gentoggle_0_odeIdeal/library/iadd','_A/1','sub_412/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/iadd','_B/1','sub_412/2');
  add_block('simulink/Math Operations/Sum','ckt_gentoggle_0_odeIdeal/library/iadd/sum_415');
  set_param('ckt_gentoggle_0_odeIdeal/library/iadd/sum_415','Inputs','+--');
  set_param('ckt_gentoggle_0_odeIdeal/library/iadd/sum_415','position',[924,159,974,179]);
  add_line('ckt_gentoggle_0_odeIdeal/library/iadd','sub_412/1','sum_415/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/iadd','_C/1','sum_415/2');
  add_line('ckt_gentoggle_0_odeIdeal/library/iadd','_D/1','sum_415/3');
  add_line('ckt_gentoggle_0_odeIdeal/library/iadd','sum_415/1','_OUT/1');
  %
  add_block('simulink/Ports & Subsystems/Subsystem','ckt_gentoggle_0_odeIdeal/library/input.I');
  set_param('ckt_gentoggle_0_odeIdeal/library/input.I','position',[790,470,840,490]);
  delete_line('ckt_gentoggle_0_odeIdeal/library/input.I','In1/1','Out1/1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/input.I/In1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/input.I/Out1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/input.I/X');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/input.I/_X');
  set_param('ckt_gentoggle_0_odeIdeal/library/input.I/X','position',[148,392,198,412]);
  add_block('simulink/Discontinuities/Quantizer','ckt_gentoggle_0_odeIdeal/library/input.I/smp_425');
  set_param('ckt_gentoggle_0_odeIdeal/library/input.I/smp_425','QuantizationInterval','1e-05');
  set_param('ckt_gentoggle_0_odeIdeal/library/input.I/smp_425','position',[904,731,954,751]);
  add_line('ckt_gentoggle_0_odeIdeal/library/input.I','X/1','smp_425/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/input.I','smp_425/1','_X/1');
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_0_odeIdeal/library/input.I/O');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/input.I/_O');
  add_line('ckt_gentoggle_0_odeIdeal/library/input.I','_O/1','O/1');
  set_param('ckt_gentoggle_0_odeIdeal/library/input.I/O','position',[826,442,876,462]);
  add_line('ckt_gentoggle_0_odeIdeal/library/input.I','_X/1','_O/1');
  %
  add_block('simulink/Ports & Subsystems/Subsystem','ckt_gentoggle_0_odeIdeal/library/igenebind');
  set_param('ckt_gentoggle_0_odeIdeal/library/igenebind','position',[536,161,586,181]);
  delete_line('ckt_gentoggle_0_odeIdeal/library/igenebind','In1/1','Out1/1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/igenebind/In1');
  delete_block('ckt_gentoggle_0_odeIdeal/library/igenebind/Out1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/igenebind/TF');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/igenebind/_TF');
  set_param('ckt_gentoggle_0_odeIdeal/library/igenebind/TF','position',[793,573,843,593]);
  add_line('ckt_gentoggle_0_odeIdeal/library/igenebind','TF/1','_TF/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/igenebind/K');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/igenebind/_K');
  set_param('ckt_gentoggle_0_odeIdeal/library/igenebind/K','position',[672,430,722,450]);
  add_line('ckt_gentoggle_0_odeIdeal/library/igenebind','K/1','_K/1');
  add_block('simulink/Ports & Subsystems/In1','ckt_gentoggle_0_odeIdeal/library/igenebind/Vmax');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/igenebind/_Vmax');
  set_param('ckt_gentoggle_0_odeIdeal/library/igenebind/Vmax','position',[241,246,291,266]);
  add_line('ckt_gentoggle_0_odeIdeal/library/igenebind','Vmax/1','_Vmax/1');
  add_block('simulink/Ports & Subsystems/Out1','ckt_gentoggle_0_odeIdeal/library/igenebind/GE');
  add_block('simulink/Math Operations/Gain','ckt_gentoggle_0_odeIdeal/library/igenebind/_GE');
  add_line('ckt_gentoggle_0_odeIdeal/library/igenebind','_GE/1','GE/1');
  set_param('ckt_gentoggle_0_odeIdeal/library/igenebind/GE','position',[970,733,1020,753]);
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/library/igenebind/const_451');
  set_param('ckt_gentoggle_0_odeIdeal/library/igenebind/const_451','Value','1.');
  set_param('ckt_gentoggle_0_odeIdeal/library/igenebind/const_451','position',[278,419,328,439]);
  add_block('simulink/Sources/Constant','ckt_gentoggle_0_odeIdeal/library/igenebind/const_453');
  set_param('ckt_gentoggle_0_odeIdeal/library/igenebind/const_453','Value','1.');
  set_param('ckt_gentoggle_0_odeIdeal/library/igenebind/const_453','position',[236,902,286,922]);
  add_block('simulink/Math Operations/Product','ckt_gentoggle_0_odeIdeal/library/igenebind/mul_455');
  set_param('ckt_gentoggle_0_odeIdeal/library/igenebind/mul_455','Inputs','**');
  set_param('ckt_gentoggle_0_odeIdeal/library/igenebind/mul_455','position',[560,861,610,881]);
  add_line('ckt_gentoggle_0_odeIdeal/library/igenebind','_K/1','mul_455/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/igenebind','_TF/1','mul_455/2');
  add_block('simulink/Math Operations/Sum','ckt_gentoggle_0_odeIdeal/library/igenebind/sub_458');
  set_param('ckt_gentoggle_0_odeIdeal/library/igenebind/sub_458','Inputs','++');
  set_param('ckt_gentoggle_0_odeIdeal/library/igenebind/sub_458','position',[151,717,201,737]);
  add_line('ckt_gentoggle_0_odeIdeal/library/igenebind','const_453/1','sub_458/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/igenebind','mul_455/1','sub_458/2');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_0_odeIdeal/library/igenebind/div_461');
  set_param('ckt_gentoggle_0_odeIdeal/library/igenebind/div_461','Inputs','*/');
  set_param('ckt_gentoggle_0_odeIdeal/library/igenebind/div_461','position',[505,611,555,631]);
  add_line('ckt_gentoggle_0_odeIdeal/library/igenebind','const_451/1','div_461/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/igenebind','sub_458/1','div_461/2');
  add_block('simulink/Math Operations/Product','ckt_gentoggle_0_odeIdeal/library/igenebind/mul_464');
  set_param('ckt_gentoggle_0_odeIdeal/library/igenebind/mul_464','Inputs','**');
  set_param('ckt_gentoggle_0_odeIdeal/library/igenebind/mul_464','position',[292,306,342,326]);
  add_line('ckt_gentoggle_0_odeIdeal/library/igenebind','_Vmax/1','mul_464/1');
  add_line('ckt_gentoggle_0_odeIdeal/library/igenebind','div_461/1','mul_464/2');
  add_line('ckt_gentoggle_0_odeIdeal/library/igenebind','mul_464/1','_GE/1');
end
%
%
%
