
init:
	rm -rf git-repo
	git clone git@github.mit.edu:sachour/symcaml.git git-repo/symcaml
	cp git-repo/symcaml/src/*.ml .
	cp git-repo/symcaml/src/*.mly .
	cp git-repo/symcaml/src/*.mll .

clean:
	rm *.ml *.mll *.mly
