

all: build

install:
	cd spice; make install

build:
	cd Z3; make
	#cd dreal; make
	#cd leon; make
	#cd pycaml; make
	#cd spice; make

clean:
	cd Z3; make clean
	#cd dreal; make clean
	#cd leon; make clean
	#cd pycaml; make clean
	#cd spice; make clean
